//go:build !wasm

// Code generated by gen_pools.go; DO NOT EDIT.
// Word-shape i_p pool: 64 slots. Native only (see gen_pools.go).

package stubs

import (
	"sync/atomic"
	"unsafe"

	"github.com/mvm-sh/mvm/internal/runtype"
)

var (
	slotPoolWi_p [poolSizeWi_p]CoreFunc
	nextSlotWi_p atomic.Uint32
)

//go:noinline
func stubWi_p_0(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(0, recv, w0) }

//go:noinline
func stubWi_p_1(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(1, recv, w0) }

//go:noinline
func stubWi_p_2(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(2, recv, w0) }

//go:noinline
func stubWi_p_3(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(3, recv, w0) }

//go:noinline
func stubWi_p_4(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(4, recv, w0) }

//go:noinline
func stubWi_p_5(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(5, recv, w0) }

//go:noinline
func stubWi_p_6(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(6, recv, w0) }

//go:noinline
func stubWi_p_7(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(7, recv, w0) }

//go:noinline
func stubWi_p_8(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(8, recv, w0) }

//go:noinline
func stubWi_p_9(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(9, recv, w0) }

//go:noinline
func stubWi_p_10(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(10, recv, w0) }

//go:noinline
func stubWi_p_11(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(11, recv, w0) }

//go:noinline
func stubWi_p_12(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(12, recv, w0) }

//go:noinline
func stubWi_p_13(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(13, recv, w0) }

//go:noinline
func stubWi_p_14(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(14, recv, w0) }

//go:noinline
func stubWi_p_15(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(15, recv, w0) }

//go:noinline
func stubWi_p_16(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(16, recv, w0) }

//go:noinline
func stubWi_p_17(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(17, recv, w0) }

//go:noinline
func stubWi_p_18(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(18, recv, w0) }

//go:noinline
func stubWi_p_19(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(19, recv, w0) }

//go:noinline
func stubWi_p_20(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(20, recv, w0) }

//go:noinline
func stubWi_p_21(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(21, recv, w0) }

//go:noinline
func stubWi_p_22(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(22, recv, w0) }

//go:noinline
func stubWi_p_23(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(23, recv, w0) }

//go:noinline
func stubWi_p_24(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(24, recv, w0) }

//go:noinline
func stubWi_p_25(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(25, recv, w0) }

//go:noinline
func stubWi_p_26(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(26, recv, w0) }

//go:noinline
func stubWi_p_27(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(27, recv, w0) }

//go:noinline
func stubWi_p_28(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(28, recv, w0) }

//go:noinline
func stubWi_p_29(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(29, recv, w0) }

//go:noinline
func stubWi_p_30(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(30, recv, w0) }

//go:noinline
func stubWi_p_31(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(31, recv, w0) }

//go:noinline
func stubWi_p_32(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(32, recv, w0) }

//go:noinline
func stubWi_p_33(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(33, recv, w0) }

//go:noinline
func stubWi_p_34(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(34, recv, w0) }

//go:noinline
func stubWi_p_35(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(35, recv, w0) }

//go:noinline
func stubWi_p_36(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(36, recv, w0) }

//go:noinline
func stubWi_p_37(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(37, recv, w0) }

//go:noinline
func stubWi_p_38(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(38, recv, w0) }

//go:noinline
func stubWi_p_39(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(39, recv, w0) }

//go:noinline
func stubWi_p_40(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(40, recv, w0) }

//go:noinline
func stubWi_p_41(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(41, recv, w0) }

//go:noinline
func stubWi_p_42(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(42, recv, w0) }

//go:noinline
func stubWi_p_43(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(43, recv, w0) }

//go:noinline
func stubWi_p_44(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(44, recv, w0) }

//go:noinline
func stubWi_p_45(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(45, recv, w0) }

//go:noinline
func stubWi_p_46(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(46, recv, w0) }

//go:noinline
func stubWi_p_47(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(47, recv, w0) }

//go:noinline
func stubWi_p_48(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(48, recv, w0) }

//go:noinline
func stubWi_p_49(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(49, recv, w0) }

//go:noinline
func stubWi_p_50(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(50, recv, w0) }

//go:noinline
func stubWi_p_51(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(51, recv, w0) }

//go:noinline
func stubWi_p_52(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(52, recv, w0) }

//go:noinline
func stubWi_p_53(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(53, recv, w0) }

//go:noinline
func stubWi_p_54(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(54, recv, w0) }

//go:noinline
func stubWi_p_55(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(55, recv, w0) }

//go:noinline
func stubWi_p_56(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(56, recv, w0) }

//go:noinline
func stubWi_p_57(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(57, recv, w0) }

//go:noinline
func stubWi_p_58(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(58, recv, w0) }

//go:noinline
func stubWi_p_59(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(59, recv, w0) }

//go:noinline
func stubWi_p_60(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(60, recv, w0) }

//go:noinline
func stubWi_p_61(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(61, recv, w0) }

//go:noinline
func stubWi_p_62(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(62, recv, w0) }

//go:noinline
func stubWi_p_63(recv unsafe.Pointer, w0 uint64) unsafe.Pointer { return dispatchWi_p(63, recv, w0) }

var stubsWi_p [poolSizeWi_p]uintptr

func dispatchWi_p(slot uint32, recv unsafe.Pointer, w0 uint64) unsafe.Pointer {
	var pw [0]unsafe.Pointer
	var sw [1]uint64
	var fw [0]float64
	sw[0] = w0
	var rpw [1]unsafe.Pointer
	var rsw [0]uint64
	var rfw [0]float64
	if core := slotPoolWi_p[slot]; core != nil {
		core(recv, pw[:], sw[:], fw[:], rpw[:], rsw[:], rfw[:])
	}
	return rpw[0]
}

func init() {
	stubsWi_p[0] = runtype.FuncPC(stubWi_p_0)
	stubsWi_p[1] = runtype.FuncPC(stubWi_p_1)
	stubsWi_p[2] = runtype.FuncPC(stubWi_p_2)
	stubsWi_p[3] = runtype.FuncPC(stubWi_p_3)
	stubsWi_p[4] = runtype.FuncPC(stubWi_p_4)
	stubsWi_p[5] = runtype.FuncPC(stubWi_p_5)
	stubsWi_p[6] = runtype.FuncPC(stubWi_p_6)
	stubsWi_p[7] = runtype.FuncPC(stubWi_p_7)
	stubsWi_p[8] = runtype.FuncPC(stubWi_p_8)
	stubsWi_p[9] = runtype.FuncPC(stubWi_p_9)
	stubsWi_p[10] = runtype.FuncPC(stubWi_p_10)
	stubsWi_p[11] = runtype.FuncPC(stubWi_p_11)
	stubsWi_p[12] = runtype.FuncPC(stubWi_p_12)
	stubsWi_p[13] = runtype.FuncPC(stubWi_p_13)
	stubsWi_p[14] = runtype.FuncPC(stubWi_p_14)
	stubsWi_p[15] = runtype.FuncPC(stubWi_p_15)
	stubsWi_p[16] = runtype.FuncPC(stubWi_p_16)
	stubsWi_p[17] = runtype.FuncPC(stubWi_p_17)
	stubsWi_p[18] = runtype.FuncPC(stubWi_p_18)
	stubsWi_p[19] = runtype.FuncPC(stubWi_p_19)
	stubsWi_p[20] = runtype.FuncPC(stubWi_p_20)
	stubsWi_p[21] = runtype.FuncPC(stubWi_p_21)
	stubsWi_p[22] = runtype.FuncPC(stubWi_p_22)
	stubsWi_p[23] = runtype.FuncPC(stubWi_p_23)
	stubsWi_p[24] = runtype.FuncPC(stubWi_p_24)
	stubsWi_p[25] = runtype.FuncPC(stubWi_p_25)
	stubsWi_p[26] = runtype.FuncPC(stubWi_p_26)
	stubsWi_p[27] = runtype.FuncPC(stubWi_p_27)
	stubsWi_p[28] = runtype.FuncPC(stubWi_p_28)
	stubsWi_p[29] = runtype.FuncPC(stubWi_p_29)
	stubsWi_p[30] = runtype.FuncPC(stubWi_p_30)
	stubsWi_p[31] = runtype.FuncPC(stubWi_p_31)
	stubsWi_p[32] = runtype.FuncPC(stubWi_p_32)
	stubsWi_p[33] = runtype.FuncPC(stubWi_p_33)
	stubsWi_p[34] = runtype.FuncPC(stubWi_p_34)
	stubsWi_p[35] = runtype.FuncPC(stubWi_p_35)
	stubsWi_p[36] = runtype.FuncPC(stubWi_p_36)
	stubsWi_p[37] = runtype.FuncPC(stubWi_p_37)
	stubsWi_p[38] = runtype.FuncPC(stubWi_p_38)
	stubsWi_p[39] = runtype.FuncPC(stubWi_p_39)
	stubsWi_p[40] = runtype.FuncPC(stubWi_p_40)
	stubsWi_p[41] = runtype.FuncPC(stubWi_p_41)
	stubsWi_p[42] = runtype.FuncPC(stubWi_p_42)
	stubsWi_p[43] = runtype.FuncPC(stubWi_p_43)
	stubsWi_p[44] = runtype.FuncPC(stubWi_p_44)
	stubsWi_p[45] = runtype.FuncPC(stubWi_p_45)
	stubsWi_p[46] = runtype.FuncPC(stubWi_p_46)
	stubsWi_p[47] = runtype.FuncPC(stubWi_p_47)
	stubsWi_p[48] = runtype.FuncPC(stubWi_p_48)
	stubsWi_p[49] = runtype.FuncPC(stubWi_p_49)
	stubsWi_p[50] = runtype.FuncPC(stubWi_p_50)
	stubsWi_p[51] = runtype.FuncPC(stubWi_p_51)
	stubsWi_p[52] = runtype.FuncPC(stubWi_p_52)
	stubsWi_p[53] = runtype.FuncPC(stubWi_p_53)
	stubsWi_p[54] = runtype.FuncPC(stubWi_p_54)
	stubsWi_p[55] = runtype.FuncPC(stubWi_p_55)
	stubsWi_p[56] = runtype.FuncPC(stubWi_p_56)
	stubsWi_p[57] = runtype.FuncPC(stubWi_p_57)
	stubsWi_p[58] = runtype.FuncPC(stubWi_p_58)
	stubsWi_p[59] = runtype.FuncPC(stubWi_p_59)
	stubsWi_p[60] = runtype.FuncPC(stubWi_p_60)
	stubsWi_p[61] = runtype.FuncPC(stubWi_p_61)
	stubsWi_p[62] = runtype.FuncPC(stubWi_p_62)
	stubsWi_p[63] = runtype.FuncPC(stubWi_p_63)
	registerWordPool("i_p", &wordPool{
		next:  &nextSlotWi_p,
		cap:   poolSizeWi_p,
		stubs: stubsWi_p[:],
		slots: slotPoolWi_p[:],
		name:  "Wi_p",
	})
}
