//go:build !wasm

// Code generated by gen_pools.go; DO NOT EDIT.
// Word-shape ppipii_ pool: 64 slots. Native only (see gen_pools.go).

package stubs

import (
	"sync/atomic"
	"unsafe"

	"github.com/mvm-sh/mvm/internal/runtype"
)

var (
	slotPoolWppipii_ [poolSizeWppipii_]CoreFunc
	nextSlotWppipii_ atomic.Uint32
)

//go:noinline
func stubWppipii__0(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(0, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__1(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(1, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__2(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(2, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__3(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(3, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__4(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(4, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__5(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(5, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__6(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(6, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__7(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(7, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__8(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(8, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__9(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(9, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__10(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(10, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__11(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(11, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__12(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(12, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__13(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(13, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__14(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(14, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__15(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(15, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__16(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(16, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__17(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(17, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__18(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(18, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__19(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(19, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__20(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(20, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__21(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(21, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__22(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(22, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__23(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(23, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__24(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(24, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__25(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(25, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__26(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(26, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__27(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(27, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__28(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(28, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__29(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(29, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__30(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(30, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__31(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(31, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__32(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(32, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__33(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(33, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__34(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(34, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__35(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(35, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__36(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(36, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__37(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(37, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__38(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(38, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__39(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(39, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__40(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(40, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__41(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(41, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__42(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(42, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__43(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(43, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__44(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(44, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__45(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(45, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__46(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(46, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__47(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(47, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__48(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(48, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__49(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(49, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__50(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(50, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__51(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(51, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__52(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(52, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__53(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(53, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__54(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(54, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__55(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(55, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__56(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(56, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__57(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(57, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__58(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(58, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__59(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(59, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__60(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(60, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__61(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(61, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__62(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(62, recv, w0, w1, w2, w3, w4, w5)
}

//go:noinline
func stubWppipii__63(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	dispatchWppipii_(63, recv, w0, w1, w2, w3, w4, w5)
}

var stubsWppipii_ [poolSizeWppipii_]uintptr

func dispatchWppipii_(slot uint32, recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 uint64, w3 unsafe.Pointer, w4 uint64, w5 uint64) {
	var pw [3]unsafe.Pointer
	var sw [3]uint64
	var fw [0]float64
	pw[0] = w0
	pw[1] = w1
	sw[0] = w2
	pw[2] = w3
	sw[1] = w4
	sw[2] = w5
	var rpw [0]unsafe.Pointer
	var rsw [0]uint64
	var rfw [0]float64
	if core := slotPoolWppipii_[slot]; core != nil {
		core(recv, pw[:], sw[:], fw[:], rpw[:], rsw[:], rfw[:])
	}
}

func init() {
	stubsWppipii_[0] = runtype.FuncPC(stubWppipii__0)
	stubsWppipii_[1] = runtype.FuncPC(stubWppipii__1)
	stubsWppipii_[2] = runtype.FuncPC(stubWppipii__2)
	stubsWppipii_[3] = runtype.FuncPC(stubWppipii__3)
	stubsWppipii_[4] = runtype.FuncPC(stubWppipii__4)
	stubsWppipii_[5] = runtype.FuncPC(stubWppipii__5)
	stubsWppipii_[6] = runtype.FuncPC(stubWppipii__6)
	stubsWppipii_[7] = runtype.FuncPC(stubWppipii__7)
	stubsWppipii_[8] = runtype.FuncPC(stubWppipii__8)
	stubsWppipii_[9] = runtype.FuncPC(stubWppipii__9)
	stubsWppipii_[10] = runtype.FuncPC(stubWppipii__10)
	stubsWppipii_[11] = runtype.FuncPC(stubWppipii__11)
	stubsWppipii_[12] = runtype.FuncPC(stubWppipii__12)
	stubsWppipii_[13] = runtype.FuncPC(stubWppipii__13)
	stubsWppipii_[14] = runtype.FuncPC(stubWppipii__14)
	stubsWppipii_[15] = runtype.FuncPC(stubWppipii__15)
	stubsWppipii_[16] = runtype.FuncPC(stubWppipii__16)
	stubsWppipii_[17] = runtype.FuncPC(stubWppipii__17)
	stubsWppipii_[18] = runtype.FuncPC(stubWppipii__18)
	stubsWppipii_[19] = runtype.FuncPC(stubWppipii__19)
	stubsWppipii_[20] = runtype.FuncPC(stubWppipii__20)
	stubsWppipii_[21] = runtype.FuncPC(stubWppipii__21)
	stubsWppipii_[22] = runtype.FuncPC(stubWppipii__22)
	stubsWppipii_[23] = runtype.FuncPC(stubWppipii__23)
	stubsWppipii_[24] = runtype.FuncPC(stubWppipii__24)
	stubsWppipii_[25] = runtype.FuncPC(stubWppipii__25)
	stubsWppipii_[26] = runtype.FuncPC(stubWppipii__26)
	stubsWppipii_[27] = runtype.FuncPC(stubWppipii__27)
	stubsWppipii_[28] = runtype.FuncPC(stubWppipii__28)
	stubsWppipii_[29] = runtype.FuncPC(stubWppipii__29)
	stubsWppipii_[30] = runtype.FuncPC(stubWppipii__30)
	stubsWppipii_[31] = runtype.FuncPC(stubWppipii__31)
	stubsWppipii_[32] = runtype.FuncPC(stubWppipii__32)
	stubsWppipii_[33] = runtype.FuncPC(stubWppipii__33)
	stubsWppipii_[34] = runtype.FuncPC(stubWppipii__34)
	stubsWppipii_[35] = runtype.FuncPC(stubWppipii__35)
	stubsWppipii_[36] = runtype.FuncPC(stubWppipii__36)
	stubsWppipii_[37] = runtype.FuncPC(stubWppipii__37)
	stubsWppipii_[38] = runtype.FuncPC(stubWppipii__38)
	stubsWppipii_[39] = runtype.FuncPC(stubWppipii__39)
	stubsWppipii_[40] = runtype.FuncPC(stubWppipii__40)
	stubsWppipii_[41] = runtype.FuncPC(stubWppipii__41)
	stubsWppipii_[42] = runtype.FuncPC(stubWppipii__42)
	stubsWppipii_[43] = runtype.FuncPC(stubWppipii__43)
	stubsWppipii_[44] = runtype.FuncPC(stubWppipii__44)
	stubsWppipii_[45] = runtype.FuncPC(stubWppipii__45)
	stubsWppipii_[46] = runtype.FuncPC(stubWppipii__46)
	stubsWppipii_[47] = runtype.FuncPC(stubWppipii__47)
	stubsWppipii_[48] = runtype.FuncPC(stubWppipii__48)
	stubsWppipii_[49] = runtype.FuncPC(stubWppipii__49)
	stubsWppipii_[50] = runtype.FuncPC(stubWppipii__50)
	stubsWppipii_[51] = runtype.FuncPC(stubWppipii__51)
	stubsWppipii_[52] = runtype.FuncPC(stubWppipii__52)
	stubsWppipii_[53] = runtype.FuncPC(stubWppipii__53)
	stubsWppipii_[54] = runtype.FuncPC(stubWppipii__54)
	stubsWppipii_[55] = runtype.FuncPC(stubWppipii__55)
	stubsWppipii_[56] = runtype.FuncPC(stubWppipii__56)
	stubsWppipii_[57] = runtype.FuncPC(stubWppipii__57)
	stubsWppipii_[58] = runtype.FuncPC(stubWppipii__58)
	stubsWppipii_[59] = runtype.FuncPC(stubWppipii__59)
	stubsWppipii_[60] = runtype.FuncPC(stubWppipii__60)
	stubsWppipii_[61] = runtype.FuncPC(stubWppipii__61)
	stubsWppipii_[62] = runtype.FuncPC(stubWppipii__62)
	stubsWppipii_[63] = runtype.FuncPC(stubWppipii__63)
	registerWordPool("ppipii_", &wordPool{
		next:  &nextSlotWppipii_,
		cap:   poolSizeWppipii_,
		stubs: stubsWppipii_[:],
		slots: slotPoolWppipii_[:],
		name:  "Wppipii_",
	})
}
