//go:build !wasm

// Code generated by gen_pools.go; DO NOT EDIT.
// Word-shape pipii_ pool: 256 slots. Native only (see gen_pools.go).

package stubs

import (
	"sync/atomic"
	"unsafe"

	"github.com/mvm-sh/mvm/internal/runtype"
)

var (
	slotPoolWpipii_ [poolSizeWpipii_]CoreFunc
	nextSlotWpipii_ atomic.Uint32
)

//go:noinline
func stubWpipii__0(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(0, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__1(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(1, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__2(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(2, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__3(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(3, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__4(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(4, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__5(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(5, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__6(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(6, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__7(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(7, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__8(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(8, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__9(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(9, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__10(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(10, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__11(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(11, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__12(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(12, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__13(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(13, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__14(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(14, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__15(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(15, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__16(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(16, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__17(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(17, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__18(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(18, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__19(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(19, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__20(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(20, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__21(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(21, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__22(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(22, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__23(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(23, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__24(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(24, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__25(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(25, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__26(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(26, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__27(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(27, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__28(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(28, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__29(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(29, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__30(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(30, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__31(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(31, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__32(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(32, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__33(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(33, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__34(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(34, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__35(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(35, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__36(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(36, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__37(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(37, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__38(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(38, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__39(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(39, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__40(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(40, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__41(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(41, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__42(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(42, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__43(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(43, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__44(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(44, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__45(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(45, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__46(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(46, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__47(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(47, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__48(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(48, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__49(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(49, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__50(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(50, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__51(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(51, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__52(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(52, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__53(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(53, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__54(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(54, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__55(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(55, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__56(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(56, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__57(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(57, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__58(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(58, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__59(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(59, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__60(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(60, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__61(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(61, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__62(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(62, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__63(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(63, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__64(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(64, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__65(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(65, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__66(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(66, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__67(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(67, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__68(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(68, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__69(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(69, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__70(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(70, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__71(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(71, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__72(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(72, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__73(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(73, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__74(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(74, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__75(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(75, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__76(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(76, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__77(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(77, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__78(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(78, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__79(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(79, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__80(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(80, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__81(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(81, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__82(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(82, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__83(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(83, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__84(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(84, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__85(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(85, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__86(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(86, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__87(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(87, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__88(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(88, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__89(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(89, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__90(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(90, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__91(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(91, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__92(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(92, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__93(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(93, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__94(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(94, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__95(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(95, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__96(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(96, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__97(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(97, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__98(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(98, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__99(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(99, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__100(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(100, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__101(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(101, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__102(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(102, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__103(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(103, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__104(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(104, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__105(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(105, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__106(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(106, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__107(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(107, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__108(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(108, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__109(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(109, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__110(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(110, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__111(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(111, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__112(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(112, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__113(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(113, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__114(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(114, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__115(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(115, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__116(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(116, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__117(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(117, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__118(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(118, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__119(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(119, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__120(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(120, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__121(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(121, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__122(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(122, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__123(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(123, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__124(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(124, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__125(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(125, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__126(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(126, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__127(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(127, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__128(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(128, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__129(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(129, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__130(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(130, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__131(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(131, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__132(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(132, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__133(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(133, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__134(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(134, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__135(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(135, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__136(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(136, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__137(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(137, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__138(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(138, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__139(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(139, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__140(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(140, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__141(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(141, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__142(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(142, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__143(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(143, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__144(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(144, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__145(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(145, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__146(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(146, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__147(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(147, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__148(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(148, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__149(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(149, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__150(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(150, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__151(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(151, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__152(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(152, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__153(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(153, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__154(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(154, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__155(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(155, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__156(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(156, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__157(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(157, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__158(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(158, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__159(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(159, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__160(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(160, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__161(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(161, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__162(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(162, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__163(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(163, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__164(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(164, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__165(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(165, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__166(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(166, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__167(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(167, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__168(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(168, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__169(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(169, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__170(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(170, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__171(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(171, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__172(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(172, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__173(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(173, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__174(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(174, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__175(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(175, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__176(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(176, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__177(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(177, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__178(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(178, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__179(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(179, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__180(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(180, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__181(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(181, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__182(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(182, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__183(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(183, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__184(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(184, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__185(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(185, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__186(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(186, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__187(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(187, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__188(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(188, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__189(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(189, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__190(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(190, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__191(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(191, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__192(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(192, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__193(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(193, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__194(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(194, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__195(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(195, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__196(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(196, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__197(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(197, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__198(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(198, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__199(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(199, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__200(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(200, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__201(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(201, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__202(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(202, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__203(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(203, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__204(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(204, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__205(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(205, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__206(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(206, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__207(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(207, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__208(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(208, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__209(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(209, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__210(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(210, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__211(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(211, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__212(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(212, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__213(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(213, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__214(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(214, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__215(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(215, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__216(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(216, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__217(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(217, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__218(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(218, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__219(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(219, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__220(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(220, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__221(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(221, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__222(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(222, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__223(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(223, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__224(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(224, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__225(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(225, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__226(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(226, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__227(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(227, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__228(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(228, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__229(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(229, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__230(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(230, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__231(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(231, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__232(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(232, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__233(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(233, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__234(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(234, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__235(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(235, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__236(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(236, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__237(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(237, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__238(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(238, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__239(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(239, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__240(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(240, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__241(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(241, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__242(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(242, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__243(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(243, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__244(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(244, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__245(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(245, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__246(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(246, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__247(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(247, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__248(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(248, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__249(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(249, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__250(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(250, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__251(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(251, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__252(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(252, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__253(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(253, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__254(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(254, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii__255(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	dispatchWpipii_(255, recv, w0, w1, w2, w3, w4)
}

var stubsWpipii_ [poolSizeWpipii_]uintptr

func dispatchWpipii_(slot uint32, recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) {
	var pw [2]unsafe.Pointer
	var sw [3]uint64
	var fw [0]float64
	pw[0] = w0
	sw[0] = w1
	pw[1] = w2
	sw[1] = w3
	sw[2] = w4
	var rpw [0]unsafe.Pointer
	var rsw [0]uint64
	var rfw [0]float64
	if core := slotPoolWpipii_[slot]; core != nil {
		core(recv, pw[:], sw[:], fw[:], rpw[:], rsw[:], rfw[:])
	}
}

func init() {
	stubsWpipii_[0] = runtype.FuncPC(stubWpipii__0)
	stubsWpipii_[1] = runtype.FuncPC(stubWpipii__1)
	stubsWpipii_[2] = runtype.FuncPC(stubWpipii__2)
	stubsWpipii_[3] = runtype.FuncPC(stubWpipii__3)
	stubsWpipii_[4] = runtype.FuncPC(stubWpipii__4)
	stubsWpipii_[5] = runtype.FuncPC(stubWpipii__5)
	stubsWpipii_[6] = runtype.FuncPC(stubWpipii__6)
	stubsWpipii_[7] = runtype.FuncPC(stubWpipii__7)
	stubsWpipii_[8] = runtype.FuncPC(stubWpipii__8)
	stubsWpipii_[9] = runtype.FuncPC(stubWpipii__9)
	stubsWpipii_[10] = runtype.FuncPC(stubWpipii__10)
	stubsWpipii_[11] = runtype.FuncPC(stubWpipii__11)
	stubsWpipii_[12] = runtype.FuncPC(stubWpipii__12)
	stubsWpipii_[13] = runtype.FuncPC(stubWpipii__13)
	stubsWpipii_[14] = runtype.FuncPC(stubWpipii__14)
	stubsWpipii_[15] = runtype.FuncPC(stubWpipii__15)
	stubsWpipii_[16] = runtype.FuncPC(stubWpipii__16)
	stubsWpipii_[17] = runtype.FuncPC(stubWpipii__17)
	stubsWpipii_[18] = runtype.FuncPC(stubWpipii__18)
	stubsWpipii_[19] = runtype.FuncPC(stubWpipii__19)
	stubsWpipii_[20] = runtype.FuncPC(stubWpipii__20)
	stubsWpipii_[21] = runtype.FuncPC(stubWpipii__21)
	stubsWpipii_[22] = runtype.FuncPC(stubWpipii__22)
	stubsWpipii_[23] = runtype.FuncPC(stubWpipii__23)
	stubsWpipii_[24] = runtype.FuncPC(stubWpipii__24)
	stubsWpipii_[25] = runtype.FuncPC(stubWpipii__25)
	stubsWpipii_[26] = runtype.FuncPC(stubWpipii__26)
	stubsWpipii_[27] = runtype.FuncPC(stubWpipii__27)
	stubsWpipii_[28] = runtype.FuncPC(stubWpipii__28)
	stubsWpipii_[29] = runtype.FuncPC(stubWpipii__29)
	stubsWpipii_[30] = runtype.FuncPC(stubWpipii__30)
	stubsWpipii_[31] = runtype.FuncPC(stubWpipii__31)
	stubsWpipii_[32] = runtype.FuncPC(stubWpipii__32)
	stubsWpipii_[33] = runtype.FuncPC(stubWpipii__33)
	stubsWpipii_[34] = runtype.FuncPC(stubWpipii__34)
	stubsWpipii_[35] = runtype.FuncPC(stubWpipii__35)
	stubsWpipii_[36] = runtype.FuncPC(stubWpipii__36)
	stubsWpipii_[37] = runtype.FuncPC(stubWpipii__37)
	stubsWpipii_[38] = runtype.FuncPC(stubWpipii__38)
	stubsWpipii_[39] = runtype.FuncPC(stubWpipii__39)
	stubsWpipii_[40] = runtype.FuncPC(stubWpipii__40)
	stubsWpipii_[41] = runtype.FuncPC(stubWpipii__41)
	stubsWpipii_[42] = runtype.FuncPC(stubWpipii__42)
	stubsWpipii_[43] = runtype.FuncPC(stubWpipii__43)
	stubsWpipii_[44] = runtype.FuncPC(stubWpipii__44)
	stubsWpipii_[45] = runtype.FuncPC(stubWpipii__45)
	stubsWpipii_[46] = runtype.FuncPC(stubWpipii__46)
	stubsWpipii_[47] = runtype.FuncPC(stubWpipii__47)
	stubsWpipii_[48] = runtype.FuncPC(stubWpipii__48)
	stubsWpipii_[49] = runtype.FuncPC(stubWpipii__49)
	stubsWpipii_[50] = runtype.FuncPC(stubWpipii__50)
	stubsWpipii_[51] = runtype.FuncPC(stubWpipii__51)
	stubsWpipii_[52] = runtype.FuncPC(stubWpipii__52)
	stubsWpipii_[53] = runtype.FuncPC(stubWpipii__53)
	stubsWpipii_[54] = runtype.FuncPC(stubWpipii__54)
	stubsWpipii_[55] = runtype.FuncPC(stubWpipii__55)
	stubsWpipii_[56] = runtype.FuncPC(stubWpipii__56)
	stubsWpipii_[57] = runtype.FuncPC(stubWpipii__57)
	stubsWpipii_[58] = runtype.FuncPC(stubWpipii__58)
	stubsWpipii_[59] = runtype.FuncPC(stubWpipii__59)
	stubsWpipii_[60] = runtype.FuncPC(stubWpipii__60)
	stubsWpipii_[61] = runtype.FuncPC(stubWpipii__61)
	stubsWpipii_[62] = runtype.FuncPC(stubWpipii__62)
	stubsWpipii_[63] = runtype.FuncPC(stubWpipii__63)
	stubsWpipii_[64] = runtype.FuncPC(stubWpipii__64)
	stubsWpipii_[65] = runtype.FuncPC(stubWpipii__65)
	stubsWpipii_[66] = runtype.FuncPC(stubWpipii__66)
	stubsWpipii_[67] = runtype.FuncPC(stubWpipii__67)
	stubsWpipii_[68] = runtype.FuncPC(stubWpipii__68)
	stubsWpipii_[69] = runtype.FuncPC(stubWpipii__69)
	stubsWpipii_[70] = runtype.FuncPC(stubWpipii__70)
	stubsWpipii_[71] = runtype.FuncPC(stubWpipii__71)
	stubsWpipii_[72] = runtype.FuncPC(stubWpipii__72)
	stubsWpipii_[73] = runtype.FuncPC(stubWpipii__73)
	stubsWpipii_[74] = runtype.FuncPC(stubWpipii__74)
	stubsWpipii_[75] = runtype.FuncPC(stubWpipii__75)
	stubsWpipii_[76] = runtype.FuncPC(stubWpipii__76)
	stubsWpipii_[77] = runtype.FuncPC(stubWpipii__77)
	stubsWpipii_[78] = runtype.FuncPC(stubWpipii__78)
	stubsWpipii_[79] = runtype.FuncPC(stubWpipii__79)
	stubsWpipii_[80] = runtype.FuncPC(stubWpipii__80)
	stubsWpipii_[81] = runtype.FuncPC(stubWpipii__81)
	stubsWpipii_[82] = runtype.FuncPC(stubWpipii__82)
	stubsWpipii_[83] = runtype.FuncPC(stubWpipii__83)
	stubsWpipii_[84] = runtype.FuncPC(stubWpipii__84)
	stubsWpipii_[85] = runtype.FuncPC(stubWpipii__85)
	stubsWpipii_[86] = runtype.FuncPC(stubWpipii__86)
	stubsWpipii_[87] = runtype.FuncPC(stubWpipii__87)
	stubsWpipii_[88] = runtype.FuncPC(stubWpipii__88)
	stubsWpipii_[89] = runtype.FuncPC(stubWpipii__89)
	stubsWpipii_[90] = runtype.FuncPC(stubWpipii__90)
	stubsWpipii_[91] = runtype.FuncPC(stubWpipii__91)
	stubsWpipii_[92] = runtype.FuncPC(stubWpipii__92)
	stubsWpipii_[93] = runtype.FuncPC(stubWpipii__93)
	stubsWpipii_[94] = runtype.FuncPC(stubWpipii__94)
	stubsWpipii_[95] = runtype.FuncPC(stubWpipii__95)
	stubsWpipii_[96] = runtype.FuncPC(stubWpipii__96)
	stubsWpipii_[97] = runtype.FuncPC(stubWpipii__97)
	stubsWpipii_[98] = runtype.FuncPC(stubWpipii__98)
	stubsWpipii_[99] = runtype.FuncPC(stubWpipii__99)
	stubsWpipii_[100] = runtype.FuncPC(stubWpipii__100)
	stubsWpipii_[101] = runtype.FuncPC(stubWpipii__101)
	stubsWpipii_[102] = runtype.FuncPC(stubWpipii__102)
	stubsWpipii_[103] = runtype.FuncPC(stubWpipii__103)
	stubsWpipii_[104] = runtype.FuncPC(stubWpipii__104)
	stubsWpipii_[105] = runtype.FuncPC(stubWpipii__105)
	stubsWpipii_[106] = runtype.FuncPC(stubWpipii__106)
	stubsWpipii_[107] = runtype.FuncPC(stubWpipii__107)
	stubsWpipii_[108] = runtype.FuncPC(stubWpipii__108)
	stubsWpipii_[109] = runtype.FuncPC(stubWpipii__109)
	stubsWpipii_[110] = runtype.FuncPC(stubWpipii__110)
	stubsWpipii_[111] = runtype.FuncPC(stubWpipii__111)
	stubsWpipii_[112] = runtype.FuncPC(stubWpipii__112)
	stubsWpipii_[113] = runtype.FuncPC(stubWpipii__113)
	stubsWpipii_[114] = runtype.FuncPC(stubWpipii__114)
	stubsWpipii_[115] = runtype.FuncPC(stubWpipii__115)
	stubsWpipii_[116] = runtype.FuncPC(stubWpipii__116)
	stubsWpipii_[117] = runtype.FuncPC(stubWpipii__117)
	stubsWpipii_[118] = runtype.FuncPC(stubWpipii__118)
	stubsWpipii_[119] = runtype.FuncPC(stubWpipii__119)
	stubsWpipii_[120] = runtype.FuncPC(stubWpipii__120)
	stubsWpipii_[121] = runtype.FuncPC(stubWpipii__121)
	stubsWpipii_[122] = runtype.FuncPC(stubWpipii__122)
	stubsWpipii_[123] = runtype.FuncPC(stubWpipii__123)
	stubsWpipii_[124] = runtype.FuncPC(stubWpipii__124)
	stubsWpipii_[125] = runtype.FuncPC(stubWpipii__125)
	stubsWpipii_[126] = runtype.FuncPC(stubWpipii__126)
	stubsWpipii_[127] = runtype.FuncPC(stubWpipii__127)
	stubsWpipii_[128] = runtype.FuncPC(stubWpipii__128)
	stubsWpipii_[129] = runtype.FuncPC(stubWpipii__129)
	stubsWpipii_[130] = runtype.FuncPC(stubWpipii__130)
	stubsWpipii_[131] = runtype.FuncPC(stubWpipii__131)
	stubsWpipii_[132] = runtype.FuncPC(stubWpipii__132)
	stubsWpipii_[133] = runtype.FuncPC(stubWpipii__133)
	stubsWpipii_[134] = runtype.FuncPC(stubWpipii__134)
	stubsWpipii_[135] = runtype.FuncPC(stubWpipii__135)
	stubsWpipii_[136] = runtype.FuncPC(stubWpipii__136)
	stubsWpipii_[137] = runtype.FuncPC(stubWpipii__137)
	stubsWpipii_[138] = runtype.FuncPC(stubWpipii__138)
	stubsWpipii_[139] = runtype.FuncPC(stubWpipii__139)
	stubsWpipii_[140] = runtype.FuncPC(stubWpipii__140)
	stubsWpipii_[141] = runtype.FuncPC(stubWpipii__141)
	stubsWpipii_[142] = runtype.FuncPC(stubWpipii__142)
	stubsWpipii_[143] = runtype.FuncPC(stubWpipii__143)
	stubsWpipii_[144] = runtype.FuncPC(stubWpipii__144)
	stubsWpipii_[145] = runtype.FuncPC(stubWpipii__145)
	stubsWpipii_[146] = runtype.FuncPC(stubWpipii__146)
	stubsWpipii_[147] = runtype.FuncPC(stubWpipii__147)
	stubsWpipii_[148] = runtype.FuncPC(stubWpipii__148)
	stubsWpipii_[149] = runtype.FuncPC(stubWpipii__149)
	stubsWpipii_[150] = runtype.FuncPC(stubWpipii__150)
	stubsWpipii_[151] = runtype.FuncPC(stubWpipii__151)
	stubsWpipii_[152] = runtype.FuncPC(stubWpipii__152)
	stubsWpipii_[153] = runtype.FuncPC(stubWpipii__153)
	stubsWpipii_[154] = runtype.FuncPC(stubWpipii__154)
	stubsWpipii_[155] = runtype.FuncPC(stubWpipii__155)
	stubsWpipii_[156] = runtype.FuncPC(stubWpipii__156)
	stubsWpipii_[157] = runtype.FuncPC(stubWpipii__157)
	stubsWpipii_[158] = runtype.FuncPC(stubWpipii__158)
	stubsWpipii_[159] = runtype.FuncPC(stubWpipii__159)
	stubsWpipii_[160] = runtype.FuncPC(stubWpipii__160)
	stubsWpipii_[161] = runtype.FuncPC(stubWpipii__161)
	stubsWpipii_[162] = runtype.FuncPC(stubWpipii__162)
	stubsWpipii_[163] = runtype.FuncPC(stubWpipii__163)
	stubsWpipii_[164] = runtype.FuncPC(stubWpipii__164)
	stubsWpipii_[165] = runtype.FuncPC(stubWpipii__165)
	stubsWpipii_[166] = runtype.FuncPC(stubWpipii__166)
	stubsWpipii_[167] = runtype.FuncPC(stubWpipii__167)
	stubsWpipii_[168] = runtype.FuncPC(stubWpipii__168)
	stubsWpipii_[169] = runtype.FuncPC(stubWpipii__169)
	stubsWpipii_[170] = runtype.FuncPC(stubWpipii__170)
	stubsWpipii_[171] = runtype.FuncPC(stubWpipii__171)
	stubsWpipii_[172] = runtype.FuncPC(stubWpipii__172)
	stubsWpipii_[173] = runtype.FuncPC(stubWpipii__173)
	stubsWpipii_[174] = runtype.FuncPC(stubWpipii__174)
	stubsWpipii_[175] = runtype.FuncPC(stubWpipii__175)
	stubsWpipii_[176] = runtype.FuncPC(stubWpipii__176)
	stubsWpipii_[177] = runtype.FuncPC(stubWpipii__177)
	stubsWpipii_[178] = runtype.FuncPC(stubWpipii__178)
	stubsWpipii_[179] = runtype.FuncPC(stubWpipii__179)
	stubsWpipii_[180] = runtype.FuncPC(stubWpipii__180)
	stubsWpipii_[181] = runtype.FuncPC(stubWpipii__181)
	stubsWpipii_[182] = runtype.FuncPC(stubWpipii__182)
	stubsWpipii_[183] = runtype.FuncPC(stubWpipii__183)
	stubsWpipii_[184] = runtype.FuncPC(stubWpipii__184)
	stubsWpipii_[185] = runtype.FuncPC(stubWpipii__185)
	stubsWpipii_[186] = runtype.FuncPC(stubWpipii__186)
	stubsWpipii_[187] = runtype.FuncPC(stubWpipii__187)
	stubsWpipii_[188] = runtype.FuncPC(stubWpipii__188)
	stubsWpipii_[189] = runtype.FuncPC(stubWpipii__189)
	stubsWpipii_[190] = runtype.FuncPC(stubWpipii__190)
	stubsWpipii_[191] = runtype.FuncPC(stubWpipii__191)
	stubsWpipii_[192] = runtype.FuncPC(stubWpipii__192)
	stubsWpipii_[193] = runtype.FuncPC(stubWpipii__193)
	stubsWpipii_[194] = runtype.FuncPC(stubWpipii__194)
	stubsWpipii_[195] = runtype.FuncPC(stubWpipii__195)
	stubsWpipii_[196] = runtype.FuncPC(stubWpipii__196)
	stubsWpipii_[197] = runtype.FuncPC(stubWpipii__197)
	stubsWpipii_[198] = runtype.FuncPC(stubWpipii__198)
	stubsWpipii_[199] = runtype.FuncPC(stubWpipii__199)
	stubsWpipii_[200] = runtype.FuncPC(stubWpipii__200)
	stubsWpipii_[201] = runtype.FuncPC(stubWpipii__201)
	stubsWpipii_[202] = runtype.FuncPC(stubWpipii__202)
	stubsWpipii_[203] = runtype.FuncPC(stubWpipii__203)
	stubsWpipii_[204] = runtype.FuncPC(stubWpipii__204)
	stubsWpipii_[205] = runtype.FuncPC(stubWpipii__205)
	stubsWpipii_[206] = runtype.FuncPC(stubWpipii__206)
	stubsWpipii_[207] = runtype.FuncPC(stubWpipii__207)
	stubsWpipii_[208] = runtype.FuncPC(stubWpipii__208)
	stubsWpipii_[209] = runtype.FuncPC(stubWpipii__209)
	stubsWpipii_[210] = runtype.FuncPC(stubWpipii__210)
	stubsWpipii_[211] = runtype.FuncPC(stubWpipii__211)
	stubsWpipii_[212] = runtype.FuncPC(stubWpipii__212)
	stubsWpipii_[213] = runtype.FuncPC(stubWpipii__213)
	stubsWpipii_[214] = runtype.FuncPC(stubWpipii__214)
	stubsWpipii_[215] = runtype.FuncPC(stubWpipii__215)
	stubsWpipii_[216] = runtype.FuncPC(stubWpipii__216)
	stubsWpipii_[217] = runtype.FuncPC(stubWpipii__217)
	stubsWpipii_[218] = runtype.FuncPC(stubWpipii__218)
	stubsWpipii_[219] = runtype.FuncPC(stubWpipii__219)
	stubsWpipii_[220] = runtype.FuncPC(stubWpipii__220)
	stubsWpipii_[221] = runtype.FuncPC(stubWpipii__221)
	stubsWpipii_[222] = runtype.FuncPC(stubWpipii__222)
	stubsWpipii_[223] = runtype.FuncPC(stubWpipii__223)
	stubsWpipii_[224] = runtype.FuncPC(stubWpipii__224)
	stubsWpipii_[225] = runtype.FuncPC(stubWpipii__225)
	stubsWpipii_[226] = runtype.FuncPC(stubWpipii__226)
	stubsWpipii_[227] = runtype.FuncPC(stubWpipii__227)
	stubsWpipii_[228] = runtype.FuncPC(stubWpipii__228)
	stubsWpipii_[229] = runtype.FuncPC(stubWpipii__229)
	stubsWpipii_[230] = runtype.FuncPC(stubWpipii__230)
	stubsWpipii_[231] = runtype.FuncPC(stubWpipii__231)
	stubsWpipii_[232] = runtype.FuncPC(stubWpipii__232)
	stubsWpipii_[233] = runtype.FuncPC(stubWpipii__233)
	stubsWpipii_[234] = runtype.FuncPC(stubWpipii__234)
	stubsWpipii_[235] = runtype.FuncPC(stubWpipii__235)
	stubsWpipii_[236] = runtype.FuncPC(stubWpipii__236)
	stubsWpipii_[237] = runtype.FuncPC(stubWpipii__237)
	stubsWpipii_[238] = runtype.FuncPC(stubWpipii__238)
	stubsWpipii_[239] = runtype.FuncPC(stubWpipii__239)
	stubsWpipii_[240] = runtype.FuncPC(stubWpipii__240)
	stubsWpipii_[241] = runtype.FuncPC(stubWpipii__241)
	stubsWpipii_[242] = runtype.FuncPC(stubWpipii__242)
	stubsWpipii_[243] = runtype.FuncPC(stubWpipii__243)
	stubsWpipii_[244] = runtype.FuncPC(stubWpipii__244)
	stubsWpipii_[245] = runtype.FuncPC(stubWpipii__245)
	stubsWpipii_[246] = runtype.FuncPC(stubWpipii__246)
	stubsWpipii_[247] = runtype.FuncPC(stubWpipii__247)
	stubsWpipii_[248] = runtype.FuncPC(stubWpipii__248)
	stubsWpipii_[249] = runtype.FuncPC(stubWpipii__249)
	stubsWpipii_[250] = runtype.FuncPC(stubWpipii__250)
	stubsWpipii_[251] = runtype.FuncPC(stubWpipii__251)
	stubsWpipii_[252] = runtype.FuncPC(stubWpipii__252)
	stubsWpipii_[253] = runtype.FuncPC(stubWpipii__253)
	stubsWpipii_[254] = runtype.FuncPC(stubWpipii__254)
	stubsWpipii_[255] = runtype.FuncPC(stubWpipii__255)
	registerWordPool("pipii_", &wordPool{
		next:  &nextSlotWpipii_,
		cap:   poolSizeWpipii_,
		stubs: stubsWpipii_[:],
		slots: slotPoolWpipii_[:],
		name:  "Wpipii_",
	})
}
