//go:build go1.25 && !wasm

// Code generated by cmd/extract; DO NOT EDIT.

package ext

import (
	"crypto"
	"reflect"

	"github.com/mvm-sh/mvm/stdlib"
)

func init() {
	m := stdlib.Values["crypto"]
	m["SignMessage"] = reflect.ValueOf(crypto.SignMessage)
	m["MessageSigner"] = reflect.ValueOf((*crypto.MessageSigner)(nil))
}
