//go:build !wasm

// Code generated by gen_pools.go; DO NOT EDIT.
// Word-shape ppp_ppp pool: 256 slots. Native only (see gen_pools.go).

package stubs

import (
	"sync/atomic"
	"unsafe"

	"github.com/mvm-sh/mvm/runtype"
)

var (
	slotPoolWppp_ppp [poolSizeWppp_ppp]CoreFunc
	nextSlotWppp_ppp atomic.Uint32
)

//go:noinline
func stubWppp_ppp_0(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(0, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_1(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(1, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_2(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(2, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_3(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(3, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_4(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(4, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_5(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(5, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_6(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(6, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_7(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(7, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_8(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(8, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_9(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(9, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_10(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(10, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_11(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(11, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_12(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(12, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_13(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(13, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_14(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(14, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_15(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(15, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_16(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(16, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_17(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(17, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_18(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(18, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_19(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(19, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_20(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(20, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_21(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(21, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_22(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(22, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_23(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(23, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_24(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(24, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_25(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(25, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_26(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(26, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_27(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(27, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_28(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(28, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_29(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(29, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_30(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(30, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_31(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(31, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_32(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(32, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_33(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(33, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_34(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(34, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_35(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(35, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_36(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(36, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_37(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(37, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_38(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(38, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_39(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(39, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_40(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(40, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_41(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(41, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_42(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(42, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_43(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(43, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_44(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(44, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_45(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(45, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_46(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(46, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_47(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(47, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_48(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(48, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_49(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(49, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_50(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(50, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_51(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(51, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_52(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(52, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_53(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(53, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_54(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(54, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_55(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(55, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_56(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(56, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_57(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(57, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_58(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(58, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_59(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(59, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_60(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(60, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_61(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(61, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_62(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(62, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_63(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(63, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_64(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(64, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_65(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(65, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_66(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(66, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_67(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(67, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_68(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(68, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_69(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(69, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_70(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(70, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_71(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(71, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_72(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(72, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_73(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(73, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_74(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(74, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_75(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(75, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_76(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(76, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_77(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(77, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_78(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(78, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_79(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(79, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_80(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(80, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_81(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(81, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_82(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(82, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_83(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(83, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_84(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(84, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_85(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(85, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_86(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(86, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_87(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(87, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_88(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(88, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_89(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(89, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_90(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(90, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_91(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(91, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_92(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(92, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_93(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(93, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_94(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(94, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_95(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(95, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_96(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(96, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_97(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(97, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_98(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(98, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_99(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(99, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_100(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(100, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_101(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(101, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_102(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(102, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_103(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(103, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_104(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(104, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_105(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(105, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_106(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(106, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_107(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(107, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_108(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(108, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_109(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(109, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_110(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(110, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_111(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(111, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_112(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(112, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_113(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(113, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_114(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(114, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_115(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(115, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_116(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(116, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_117(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(117, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_118(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(118, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_119(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(119, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_120(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(120, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_121(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(121, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_122(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(122, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_123(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(123, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_124(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(124, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_125(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(125, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_126(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(126, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_127(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(127, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_128(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(128, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_129(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(129, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_130(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(130, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_131(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(131, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_132(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(132, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_133(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(133, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_134(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(134, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_135(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(135, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_136(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(136, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_137(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(137, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_138(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(138, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_139(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(139, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_140(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(140, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_141(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(141, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_142(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(142, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_143(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(143, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_144(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(144, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_145(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(145, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_146(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(146, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_147(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(147, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_148(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(148, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_149(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(149, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_150(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(150, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_151(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(151, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_152(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(152, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_153(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(153, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_154(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(154, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_155(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(155, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_156(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(156, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_157(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(157, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_158(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(158, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_159(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(159, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_160(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(160, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_161(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(161, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_162(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(162, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_163(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(163, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_164(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(164, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_165(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(165, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_166(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(166, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_167(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(167, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_168(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(168, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_169(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(169, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_170(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(170, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_171(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(171, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_172(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(172, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_173(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(173, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_174(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(174, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_175(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(175, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_176(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(176, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_177(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(177, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_178(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(178, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_179(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(179, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_180(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(180, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_181(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(181, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_182(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(182, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_183(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(183, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_184(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(184, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_185(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(185, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_186(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(186, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_187(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(187, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_188(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(188, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_189(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(189, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_190(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(190, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_191(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(191, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_192(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(192, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_193(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(193, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_194(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(194, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_195(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(195, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_196(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(196, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_197(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(197, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_198(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(198, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_199(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(199, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_200(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(200, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_201(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(201, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_202(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(202, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_203(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(203, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_204(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(204, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_205(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(205, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_206(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(206, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_207(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(207, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_208(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(208, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_209(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(209, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_210(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(210, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_211(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(211, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_212(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(212, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_213(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(213, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_214(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(214, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_215(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(215, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_216(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(216, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_217(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(217, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_218(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(218, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_219(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(219, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_220(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(220, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_221(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(221, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_222(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(222, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_223(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(223, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_224(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(224, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_225(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(225, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_226(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(226, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_227(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(227, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_228(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(228, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_229(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(229, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_230(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(230, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_231(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(231, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_232(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(232, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_233(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(233, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_234(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(234, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_235(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(235, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_236(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(236, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_237(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(237, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_238(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(238, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_239(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(239, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_240(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(240, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_241(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(241, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_242(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(242, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_243(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(243, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_244(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(244, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_245(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(245, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_246(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(246, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_247(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(247, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_248(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(248, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_249(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(249, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_250(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(250, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_251(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(251, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_252(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(252, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_253(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(253, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_254(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(254, recv, w0, w1, w2)
}

//go:noinline
func stubWppp_ppp_255(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWppp_ppp(255, recv, w0, w1, w2)
}

var stubsWppp_ppp [poolSizeWppp_ppp]uintptr

func dispatchWppp_ppp(slot uint32, recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	var pw [3]unsafe.Pointer
	var sw [0]uint64
	var fw [0]float64
	pw[0] = w0
	pw[1] = w1
	pw[2] = w2
	var rpw [3]unsafe.Pointer
	var rsw [0]uint64
	var rfw [0]float64
	if core := slotPoolWppp_ppp[slot]; core != nil {
		core(recv, pw[:], sw[:], fw[:], rpw[:], rsw[:], rfw[:])
	}
	return rpw[0], rpw[1], rpw[2]
}

func init() {
	stubsWppp_ppp[0] = runtype.FuncPC(stubWppp_ppp_0)
	stubsWppp_ppp[1] = runtype.FuncPC(stubWppp_ppp_1)
	stubsWppp_ppp[2] = runtype.FuncPC(stubWppp_ppp_2)
	stubsWppp_ppp[3] = runtype.FuncPC(stubWppp_ppp_3)
	stubsWppp_ppp[4] = runtype.FuncPC(stubWppp_ppp_4)
	stubsWppp_ppp[5] = runtype.FuncPC(stubWppp_ppp_5)
	stubsWppp_ppp[6] = runtype.FuncPC(stubWppp_ppp_6)
	stubsWppp_ppp[7] = runtype.FuncPC(stubWppp_ppp_7)
	stubsWppp_ppp[8] = runtype.FuncPC(stubWppp_ppp_8)
	stubsWppp_ppp[9] = runtype.FuncPC(stubWppp_ppp_9)
	stubsWppp_ppp[10] = runtype.FuncPC(stubWppp_ppp_10)
	stubsWppp_ppp[11] = runtype.FuncPC(stubWppp_ppp_11)
	stubsWppp_ppp[12] = runtype.FuncPC(stubWppp_ppp_12)
	stubsWppp_ppp[13] = runtype.FuncPC(stubWppp_ppp_13)
	stubsWppp_ppp[14] = runtype.FuncPC(stubWppp_ppp_14)
	stubsWppp_ppp[15] = runtype.FuncPC(stubWppp_ppp_15)
	stubsWppp_ppp[16] = runtype.FuncPC(stubWppp_ppp_16)
	stubsWppp_ppp[17] = runtype.FuncPC(stubWppp_ppp_17)
	stubsWppp_ppp[18] = runtype.FuncPC(stubWppp_ppp_18)
	stubsWppp_ppp[19] = runtype.FuncPC(stubWppp_ppp_19)
	stubsWppp_ppp[20] = runtype.FuncPC(stubWppp_ppp_20)
	stubsWppp_ppp[21] = runtype.FuncPC(stubWppp_ppp_21)
	stubsWppp_ppp[22] = runtype.FuncPC(stubWppp_ppp_22)
	stubsWppp_ppp[23] = runtype.FuncPC(stubWppp_ppp_23)
	stubsWppp_ppp[24] = runtype.FuncPC(stubWppp_ppp_24)
	stubsWppp_ppp[25] = runtype.FuncPC(stubWppp_ppp_25)
	stubsWppp_ppp[26] = runtype.FuncPC(stubWppp_ppp_26)
	stubsWppp_ppp[27] = runtype.FuncPC(stubWppp_ppp_27)
	stubsWppp_ppp[28] = runtype.FuncPC(stubWppp_ppp_28)
	stubsWppp_ppp[29] = runtype.FuncPC(stubWppp_ppp_29)
	stubsWppp_ppp[30] = runtype.FuncPC(stubWppp_ppp_30)
	stubsWppp_ppp[31] = runtype.FuncPC(stubWppp_ppp_31)
	stubsWppp_ppp[32] = runtype.FuncPC(stubWppp_ppp_32)
	stubsWppp_ppp[33] = runtype.FuncPC(stubWppp_ppp_33)
	stubsWppp_ppp[34] = runtype.FuncPC(stubWppp_ppp_34)
	stubsWppp_ppp[35] = runtype.FuncPC(stubWppp_ppp_35)
	stubsWppp_ppp[36] = runtype.FuncPC(stubWppp_ppp_36)
	stubsWppp_ppp[37] = runtype.FuncPC(stubWppp_ppp_37)
	stubsWppp_ppp[38] = runtype.FuncPC(stubWppp_ppp_38)
	stubsWppp_ppp[39] = runtype.FuncPC(stubWppp_ppp_39)
	stubsWppp_ppp[40] = runtype.FuncPC(stubWppp_ppp_40)
	stubsWppp_ppp[41] = runtype.FuncPC(stubWppp_ppp_41)
	stubsWppp_ppp[42] = runtype.FuncPC(stubWppp_ppp_42)
	stubsWppp_ppp[43] = runtype.FuncPC(stubWppp_ppp_43)
	stubsWppp_ppp[44] = runtype.FuncPC(stubWppp_ppp_44)
	stubsWppp_ppp[45] = runtype.FuncPC(stubWppp_ppp_45)
	stubsWppp_ppp[46] = runtype.FuncPC(stubWppp_ppp_46)
	stubsWppp_ppp[47] = runtype.FuncPC(stubWppp_ppp_47)
	stubsWppp_ppp[48] = runtype.FuncPC(stubWppp_ppp_48)
	stubsWppp_ppp[49] = runtype.FuncPC(stubWppp_ppp_49)
	stubsWppp_ppp[50] = runtype.FuncPC(stubWppp_ppp_50)
	stubsWppp_ppp[51] = runtype.FuncPC(stubWppp_ppp_51)
	stubsWppp_ppp[52] = runtype.FuncPC(stubWppp_ppp_52)
	stubsWppp_ppp[53] = runtype.FuncPC(stubWppp_ppp_53)
	stubsWppp_ppp[54] = runtype.FuncPC(stubWppp_ppp_54)
	stubsWppp_ppp[55] = runtype.FuncPC(stubWppp_ppp_55)
	stubsWppp_ppp[56] = runtype.FuncPC(stubWppp_ppp_56)
	stubsWppp_ppp[57] = runtype.FuncPC(stubWppp_ppp_57)
	stubsWppp_ppp[58] = runtype.FuncPC(stubWppp_ppp_58)
	stubsWppp_ppp[59] = runtype.FuncPC(stubWppp_ppp_59)
	stubsWppp_ppp[60] = runtype.FuncPC(stubWppp_ppp_60)
	stubsWppp_ppp[61] = runtype.FuncPC(stubWppp_ppp_61)
	stubsWppp_ppp[62] = runtype.FuncPC(stubWppp_ppp_62)
	stubsWppp_ppp[63] = runtype.FuncPC(stubWppp_ppp_63)
	stubsWppp_ppp[64] = runtype.FuncPC(stubWppp_ppp_64)
	stubsWppp_ppp[65] = runtype.FuncPC(stubWppp_ppp_65)
	stubsWppp_ppp[66] = runtype.FuncPC(stubWppp_ppp_66)
	stubsWppp_ppp[67] = runtype.FuncPC(stubWppp_ppp_67)
	stubsWppp_ppp[68] = runtype.FuncPC(stubWppp_ppp_68)
	stubsWppp_ppp[69] = runtype.FuncPC(stubWppp_ppp_69)
	stubsWppp_ppp[70] = runtype.FuncPC(stubWppp_ppp_70)
	stubsWppp_ppp[71] = runtype.FuncPC(stubWppp_ppp_71)
	stubsWppp_ppp[72] = runtype.FuncPC(stubWppp_ppp_72)
	stubsWppp_ppp[73] = runtype.FuncPC(stubWppp_ppp_73)
	stubsWppp_ppp[74] = runtype.FuncPC(stubWppp_ppp_74)
	stubsWppp_ppp[75] = runtype.FuncPC(stubWppp_ppp_75)
	stubsWppp_ppp[76] = runtype.FuncPC(stubWppp_ppp_76)
	stubsWppp_ppp[77] = runtype.FuncPC(stubWppp_ppp_77)
	stubsWppp_ppp[78] = runtype.FuncPC(stubWppp_ppp_78)
	stubsWppp_ppp[79] = runtype.FuncPC(stubWppp_ppp_79)
	stubsWppp_ppp[80] = runtype.FuncPC(stubWppp_ppp_80)
	stubsWppp_ppp[81] = runtype.FuncPC(stubWppp_ppp_81)
	stubsWppp_ppp[82] = runtype.FuncPC(stubWppp_ppp_82)
	stubsWppp_ppp[83] = runtype.FuncPC(stubWppp_ppp_83)
	stubsWppp_ppp[84] = runtype.FuncPC(stubWppp_ppp_84)
	stubsWppp_ppp[85] = runtype.FuncPC(stubWppp_ppp_85)
	stubsWppp_ppp[86] = runtype.FuncPC(stubWppp_ppp_86)
	stubsWppp_ppp[87] = runtype.FuncPC(stubWppp_ppp_87)
	stubsWppp_ppp[88] = runtype.FuncPC(stubWppp_ppp_88)
	stubsWppp_ppp[89] = runtype.FuncPC(stubWppp_ppp_89)
	stubsWppp_ppp[90] = runtype.FuncPC(stubWppp_ppp_90)
	stubsWppp_ppp[91] = runtype.FuncPC(stubWppp_ppp_91)
	stubsWppp_ppp[92] = runtype.FuncPC(stubWppp_ppp_92)
	stubsWppp_ppp[93] = runtype.FuncPC(stubWppp_ppp_93)
	stubsWppp_ppp[94] = runtype.FuncPC(stubWppp_ppp_94)
	stubsWppp_ppp[95] = runtype.FuncPC(stubWppp_ppp_95)
	stubsWppp_ppp[96] = runtype.FuncPC(stubWppp_ppp_96)
	stubsWppp_ppp[97] = runtype.FuncPC(stubWppp_ppp_97)
	stubsWppp_ppp[98] = runtype.FuncPC(stubWppp_ppp_98)
	stubsWppp_ppp[99] = runtype.FuncPC(stubWppp_ppp_99)
	stubsWppp_ppp[100] = runtype.FuncPC(stubWppp_ppp_100)
	stubsWppp_ppp[101] = runtype.FuncPC(stubWppp_ppp_101)
	stubsWppp_ppp[102] = runtype.FuncPC(stubWppp_ppp_102)
	stubsWppp_ppp[103] = runtype.FuncPC(stubWppp_ppp_103)
	stubsWppp_ppp[104] = runtype.FuncPC(stubWppp_ppp_104)
	stubsWppp_ppp[105] = runtype.FuncPC(stubWppp_ppp_105)
	stubsWppp_ppp[106] = runtype.FuncPC(stubWppp_ppp_106)
	stubsWppp_ppp[107] = runtype.FuncPC(stubWppp_ppp_107)
	stubsWppp_ppp[108] = runtype.FuncPC(stubWppp_ppp_108)
	stubsWppp_ppp[109] = runtype.FuncPC(stubWppp_ppp_109)
	stubsWppp_ppp[110] = runtype.FuncPC(stubWppp_ppp_110)
	stubsWppp_ppp[111] = runtype.FuncPC(stubWppp_ppp_111)
	stubsWppp_ppp[112] = runtype.FuncPC(stubWppp_ppp_112)
	stubsWppp_ppp[113] = runtype.FuncPC(stubWppp_ppp_113)
	stubsWppp_ppp[114] = runtype.FuncPC(stubWppp_ppp_114)
	stubsWppp_ppp[115] = runtype.FuncPC(stubWppp_ppp_115)
	stubsWppp_ppp[116] = runtype.FuncPC(stubWppp_ppp_116)
	stubsWppp_ppp[117] = runtype.FuncPC(stubWppp_ppp_117)
	stubsWppp_ppp[118] = runtype.FuncPC(stubWppp_ppp_118)
	stubsWppp_ppp[119] = runtype.FuncPC(stubWppp_ppp_119)
	stubsWppp_ppp[120] = runtype.FuncPC(stubWppp_ppp_120)
	stubsWppp_ppp[121] = runtype.FuncPC(stubWppp_ppp_121)
	stubsWppp_ppp[122] = runtype.FuncPC(stubWppp_ppp_122)
	stubsWppp_ppp[123] = runtype.FuncPC(stubWppp_ppp_123)
	stubsWppp_ppp[124] = runtype.FuncPC(stubWppp_ppp_124)
	stubsWppp_ppp[125] = runtype.FuncPC(stubWppp_ppp_125)
	stubsWppp_ppp[126] = runtype.FuncPC(stubWppp_ppp_126)
	stubsWppp_ppp[127] = runtype.FuncPC(stubWppp_ppp_127)
	stubsWppp_ppp[128] = runtype.FuncPC(stubWppp_ppp_128)
	stubsWppp_ppp[129] = runtype.FuncPC(stubWppp_ppp_129)
	stubsWppp_ppp[130] = runtype.FuncPC(stubWppp_ppp_130)
	stubsWppp_ppp[131] = runtype.FuncPC(stubWppp_ppp_131)
	stubsWppp_ppp[132] = runtype.FuncPC(stubWppp_ppp_132)
	stubsWppp_ppp[133] = runtype.FuncPC(stubWppp_ppp_133)
	stubsWppp_ppp[134] = runtype.FuncPC(stubWppp_ppp_134)
	stubsWppp_ppp[135] = runtype.FuncPC(stubWppp_ppp_135)
	stubsWppp_ppp[136] = runtype.FuncPC(stubWppp_ppp_136)
	stubsWppp_ppp[137] = runtype.FuncPC(stubWppp_ppp_137)
	stubsWppp_ppp[138] = runtype.FuncPC(stubWppp_ppp_138)
	stubsWppp_ppp[139] = runtype.FuncPC(stubWppp_ppp_139)
	stubsWppp_ppp[140] = runtype.FuncPC(stubWppp_ppp_140)
	stubsWppp_ppp[141] = runtype.FuncPC(stubWppp_ppp_141)
	stubsWppp_ppp[142] = runtype.FuncPC(stubWppp_ppp_142)
	stubsWppp_ppp[143] = runtype.FuncPC(stubWppp_ppp_143)
	stubsWppp_ppp[144] = runtype.FuncPC(stubWppp_ppp_144)
	stubsWppp_ppp[145] = runtype.FuncPC(stubWppp_ppp_145)
	stubsWppp_ppp[146] = runtype.FuncPC(stubWppp_ppp_146)
	stubsWppp_ppp[147] = runtype.FuncPC(stubWppp_ppp_147)
	stubsWppp_ppp[148] = runtype.FuncPC(stubWppp_ppp_148)
	stubsWppp_ppp[149] = runtype.FuncPC(stubWppp_ppp_149)
	stubsWppp_ppp[150] = runtype.FuncPC(stubWppp_ppp_150)
	stubsWppp_ppp[151] = runtype.FuncPC(stubWppp_ppp_151)
	stubsWppp_ppp[152] = runtype.FuncPC(stubWppp_ppp_152)
	stubsWppp_ppp[153] = runtype.FuncPC(stubWppp_ppp_153)
	stubsWppp_ppp[154] = runtype.FuncPC(stubWppp_ppp_154)
	stubsWppp_ppp[155] = runtype.FuncPC(stubWppp_ppp_155)
	stubsWppp_ppp[156] = runtype.FuncPC(stubWppp_ppp_156)
	stubsWppp_ppp[157] = runtype.FuncPC(stubWppp_ppp_157)
	stubsWppp_ppp[158] = runtype.FuncPC(stubWppp_ppp_158)
	stubsWppp_ppp[159] = runtype.FuncPC(stubWppp_ppp_159)
	stubsWppp_ppp[160] = runtype.FuncPC(stubWppp_ppp_160)
	stubsWppp_ppp[161] = runtype.FuncPC(stubWppp_ppp_161)
	stubsWppp_ppp[162] = runtype.FuncPC(stubWppp_ppp_162)
	stubsWppp_ppp[163] = runtype.FuncPC(stubWppp_ppp_163)
	stubsWppp_ppp[164] = runtype.FuncPC(stubWppp_ppp_164)
	stubsWppp_ppp[165] = runtype.FuncPC(stubWppp_ppp_165)
	stubsWppp_ppp[166] = runtype.FuncPC(stubWppp_ppp_166)
	stubsWppp_ppp[167] = runtype.FuncPC(stubWppp_ppp_167)
	stubsWppp_ppp[168] = runtype.FuncPC(stubWppp_ppp_168)
	stubsWppp_ppp[169] = runtype.FuncPC(stubWppp_ppp_169)
	stubsWppp_ppp[170] = runtype.FuncPC(stubWppp_ppp_170)
	stubsWppp_ppp[171] = runtype.FuncPC(stubWppp_ppp_171)
	stubsWppp_ppp[172] = runtype.FuncPC(stubWppp_ppp_172)
	stubsWppp_ppp[173] = runtype.FuncPC(stubWppp_ppp_173)
	stubsWppp_ppp[174] = runtype.FuncPC(stubWppp_ppp_174)
	stubsWppp_ppp[175] = runtype.FuncPC(stubWppp_ppp_175)
	stubsWppp_ppp[176] = runtype.FuncPC(stubWppp_ppp_176)
	stubsWppp_ppp[177] = runtype.FuncPC(stubWppp_ppp_177)
	stubsWppp_ppp[178] = runtype.FuncPC(stubWppp_ppp_178)
	stubsWppp_ppp[179] = runtype.FuncPC(stubWppp_ppp_179)
	stubsWppp_ppp[180] = runtype.FuncPC(stubWppp_ppp_180)
	stubsWppp_ppp[181] = runtype.FuncPC(stubWppp_ppp_181)
	stubsWppp_ppp[182] = runtype.FuncPC(stubWppp_ppp_182)
	stubsWppp_ppp[183] = runtype.FuncPC(stubWppp_ppp_183)
	stubsWppp_ppp[184] = runtype.FuncPC(stubWppp_ppp_184)
	stubsWppp_ppp[185] = runtype.FuncPC(stubWppp_ppp_185)
	stubsWppp_ppp[186] = runtype.FuncPC(stubWppp_ppp_186)
	stubsWppp_ppp[187] = runtype.FuncPC(stubWppp_ppp_187)
	stubsWppp_ppp[188] = runtype.FuncPC(stubWppp_ppp_188)
	stubsWppp_ppp[189] = runtype.FuncPC(stubWppp_ppp_189)
	stubsWppp_ppp[190] = runtype.FuncPC(stubWppp_ppp_190)
	stubsWppp_ppp[191] = runtype.FuncPC(stubWppp_ppp_191)
	stubsWppp_ppp[192] = runtype.FuncPC(stubWppp_ppp_192)
	stubsWppp_ppp[193] = runtype.FuncPC(stubWppp_ppp_193)
	stubsWppp_ppp[194] = runtype.FuncPC(stubWppp_ppp_194)
	stubsWppp_ppp[195] = runtype.FuncPC(stubWppp_ppp_195)
	stubsWppp_ppp[196] = runtype.FuncPC(stubWppp_ppp_196)
	stubsWppp_ppp[197] = runtype.FuncPC(stubWppp_ppp_197)
	stubsWppp_ppp[198] = runtype.FuncPC(stubWppp_ppp_198)
	stubsWppp_ppp[199] = runtype.FuncPC(stubWppp_ppp_199)
	stubsWppp_ppp[200] = runtype.FuncPC(stubWppp_ppp_200)
	stubsWppp_ppp[201] = runtype.FuncPC(stubWppp_ppp_201)
	stubsWppp_ppp[202] = runtype.FuncPC(stubWppp_ppp_202)
	stubsWppp_ppp[203] = runtype.FuncPC(stubWppp_ppp_203)
	stubsWppp_ppp[204] = runtype.FuncPC(stubWppp_ppp_204)
	stubsWppp_ppp[205] = runtype.FuncPC(stubWppp_ppp_205)
	stubsWppp_ppp[206] = runtype.FuncPC(stubWppp_ppp_206)
	stubsWppp_ppp[207] = runtype.FuncPC(stubWppp_ppp_207)
	stubsWppp_ppp[208] = runtype.FuncPC(stubWppp_ppp_208)
	stubsWppp_ppp[209] = runtype.FuncPC(stubWppp_ppp_209)
	stubsWppp_ppp[210] = runtype.FuncPC(stubWppp_ppp_210)
	stubsWppp_ppp[211] = runtype.FuncPC(stubWppp_ppp_211)
	stubsWppp_ppp[212] = runtype.FuncPC(stubWppp_ppp_212)
	stubsWppp_ppp[213] = runtype.FuncPC(stubWppp_ppp_213)
	stubsWppp_ppp[214] = runtype.FuncPC(stubWppp_ppp_214)
	stubsWppp_ppp[215] = runtype.FuncPC(stubWppp_ppp_215)
	stubsWppp_ppp[216] = runtype.FuncPC(stubWppp_ppp_216)
	stubsWppp_ppp[217] = runtype.FuncPC(stubWppp_ppp_217)
	stubsWppp_ppp[218] = runtype.FuncPC(stubWppp_ppp_218)
	stubsWppp_ppp[219] = runtype.FuncPC(stubWppp_ppp_219)
	stubsWppp_ppp[220] = runtype.FuncPC(stubWppp_ppp_220)
	stubsWppp_ppp[221] = runtype.FuncPC(stubWppp_ppp_221)
	stubsWppp_ppp[222] = runtype.FuncPC(stubWppp_ppp_222)
	stubsWppp_ppp[223] = runtype.FuncPC(stubWppp_ppp_223)
	stubsWppp_ppp[224] = runtype.FuncPC(stubWppp_ppp_224)
	stubsWppp_ppp[225] = runtype.FuncPC(stubWppp_ppp_225)
	stubsWppp_ppp[226] = runtype.FuncPC(stubWppp_ppp_226)
	stubsWppp_ppp[227] = runtype.FuncPC(stubWppp_ppp_227)
	stubsWppp_ppp[228] = runtype.FuncPC(stubWppp_ppp_228)
	stubsWppp_ppp[229] = runtype.FuncPC(stubWppp_ppp_229)
	stubsWppp_ppp[230] = runtype.FuncPC(stubWppp_ppp_230)
	stubsWppp_ppp[231] = runtype.FuncPC(stubWppp_ppp_231)
	stubsWppp_ppp[232] = runtype.FuncPC(stubWppp_ppp_232)
	stubsWppp_ppp[233] = runtype.FuncPC(stubWppp_ppp_233)
	stubsWppp_ppp[234] = runtype.FuncPC(stubWppp_ppp_234)
	stubsWppp_ppp[235] = runtype.FuncPC(stubWppp_ppp_235)
	stubsWppp_ppp[236] = runtype.FuncPC(stubWppp_ppp_236)
	stubsWppp_ppp[237] = runtype.FuncPC(stubWppp_ppp_237)
	stubsWppp_ppp[238] = runtype.FuncPC(stubWppp_ppp_238)
	stubsWppp_ppp[239] = runtype.FuncPC(stubWppp_ppp_239)
	stubsWppp_ppp[240] = runtype.FuncPC(stubWppp_ppp_240)
	stubsWppp_ppp[241] = runtype.FuncPC(stubWppp_ppp_241)
	stubsWppp_ppp[242] = runtype.FuncPC(stubWppp_ppp_242)
	stubsWppp_ppp[243] = runtype.FuncPC(stubWppp_ppp_243)
	stubsWppp_ppp[244] = runtype.FuncPC(stubWppp_ppp_244)
	stubsWppp_ppp[245] = runtype.FuncPC(stubWppp_ppp_245)
	stubsWppp_ppp[246] = runtype.FuncPC(stubWppp_ppp_246)
	stubsWppp_ppp[247] = runtype.FuncPC(stubWppp_ppp_247)
	stubsWppp_ppp[248] = runtype.FuncPC(stubWppp_ppp_248)
	stubsWppp_ppp[249] = runtype.FuncPC(stubWppp_ppp_249)
	stubsWppp_ppp[250] = runtype.FuncPC(stubWppp_ppp_250)
	stubsWppp_ppp[251] = runtype.FuncPC(stubWppp_ppp_251)
	stubsWppp_ppp[252] = runtype.FuncPC(stubWppp_ppp_252)
	stubsWppp_ppp[253] = runtype.FuncPC(stubWppp_ppp_253)
	stubsWppp_ppp[254] = runtype.FuncPC(stubWppp_ppp_254)
	stubsWppp_ppp[255] = runtype.FuncPC(stubWppp_ppp_255)
	registerWordPool("ppp_ppp", &wordPool{
		next:  &nextSlotWppp_ppp,
		cap:   poolSizeWppp_ppp,
		stubs: stubsWppp_ppp[:],
		slots: slotPoolWppp_ppp[:],
		name:  "Wppp_ppp",
	})
}
