// Code generated by gen_pools.go; DO NOT EDIT.
// Word-shape pipii_pppp pool: 256 slots (128 on wasm).

package stubs

import (
	"sync/atomic"
	"unsafe"

	"github.com/mvm-sh/mvm/runtype"
)

var (
	slotPoolWpipii_pppp [poolSizeWpipii_pppp]CoreFunc
	nextSlotWpipii_pppp atomic.Uint32
)

//go:noinline
func stubWpipii_pppp_0(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(0, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_1(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(1, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_2(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(2, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_3(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(3, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_4(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(4, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_5(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(5, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_6(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(6, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_7(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(7, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_8(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(8, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_9(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(9, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_10(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(10, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_11(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(11, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_12(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(12, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_13(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(13, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_14(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(14, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_15(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(15, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_16(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(16, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_17(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(17, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_18(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(18, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_19(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(19, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_20(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(20, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_21(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(21, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_22(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(22, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_23(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(23, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_24(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(24, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_25(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(25, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_26(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(26, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_27(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(27, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_28(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(28, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_29(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(29, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_30(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(30, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_31(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(31, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_32(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(32, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_33(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(33, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_34(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(34, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_35(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(35, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_36(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(36, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_37(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(37, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_38(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(38, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_39(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(39, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_40(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(40, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_41(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(41, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_42(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(42, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_43(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(43, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_44(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(44, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_45(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(45, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_46(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(46, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_47(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(47, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_48(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(48, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_49(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(49, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_50(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(50, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_51(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(51, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_52(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(52, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_53(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(53, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_54(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(54, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_55(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(55, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_56(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(56, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_57(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(57, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_58(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(58, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_59(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(59, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_60(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(60, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_61(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(61, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_62(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(62, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_63(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(63, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_64(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(64, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_65(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(65, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_66(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(66, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_67(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(67, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_68(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(68, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_69(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(69, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_70(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(70, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_71(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(71, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_72(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(72, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_73(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(73, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_74(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(74, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_75(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(75, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_76(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(76, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_77(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(77, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_78(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(78, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_79(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(79, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_80(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(80, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_81(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(81, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_82(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(82, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_83(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(83, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_84(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(84, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_85(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(85, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_86(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(86, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_87(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(87, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_88(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(88, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_89(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(89, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_90(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(90, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_91(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(91, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_92(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(92, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_93(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(93, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_94(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(94, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_95(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(95, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_96(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(96, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_97(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(97, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_98(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(98, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_99(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(99, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_100(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(100, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_101(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(101, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_102(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(102, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_103(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(103, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_104(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(104, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_105(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(105, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_106(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(106, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_107(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(107, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_108(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(108, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_109(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(109, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_110(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(110, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_111(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(111, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_112(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(112, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_113(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(113, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_114(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(114, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_115(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(115, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_116(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(116, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_117(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(117, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_118(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(118, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_119(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(119, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_120(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(120, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_121(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(121, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_122(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(122, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_123(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(123, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_124(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(124, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_125(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(125, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_126(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(126, recv, w0, w1, w2, w3, w4)
}

//go:noinline
func stubWpipii_pppp_127(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpipii_pppp(127, recv, w0, w1, w2, w3, w4)
}

var stubsWpipii_pppp [poolSizeWpipii_pppp]uintptr

func dispatchWpipii_pppp(slot uint32, recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 unsafe.Pointer, w3 uint64, w4 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	var pw [2]unsafe.Pointer
	var sw [3]uint64
	var fw [0]float64
	pw[0] = w0
	sw[0] = w1
	pw[1] = w2
	sw[1] = w3
	sw[2] = w4
	var rpw [4]unsafe.Pointer
	var rsw [0]uint64
	var rfw [0]float64
	if core := slotPoolWpipii_pppp[slot]; core != nil {
		core(recv, pw[:], sw[:], fw[:], rpw[:], rsw[:], rfw[:])
	}
	return rpw[0], rpw[1], rpw[2], rpw[3]
}

func init() {
	stubsWpipii_pppp[0] = runtype.FuncPC(stubWpipii_pppp_0)
	stubsWpipii_pppp[1] = runtype.FuncPC(stubWpipii_pppp_1)
	stubsWpipii_pppp[2] = runtype.FuncPC(stubWpipii_pppp_2)
	stubsWpipii_pppp[3] = runtype.FuncPC(stubWpipii_pppp_3)
	stubsWpipii_pppp[4] = runtype.FuncPC(stubWpipii_pppp_4)
	stubsWpipii_pppp[5] = runtype.FuncPC(stubWpipii_pppp_5)
	stubsWpipii_pppp[6] = runtype.FuncPC(stubWpipii_pppp_6)
	stubsWpipii_pppp[7] = runtype.FuncPC(stubWpipii_pppp_7)
	stubsWpipii_pppp[8] = runtype.FuncPC(stubWpipii_pppp_8)
	stubsWpipii_pppp[9] = runtype.FuncPC(stubWpipii_pppp_9)
	stubsWpipii_pppp[10] = runtype.FuncPC(stubWpipii_pppp_10)
	stubsWpipii_pppp[11] = runtype.FuncPC(stubWpipii_pppp_11)
	stubsWpipii_pppp[12] = runtype.FuncPC(stubWpipii_pppp_12)
	stubsWpipii_pppp[13] = runtype.FuncPC(stubWpipii_pppp_13)
	stubsWpipii_pppp[14] = runtype.FuncPC(stubWpipii_pppp_14)
	stubsWpipii_pppp[15] = runtype.FuncPC(stubWpipii_pppp_15)
	stubsWpipii_pppp[16] = runtype.FuncPC(stubWpipii_pppp_16)
	stubsWpipii_pppp[17] = runtype.FuncPC(stubWpipii_pppp_17)
	stubsWpipii_pppp[18] = runtype.FuncPC(stubWpipii_pppp_18)
	stubsWpipii_pppp[19] = runtype.FuncPC(stubWpipii_pppp_19)
	stubsWpipii_pppp[20] = runtype.FuncPC(stubWpipii_pppp_20)
	stubsWpipii_pppp[21] = runtype.FuncPC(stubWpipii_pppp_21)
	stubsWpipii_pppp[22] = runtype.FuncPC(stubWpipii_pppp_22)
	stubsWpipii_pppp[23] = runtype.FuncPC(stubWpipii_pppp_23)
	stubsWpipii_pppp[24] = runtype.FuncPC(stubWpipii_pppp_24)
	stubsWpipii_pppp[25] = runtype.FuncPC(stubWpipii_pppp_25)
	stubsWpipii_pppp[26] = runtype.FuncPC(stubWpipii_pppp_26)
	stubsWpipii_pppp[27] = runtype.FuncPC(stubWpipii_pppp_27)
	stubsWpipii_pppp[28] = runtype.FuncPC(stubWpipii_pppp_28)
	stubsWpipii_pppp[29] = runtype.FuncPC(stubWpipii_pppp_29)
	stubsWpipii_pppp[30] = runtype.FuncPC(stubWpipii_pppp_30)
	stubsWpipii_pppp[31] = runtype.FuncPC(stubWpipii_pppp_31)
	stubsWpipii_pppp[32] = runtype.FuncPC(stubWpipii_pppp_32)
	stubsWpipii_pppp[33] = runtype.FuncPC(stubWpipii_pppp_33)
	stubsWpipii_pppp[34] = runtype.FuncPC(stubWpipii_pppp_34)
	stubsWpipii_pppp[35] = runtype.FuncPC(stubWpipii_pppp_35)
	stubsWpipii_pppp[36] = runtype.FuncPC(stubWpipii_pppp_36)
	stubsWpipii_pppp[37] = runtype.FuncPC(stubWpipii_pppp_37)
	stubsWpipii_pppp[38] = runtype.FuncPC(stubWpipii_pppp_38)
	stubsWpipii_pppp[39] = runtype.FuncPC(stubWpipii_pppp_39)
	stubsWpipii_pppp[40] = runtype.FuncPC(stubWpipii_pppp_40)
	stubsWpipii_pppp[41] = runtype.FuncPC(stubWpipii_pppp_41)
	stubsWpipii_pppp[42] = runtype.FuncPC(stubWpipii_pppp_42)
	stubsWpipii_pppp[43] = runtype.FuncPC(stubWpipii_pppp_43)
	stubsWpipii_pppp[44] = runtype.FuncPC(stubWpipii_pppp_44)
	stubsWpipii_pppp[45] = runtype.FuncPC(stubWpipii_pppp_45)
	stubsWpipii_pppp[46] = runtype.FuncPC(stubWpipii_pppp_46)
	stubsWpipii_pppp[47] = runtype.FuncPC(stubWpipii_pppp_47)
	stubsWpipii_pppp[48] = runtype.FuncPC(stubWpipii_pppp_48)
	stubsWpipii_pppp[49] = runtype.FuncPC(stubWpipii_pppp_49)
	stubsWpipii_pppp[50] = runtype.FuncPC(stubWpipii_pppp_50)
	stubsWpipii_pppp[51] = runtype.FuncPC(stubWpipii_pppp_51)
	stubsWpipii_pppp[52] = runtype.FuncPC(stubWpipii_pppp_52)
	stubsWpipii_pppp[53] = runtype.FuncPC(stubWpipii_pppp_53)
	stubsWpipii_pppp[54] = runtype.FuncPC(stubWpipii_pppp_54)
	stubsWpipii_pppp[55] = runtype.FuncPC(stubWpipii_pppp_55)
	stubsWpipii_pppp[56] = runtype.FuncPC(stubWpipii_pppp_56)
	stubsWpipii_pppp[57] = runtype.FuncPC(stubWpipii_pppp_57)
	stubsWpipii_pppp[58] = runtype.FuncPC(stubWpipii_pppp_58)
	stubsWpipii_pppp[59] = runtype.FuncPC(stubWpipii_pppp_59)
	stubsWpipii_pppp[60] = runtype.FuncPC(stubWpipii_pppp_60)
	stubsWpipii_pppp[61] = runtype.FuncPC(stubWpipii_pppp_61)
	stubsWpipii_pppp[62] = runtype.FuncPC(stubWpipii_pppp_62)
	stubsWpipii_pppp[63] = runtype.FuncPC(stubWpipii_pppp_63)
	stubsWpipii_pppp[64] = runtype.FuncPC(stubWpipii_pppp_64)
	stubsWpipii_pppp[65] = runtype.FuncPC(stubWpipii_pppp_65)
	stubsWpipii_pppp[66] = runtype.FuncPC(stubWpipii_pppp_66)
	stubsWpipii_pppp[67] = runtype.FuncPC(stubWpipii_pppp_67)
	stubsWpipii_pppp[68] = runtype.FuncPC(stubWpipii_pppp_68)
	stubsWpipii_pppp[69] = runtype.FuncPC(stubWpipii_pppp_69)
	stubsWpipii_pppp[70] = runtype.FuncPC(stubWpipii_pppp_70)
	stubsWpipii_pppp[71] = runtype.FuncPC(stubWpipii_pppp_71)
	stubsWpipii_pppp[72] = runtype.FuncPC(stubWpipii_pppp_72)
	stubsWpipii_pppp[73] = runtype.FuncPC(stubWpipii_pppp_73)
	stubsWpipii_pppp[74] = runtype.FuncPC(stubWpipii_pppp_74)
	stubsWpipii_pppp[75] = runtype.FuncPC(stubWpipii_pppp_75)
	stubsWpipii_pppp[76] = runtype.FuncPC(stubWpipii_pppp_76)
	stubsWpipii_pppp[77] = runtype.FuncPC(stubWpipii_pppp_77)
	stubsWpipii_pppp[78] = runtype.FuncPC(stubWpipii_pppp_78)
	stubsWpipii_pppp[79] = runtype.FuncPC(stubWpipii_pppp_79)
	stubsWpipii_pppp[80] = runtype.FuncPC(stubWpipii_pppp_80)
	stubsWpipii_pppp[81] = runtype.FuncPC(stubWpipii_pppp_81)
	stubsWpipii_pppp[82] = runtype.FuncPC(stubWpipii_pppp_82)
	stubsWpipii_pppp[83] = runtype.FuncPC(stubWpipii_pppp_83)
	stubsWpipii_pppp[84] = runtype.FuncPC(stubWpipii_pppp_84)
	stubsWpipii_pppp[85] = runtype.FuncPC(stubWpipii_pppp_85)
	stubsWpipii_pppp[86] = runtype.FuncPC(stubWpipii_pppp_86)
	stubsWpipii_pppp[87] = runtype.FuncPC(stubWpipii_pppp_87)
	stubsWpipii_pppp[88] = runtype.FuncPC(stubWpipii_pppp_88)
	stubsWpipii_pppp[89] = runtype.FuncPC(stubWpipii_pppp_89)
	stubsWpipii_pppp[90] = runtype.FuncPC(stubWpipii_pppp_90)
	stubsWpipii_pppp[91] = runtype.FuncPC(stubWpipii_pppp_91)
	stubsWpipii_pppp[92] = runtype.FuncPC(stubWpipii_pppp_92)
	stubsWpipii_pppp[93] = runtype.FuncPC(stubWpipii_pppp_93)
	stubsWpipii_pppp[94] = runtype.FuncPC(stubWpipii_pppp_94)
	stubsWpipii_pppp[95] = runtype.FuncPC(stubWpipii_pppp_95)
	stubsWpipii_pppp[96] = runtype.FuncPC(stubWpipii_pppp_96)
	stubsWpipii_pppp[97] = runtype.FuncPC(stubWpipii_pppp_97)
	stubsWpipii_pppp[98] = runtype.FuncPC(stubWpipii_pppp_98)
	stubsWpipii_pppp[99] = runtype.FuncPC(stubWpipii_pppp_99)
	stubsWpipii_pppp[100] = runtype.FuncPC(stubWpipii_pppp_100)
	stubsWpipii_pppp[101] = runtype.FuncPC(stubWpipii_pppp_101)
	stubsWpipii_pppp[102] = runtype.FuncPC(stubWpipii_pppp_102)
	stubsWpipii_pppp[103] = runtype.FuncPC(stubWpipii_pppp_103)
	stubsWpipii_pppp[104] = runtype.FuncPC(stubWpipii_pppp_104)
	stubsWpipii_pppp[105] = runtype.FuncPC(stubWpipii_pppp_105)
	stubsWpipii_pppp[106] = runtype.FuncPC(stubWpipii_pppp_106)
	stubsWpipii_pppp[107] = runtype.FuncPC(stubWpipii_pppp_107)
	stubsWpipii_pppp[108] = runtype.FuncPC(stubWpipii_pppp_108)
	stubsWpipii_pppp[109] = runtype.FuncPC(stubWpipii_pppp_109)
	stubsWpipii_pppp[110] = runtype.FuncPC(stubWpipii_pppp_110)
	stubsWpipii_pppp[111] = runtype.FuncPC(stubWpipii_pppp_111)
	stubsWpipii_pppp[112] = runtype.FuncPC(stubWpipii_pppp_112)
	stubsWpipii_pppp[113] = runtype.FuncPC(stubWpipii_pppp_113)
	stubsWpipii_pppp[114] = runtype.FuncPC(stubWpipii_pppp_114)
	stubsWpipii_pppp[115] = runtype.FuncPC(stubWpipii_pppp_115)
	stubsWpipii_pppp[116] = runtype.FuncPC(stubWpipii_pppp_116)
	stubsWpipii_pppp[117] = runtype.FuncPC(stubWpipii_pppp_117)
	stubsWpipii_pppp[118] = runtype.FuncPC(stubWpipii_pppp_118)
	stubsWpipii_pppp[119] = runtype.FuncPC(stubWpipii_pppp_119)
	stubsWpipii_pppp[120] = runtype.FuncPC(stubWpipii_pppp_120)
	stubsWpipii_pppp[121] = runtype.FuncPC(stubWpipii_pppp_121)
	stubsWpipii_pppp[122] = runtype.FuncPC(stubWpipii_pppp_122)
	stubsWpipii_pppp[123] = runtype.FuncPC(stubWpipii_pppp_123)
	stubsWpipii_pppp[124] = runtype.FuncPC(stubWpipii_pppp_124)
	stubsWpipii_pppp[125] = runtype.FuncPC(stubWpipii_pppp_125)
	stubsWpipii_pppp[126] = runtype.FuncPC(stubWpipii_pppp_126)
	stubsWpipii_pppp[127] = runtype.FuncPC(stubWpipii_pppp_127)
	registerWordPool("pipii_pppp", &wordPool{
		next:  &nextSlotWpipii_pppp,
		cap:   poolSizeWpipii_pppp,
		stubs: stubsWpipii_pppp[:],
		slots: slotPoolWpipii_pppp[:],
		name:  "Wpipii_pppp",
	})
}
