//go:build !wasm

// Code generated by gen_pools.go; DO NOT EDIT.
// Word-shape pppi_pppp pool: 256 slots. Native only (see gen_pools.go).

package stubs

import (
	"sync/atomic"
	"unsafe"

	"github.com/mvm-sh/mvm/runtype"
)

var (
	slotPoolWpppi_pppp [poolSizeWpppi_pppp]CoreFunc
	nextSlotWpppi_pppp atomic.Uint32
)

//go:noinline
func stubWpppi_pppp_0(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(0, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_1(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(1, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_2(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(2, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_3(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(3, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_4(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(4, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_5(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(5, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_6(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(6, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_7(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(7, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_8(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(8, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_9(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(9, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_10(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(10, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_11(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(11, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_12(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(12, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_13(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(13, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_14(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(14, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_15(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(15, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_16(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(16, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_17(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(17, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_18(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(18, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_19(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(19, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_20(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(20, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_21(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(21, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_22(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(22, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_23(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(23, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_24(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(24, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_25(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(25, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_26(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(26, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_27(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(27, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_28(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(28, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_29(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(29, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_30(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(30, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_31(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(31, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_32(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(32, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_33(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(33, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_34(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(34, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_35(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(35, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_36(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(36, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_37(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(37, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_38(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(38, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_39(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(39, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_40(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(40, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_41(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(41, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_42(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(42, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_43(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(43, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_44(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(44, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_45(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(45, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_46(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(46, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_47(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(47, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_48(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(48, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_49(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(49, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_50(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(50, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_51(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(51, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_52(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(52, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_53(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(53, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_54(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(54, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_55(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(55, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_56(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(56, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_57(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(57, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_58(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(58, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_59(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(59, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_60(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(60, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_61(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(61, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_62(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(62, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_63(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(63, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_64(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(64, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_65(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(65, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_66(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(66, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_67(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(67, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_68(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(68, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_69(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(69, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_70(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(70, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_71(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(71, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_72(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(72, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_73(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(73, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_74(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(74, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_75(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(75, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_76(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(76, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_77(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(77, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_78(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(78, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_79(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(79, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_80(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(80, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_81(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(81, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_82(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(82, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_83(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(83, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_84(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(84, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_85(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(85, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_86(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(86, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_87(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(87, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_88(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(88, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_89(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(89, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_90(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(90, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_91(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(91, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_92(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(92, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_93(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(93, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_94(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(94, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_95(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(95, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_96(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(96, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_97(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(97, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_98(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(98, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_99(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(99, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_100(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(100, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_101(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(101, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_102(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(102, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_103(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(103, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_104(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(104, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_105(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(105, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_106(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(106, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_107(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(107, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_108(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(108, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_109(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(109, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_110(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(110, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_111(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(111, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_112(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(112, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_113(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(113, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_114(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(114, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_115(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(115, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_116(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(116, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_117(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(117, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_118(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(118, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_119(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(119, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_120(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(120, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_121(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(121, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_122(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(122, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_123(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(123, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_124(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(124, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_125(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(125, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_126(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(126, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_127(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(127, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_128(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(128, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_129(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(129, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_130(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(130, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_131(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(131, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_132(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(132, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_133(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(133, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_134(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(134, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_135(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(135, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_136(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(136, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_137(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(137, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_138(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(138, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_139(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(139, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_140(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(140, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_141(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(141, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_142(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(142, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_143(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(143, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_144(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(144, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_145(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(145, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_146(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(146, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_147(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(147, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_148(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(148, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_149(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(149, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_150(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(150, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_151(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(151, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_152(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(152, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_153(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(153, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_154(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(154, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_155(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(155, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_156(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(156, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_157(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(157, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_158(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(158, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_159(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(159, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_160(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(160, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_161(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(161, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_162(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(162, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_163(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(163, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_164(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(164, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_165(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(165, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_166(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(166, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_167(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(167, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_168(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(168, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_169(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(169, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_170(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(170, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_171(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(171, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_172(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(172, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_173(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(173, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_174(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(174, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_175(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(175, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_176(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(176, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_177(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(177, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_178(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(178, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_179(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(179, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_180(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(180, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_181(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(181, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_182(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(182, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_183(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(183, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_184(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(184, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_185(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(185, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_186(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(186, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_187(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(187, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_188(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(188, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_189(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(189, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_190(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(190, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_191(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(191, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_192(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(192, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_193(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(193, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_194(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(194, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_195(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(195, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_196(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(196, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_197(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(197, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_198(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(198, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_199(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(199, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_200(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(200, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_201(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(201, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_202(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(202, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_203(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(203, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_204(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(204, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_205(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(205, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_206(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(206, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_207(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(207, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_208(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(208, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_209(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(209, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_210(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(210, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_211(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(211, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_212(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(212, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_213(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(213, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_214(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(214, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_215(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(215, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_216(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(216, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_217(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(217, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_218(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(218, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_219(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(219, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_220(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(220, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_221(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(221, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_222(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(222, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_223(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(223, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_224(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(224, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_225(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(225, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_226(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(226, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_227(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(227, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_228(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(228, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_229(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(229, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_230(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(230, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_231(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(231, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_232(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(232, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_233(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(233, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_234(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(234, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_235(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(235, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_236(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(236, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_237(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(237, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_238(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(238, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_239(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(239, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_240(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(240, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_241(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(241, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_242(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(242, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_243(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(243, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_244(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(244, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_245(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(245, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_246(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(246, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_247(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(247, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_248(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(248, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_249(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(249, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_250(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(250, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_251(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(251, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_252(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(252, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_253(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(253, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_254(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(254, recv, w0, w1, w2, w3)
}

//go:noinline
func stubWpppi_pppp_255(recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	return dispatchWpppi_pppp(255, recv, w0, w1, w2, w3)
}

var stubsWpppi_pppp [poolSizeWpppi_pppp]uintptr

func dispatchWpppi_pppp(slot uint32, recv unsafe.Pointer, w0 unsafe.Pointer, w1 unsafe.Pointer, w2 unsafe.Pointer, w3 uint64) (unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) {
	var pw [3]unsafe.Pointer
	var sw [1]uint64
	var fw [0]float64
	pw[0] = w0
	pw[1] = w1
	pw[2] = w2
	sw[0] = w3
	var rpw [4]unsafe.Pointer
	var rsw [0]uint64
	var rfw [0]float64
	if core := slotPoolWpppi_pppp[slot]; core != nil {
		core(recv, pw[:], sw[:], fw[:], rpw[:], rsw[:], rfw[:])
	}
	return rpw[0], rpw[1], rpw[2], rpw[3]
}

func init() {
	stubsWpppi_pppp[0] = runtype.FuncPC(stubWpppi_pppp_0)
	stubsWpppi_pppp[1] = runtype.FuncPC(stubWpppi_pppp_1)
	stubsWpppi_pppp[2] = runtype.FuncPC(stubWpppi_pppp_2)
	stubsWpppi_pppp[3] = runtype.FuncPC(stubWpppi_pppp_3)
	stubsWpppi_pppp[4] = runtype.FuncPC(stubWpppi_pppp_4)
	stubsWpppi_pppp[5] = runtype.FuncPC(stubWpppi_pppp_5)
	stubsWpppi_pppp[6] = runtype.FuncPC(stubWpppi_pppp_6)
	stubsWpppi_pppp[7] = runtype.FuncPC(stubWpppi_pppp_7)
	stubsWpppi_pppp[8] = runtype.FuncPC(stubWpppi_pppp_8)
	stubsWpppi_pppp[9] = runtype.FuncPC(stubWpppi_pppp_9)
	stubsWpppi_pppp[10] = runtype.FuncPC(stubWpppi_pppp_10)
	stubsWpppi_pppp[11] = runtype.FuncPC(stubWpppi_pppp_11)
	stubsWpppi_pppp[12] = runtype.FuncPC(stubWpppi_pppp_12)
	stubsWpppi_pppp[13] = runtype.FuncPC(stubWpppi_pppp_13)
	stubsWpppi_pppp[14] = runtype.FuncPC(stubWpppi_pppp_14)
	stubsWpppi_pppp[15] = runtype.FuncPC(stubWpppi_pppp_15)
	stubsWpppi_pppp[16] = runtype.FuncPC(stubWpppi_pppp_16)
	stubsWpppi_pppp[17] = runtype.FuncPC(stubWpppi_pppp_17)
	stubsWpppi_pppp[18] = runtype.FuncPC(stubWpppi_pppp_18)
	stubsWpppi_pppp[19] = runtype.FuncPC(stubWpppi_pppp_19)
	stubsWpppi_pppp[20] = runtype.FuncPC(stubWpppi_pppp_20)
	stubsWpppi_pppp[21] = runtype.FuncPC(stubWpppi_pppp_21)
	stubsWpppi_pppp[22] = runtype.FuncPC(stubWpppi_pppp_22)
	stubsWpppi_pppp[23] = runtype.FuncPC(stubWpppi_pppp_23)
	stubsWpppi_pppp[24] = runtype.FuncPC(stubWpppi_pppp_24)
	stubsWpppi_pppp[25] = runtype.FuncPC(stubWpppi_pppp_25)
	stubsWpppi_pppp[26] = runtype.FuncPC(stubWpppi_pppp_26)
	stubsWpppi_pppp[27] = runtype.FuncPC(stubWpppi_pppp_27)
	stubsWpppi_pppp[28] = runtype.FuncPC(stubWpppi_pppp_28)
	stubsWpppi_pppp[29] = runtype.FuncPC(stubWpppi_pppp_29)
	stubsWpppi_pppp[30] = runtype.FuncPC(stubWpppi_pppp_30)
	stubsWpppi_pppp[31] = runtype.FuncPC(stubWpppi_pppp_31)
	stubsWpppi_pppp[32] = runtype.FuncPC(stubWpppi_pppp_32)
	stubsWpppi_pppp[33] = runtype.FuncPC(stubWpppi_pppp_33)
	stubsWpppi_pppp[34] = runtype.FuncPC(stubWpppi_pppp_34)
	stubsWpppi_pppp[35] = runtype.FuncPC(stubWpppi_pppp_35)
	stubsWpppi_pppp[36] = runtype.FuncPC(stubWpppi_pppp_36)
	stubsWpppi_pppp[37] = runtype.FuncPC(stubWpppi_pppp_37)
	stubsWpppi_pppp[38] = runtype.FuncPC(stubWpppi_pppp_38)
	stubsWpppi_pppp[39] = runtype.FuncPC(stubWpppi_pppp_39)
	stubsWpppi_pppp[40] = runtype.FuncPC(stubWpppi_pppp_40)
	stubsWpppi_pppp[41] = runtype.FuncPC(stubWpppi_pppp_41)
	stubsWpppi_pppp[42] = runtype.FuncPC(stubWpppi_pppp_42)
	stubsWpppi_pppp[43] = runtype.FuncPC(stubWpppi_pppp_43)
	stubsWpppi_pppp[44] = runtype.FuncPC(stubWpppi_pppp_44)
	stubsWpppi_pppp[45] = runtype.FuncPC(stubWpppi_pppp_45)
	stubsWpppi_pppp[46] = runtype.FuncPC(stubWpppi_pppp_46)
	stubsWpppi_pppp[47] = runtype.FuncPC(stubWpppi_pppp_47)
	stubsWpppi_pppp[48] = runtype.FuncPC(stubWpppi_pppp_48)
	stubsWpppi_pppp[49] = runtype.FuncPC(stubWpppi_pppp_49)
	stubsWpppi_pppp[50] = runtype.FuncPC(stubWpppi_pppp_50)
	stubsWpppi_pppp[51] = runtype.FuncPC(stubWpppi_pppp_51)
	stubsWpppi_pppp[52] = runtype.FuncPC(stubWpppi_pppp_52)
	stubsWpppi_pppp[53] = runtype.FuncPC(stubWpppi_pppp_53)
	stubsWpppi_pppp[54] = runtype.FuncPC(stubWpppi_pppp_54)
	stubsWpppi_pppp[55] = runtype.FuncPC(stubWpppi_pppp_55)
	stubsWpppi_pppp[56] = runtype.FuncPC(stubWpppi_pppp_56)
	stubsWpppi_pppp[57] = runtype.FuncPC(stubWpppi_pppp_57)
	stubsWpppi_pppp[58] = runtype.FuncPC(stubWpppi_pppp_58)
	stubsWpppi_pppp[59] = runtype.FuncPC(stubWpppi_pppp_59)
	stubsWpppi_pppp[60] = runtype.FuncPC(stubWpppi_pppp_60)
	stubsWpppi_pppp[61] = runtype.FuncPC(stubWpppi_pppp_61)
	stubsWpppi_pppp[62] = runtype.FuncPC(stubWpppi_pppp_62)
	stubsWpppi_pppp[63] = runtype.FuncPC(stubWpppi_pppp_63)
	stubsWpppi_pppp[64] = runtype.FuncPC(stubWpppi_pppp_64)
	stubsWpppi_pppp[65] = runtype.FuncPC(stubWpppi_pppp_65)
	stubsWpppi_pppp[66] = runtype.FuncPC(stubWpppi_pppp_66)
	stubsWpppi_pppp[67] = runtype.FuncPC(stubWpppi_pppp_67)
	stubsWpppi_pppp[68] = runtype.FuncPC(stubWpppi_pppp_68)
	stubsWpppi_pppp[69] = runtype.FuncPC(stubWpppi_pppp_69)
	stubsWpppi_pppp[70] = runtype.FuncPC(stubWpppi_pppp_70)
	stubsWpppi_pppp[71] = runtype.FuncPC(stubWpppi_pppp_71)
	stubsWpppi_pppp[72] = runtype.FuncPC(stubWpppi_pppp_72)
	stubsWpppi_pppp[73] = runtype.FuncPC(stubWpppi_pppp_73)
	stubsWpppi_pppp[74] = runtype.FuncPC(stubWpppi_pppp_74)
	stubsWpppi_pppp[75] = runtype.FuncPC(stubWpppi_pppp_75)
	stubsWpppi_pppp[76] = runtype.FuncPC(stubWpppi_pppp_76)
	stubsWpppi_pppp[77] = runtype.FuncPC(stubWpppi_pppp_77)
	stubsWpppi_pppp[78] = runtype.FuncPC(stubWpppi_pppp_78)
	stubsWpppi_pppp[79] = runtype.FuncPC(stubWpppi_pppp_79)
	stubsWpppi_pppp[80] = runtype.FuncPC(stubWpppi_pppp_80)
	stubsWpppi_pppp[81] = runtype.FuncPC(stubWpppi_pppp_81)
	stubsWpppi_pppp[82] = runtype.FuncPC(stubWpppi_pppp_82)
	stubsWpppi_pppp[83] = runtype.FuncPC(stubWpppi_pppp_83)
	stubsWpppi_pppp[84] = runtype.FuncPC(stubWpppi_pppp_84)
	stubsWpppi_pppp[85] = runtype.FuncPC(stubWpppi_pppp_85)
	stubsWpppi_pppp[86] = runtype.FuncPC(stubWpppi_pppp_86)
	stubsWpppi_pppp[87] = runtype.FuncPC(stubWpppi_pppp_87)
	stubsWpppi_pppp[88] = runtype.FuncPC(stubWpppi_pppp_88)
	stubsWpppi_pppp[89] = runtype.FuncPC(stubWpppi_pppp_89)
	stubsWpppi_pppp[90] = runtype.FuncPC(stubWpppi_pppp_90)
	stubsWpppi_pppp[91] = runtype.FuncPC(stubWpppi_pppp_91)
	stubsWpppi_pppp[92] = runtype.FuncPC(stubWpppi_pppp_92)
	stubsWpppi_pppp[93] = runtype.FuncPC(stubWpppi_pppp_93)
	stubsWpppi_pppp[94] = runtype.FuncPC(stubWpppi_pppp_94)
	stubsWpppi_pppp[95] = runtype.FuncPC(stubWpppi_pppp_95)
	stubsWpppi_pppp[96] = runtype.FuncPC(stubWpppi_pppp_96)
	stubsWpppi_pppp[97] = runtype.FuncPC(stubWpppi_pppp_97)
	stubsWpppi_pppp[98] = runtype.FuncPC(stubWpppi_pppp_98)
	stubsWpppi_pppp[99] = runtype.FuncPC(stubWpppi_pppp_99)
	stubsWpppi_pppp[100] = runtype.FuncPC(stubWpppi_pppp_100)
	stubsWpppi_pppp[101] = runtype.FuncPC(stubWpppi_pppp_101)
	stubsWpppi_pppp[102] = runtype.FuncPC(stubWpppi_pppp_102)
	stubsWpppi_pppp[103] = runtype.FuncPC(stubWpppi_pppp_103)
	stubsWpppi_pppp[104] = runtype.FuncPC(stubWpppi_pppp_104)
	stubsWpppi_pppp[105] = runtype.FuncPC(stubWpppi_pppp_105)
	stubsWpppi_pppp[106] = runtype.FuncPC(stubWpppi_pppp_106)
	stubsWpppi_pppp[107] = runtype.FuncPC(stubWpppi_pppp_107)
	stubsWpppi_pppp[108] = runtype.FuncPC(stubWpppi_pppp_108)
	stubsWpppi_pppp[109] = runtype.FuncPC(stubWpppi_pppp_109)
	stubsWpppi_pppp[110] = runtype.FuncPC(stubWpppi_pppp_110)
	stubsWpppi_pppp[111] = runtype.FuncPC(stubWpppi_pppp_111)
	stubsWpppi_pppp[112] = runtype.FuncPC(stubWpppi_pppp_112)
	stubsWpppi_pppp[113] = runtype.FuncPC(stubWpppi_pppp_113)
	stubsWpppi_pppp[114] = runtype.FuncPC(stubWpppi_pppp_114)
	stubsWpppi_pppp[115] = runtype.FuncPC(stubWpppi_pppp_115)
	stubsWpppi_pppp[116] = runtype.FuncPC(stubWpppi_pppp_116)
	stubsWpppi_pppp[117] = runtype.FuncPC(stubWpppi_pppp_117)
	stubsWpppi_pppp[118] = runtype.FuncPC(stubWpppi_pppp_118)
	stubsWpppi_pppp[119] = runtype.FuncPC(stubWpppi_pppp_119)
	stubsWpppi_pppp[120] = runtype.FuncPC(stubWpppi_pppp_120)
	stubsWpppi_pppp[121] = runtype.FuncPC(stubWpppi_pppp_121)
	stubsWpppi_pppp[122] = runtype.FuncPC(stubWpppi_pppp_122)
	stubsWpppi_pppp[123] = runtype.FuncPC(stubWpppi_pppp_123)
	stubsWpppi_pppp[124] = runtype.FuncPC(stubWpppi_pppp_124)
	stubsWpppi_pppp[125] = runtype.FuncPC(stubWpppi_pppp_125)
	stubsWpppi_pppp[126] = runtype.FuncPC(stubWpppi_pppp_126)
	stubsWpppi_pppp[127] = runtype.FuncPC(stubWpppi_pppp_127)
	stubsWpppi_pppp[128] = runtype.FuncPC(stubWpppi_pppp_128)
	stubsWpppi_pppp[129] = runtype.FuncPC(stubWpppi_pppp_129)
	stubsWpppi_pppp[130] = runtype.FuncPC(stubWpppi_pppp_130)
	stubsWpppi_pppp[131] = runtype.FuncPC(stubWpppi_pppp_131)
	stubsWpppi_pppp[132] = runtype.FuncPC(stubWpppi_pppp_132)
	stubsWpppi_pppp[133] = runtype.FuncPC(stubWpppi_pppp_133)
	stubsWpppi_pppp[134] = runtype.FuncPC(stubWpppi_pppp_134)
	stubsWpppi_pppp[135] = runtype.FuncPC(stubWpppi_pppp_135)
	stubsWpppi_pppp[136] = runtype.FuncPC(stubWpppi_pppp_136)
	stubsWpppi_pppp[137] = runtype.FuncPC(stubWpppi_pppp_137)
	stubsWpppi_pppp[138] = runtype.FuncPC(stubWpppi_pppp_138)
	stubsWpppi_pppp[139] = runtype.FuncPC(stubWpppi_pppp_139)
	stubsWpppi_pppp[140] = runtype.FuncPC(stubWpppi_pppp_140)
	stubsWpppi_pppp[141] = runtype.FuncPC(stubWpppi_pppp_141)
	stubsWpppi_pppp[142] = runtype.FuncPC(stubWpppi_pppp_142)
	stubsWpppi_pppp[143] = runtype.FuncPC(stubWpppi_pppp_143)
	stubsWpppi_pppp[144] = runtype.FuncPC(stubWpppi_pppp_144)
	stubsWpppi_pppp[145] = runtype.FuncPC(stubWpppi_pppp_145)
	stubsWpppi_pppp[146] = runtype.FuncPC(stubWpppi_pppp_146)
	stubsWpppi_pppp[147] = runtype.FuncPC(stubWpppi_pppp_147)
	stubsWpppi_pppp[148] = runtype.FuncPC(stubWpppi_pppp_148)
	stubsWpppi_pppp[149] = runtype.FuncPC(stubWpppi_pppp_149)
	stubsWpppi_pppp[150] = runtype.FuncPC(stubWpppi_pppp_150)
	stubsWpppi_pppp[151] = runtype.FuncPC(stubWpppi_pppp_151)
	stubsWpppi_pppp[152] = runtype.FuncPC(stubWpppi_pppp_152)
	stubsWpppi_pppp[153] = runtype.FuncPC(stubWpppi_pppp_153)
	stubsWpppi_pppp[154] = runtype.FuncPC(stubWpppi_pppp_154)
	stubsWpppi_pppp[155] = runtype.FuncPC(stubWpppi_pppp_155)
	stubsWpppi_pppp[156] = runtype.FuncPC(stubWpppi_pppp_156)
	stubsWpppi_pppp[157] = runtype.FuncPC(stubWpppi_pppp_157)
	stubsWpppi_pppp[158] = runtype.FuncPC(stubWpppi_pppp_158)
	stubsWpppi_pppp[159] = runtype.FuncPC(stubWpppi_pppp_159)
	stubsWpppi_pppp[160] = runtype.FuncPC(stubWpppi_pppp_160)
	stubsWpppi_pppp[161] = runtype.FuncPC(stubWpppi_pppp_161)
	stubsWpppi_pppp[162] = runtype.FuncPC(stubWpppi_pppp_162)
	stubsWpppi_pppp[163] = runtype.FuncPC(stubWpppi_pppp_163)
	stubsWpppi_pppp[164] = runtype.FuncPC(stubWpppi_pppp_164)
	stubsWpppi_pppp[165] = runtype.FuncPC(stubWpppi_pppp_165)
	stubsWpppi_pppp[166] = runtype.FuncPC(stubWpppi_pppp_166)
	stubsWpppi_pppp[167] = runtype.FuncPC(stubWpppi_pppp_167)
	stubsWpppi_pppp[168] = runtype.FuncPC(stubWpppi_pppp_168)
	stubsWpppi_pppp[169] = runtype.FuncPC(stubWpppi_pppp_169)
	stubsWpppi_pppp[170] = runtype.FuncPC(stubWpppi_pppp_170)
	stubsWpppi_pppp[171] = runtype.FuncPC(stubWpppi_pppp_171)
	stubsWpppi_pppp[172] = runtype.FuncPC(stubWpppi_pppp_172)
	stubsWpppi_pppp[173] = runtype.FuncPC(stubWpppi_pppp_173)
	stubsWpppi_pppp[174] = runtype.FuncPC(stubWpppi_pppp_174)
	stubsWpppi_pppp[175] = runtype.FuncPC(stubWpppi_pppp_175)
	stubsWpppi_pppp[176] = runtype.FuncPC(stubWpppi_pppp_176)
	stubsWpppi_pppp[177] = runtype.FuncPC(stubWpppi_pppp_177)
	stubsWpppi_pppp[178] = runtype.FuncPC(stubWpppi_pppp_178)
	stubsWpppi_pppp[179] = runtype.FuncPC(stubWpppi_pppp_179)
	stubsWpppi_pppp[180] = runtype.FuncPC(stubWpppi_pppp_180)
	stubsWpppi_pppp[181] = runtype.FuncPC(stubWpppi_pppp_181)
	stubsWpppi_pppp[182] = runtype.FuncPC(stubWpppi_pppp_182)
	stubsWpppi_pppp[183] = runtype.FuncPC(stubWpppi_pppp_183)
	stubsWpppi_pppp[184] = runtype.FuncPC(stubWpppi_pppp_184)
	stubsWpppi_pppp[185] = runtype.FuncPC(stubWpppi_pppp_185)
	stubsWpppi_pppp[186] = runtype.FuncPC(stubWpppi_pppp_186)
	stubsWpppi_pppp[187] = runtype.FuncPC(stubWpppi_pppp_187)
	stubsWpppi_pppp[188] = runtype.FuncPC(stubWpppi_pppp_188)
	stubsWpppi_pppp[189] = runtype.FuncPC(stubWpppi_pppp_189)
	stubsWpppi_pppp[190] = runtype.FuncPC(stubWpppi_pppp_190)
	stubsWpppi_pppp[191] = runtype.FuncPC(stubWpppi_pppp_191)
	stubsWpppi_pppp[192] = runtype.FuncPC(stubWpppi_pppp_192)
	stubsWpppi_pppp[193] = runtype.FuncPC(stubWpppi_pppp_193)
	stubsWpppi_pppp[194] = runtype.FuncPC(stubWpppi_pppp_194)
	stubsWpppi_pppp[195] = runtype.FuncPC(stubWpppi_pppp_195)
	stubsWpppi_pppp[196] = runtype.FuncPC(stubWpppi_pppp_196)
	stubsWpppi_pppp[197] = runtype.FuncPC(stubWpppi_pppp_197)
	stubsWpppi_pppp[198] = runtype.FuncPC(stubWpppi_pppp_198)
	stubsWpppi_pppp[199] = runtype.FuncPC(stubWpppi_pppp_199)
	stubsWpppi_pppp[200] = runtype.FuncPC(stubWpppi_pppp_200)
	stubsWpppi_pppp[201] = runtype.FuncPC(stubWpppi_pppp_201)
	stubsWpppi_pppp[202] = runtype.FuncPC(stubWpppi_pppp_202)
	stubsWpppi_pppp[203] = runtype.FuncPC(stubWpppi_pppp_203)
	stubsWpppi_pppp[204] = runtype.FuncPC(stubWpppi_pppp_204)
	stubsWpppi_pppp[205] = runtype.FuncPC(stubWpppi_pppp_205)
	stubsWpppi_pppp[206] = runtype.FuncPC(stubWpppi_pppp_206)
	stubsWpppi_pppp[207] = runtype.FuncPC(stubWpppi_pppp_207)
	stubsWpppi_pppp[208] = runtype.FuncPC(stubWpppi_pppp_208)
	stubsWpppi_pppp[209] = runtype.FuncPC(stubWpppi_pppp_209)
	stubsWpppi_pppp[210] = runtype.FuncPC(stubWpppi_pppp_210)
	stubsWpppi_pppp[211] = runtype.FuncPC(stubWpppi_pppp_211)
	stubsWpppi_pppp[212] = runtype.FuncPC(stubWpppi_pppp_212)
	stubsWpppi_pppp[213] = runtype.FuncPC(stubWpppi_pppp_213)
	stubsWpppi_pppp[214] = runtype.FuncPC(stubWpppi_pppp_214)
	stubsWpppi_pppp[215] = runtype.FuncPC(stubWpppi_pppp_215)
	stubsWpppi_pppp[216] = runtype.FuncPC(stubWpppi_pppp_216)
	stubsWpppi_pppp[217] = runtype.FuncPC(stubWpppi_pppp_217)
	stubsWpppi_pppp[218] = runtype.FuncPC(stubWpppi_pppp_218)
	stubsWpppi_pppp[219] = runtype.FuncPC(stubWpppi_pppp_219)
	stubsWpppi_pppp[220] = runtype.FuncPC(stubWpppi_pppp_220)
	stubsWpppi_pppp[221] = runtype.FuncPC(stubWpppi_pppp_221)
	stubsWpppi_pppp[222] = runtype.FuncPC(stubWpppi_pppp_222)
	stubsWpppi_pppp[223] = runtype.FuncPC(stubWpppi_pppp_223)
	stubsWpppi_pppp[224] = runtype.FuncPC(stubWpppi_pppp_224)
	stubsWpppi_pppp[225] = runtype.FuncPC(stubWpppi_pppp_225)
	stubsWpppi_pppp[226] = runtype.FuncPC(stubWpppi_pppp_226)
	stubsWpppi_pppp[227] = runtype.FuncPC(stubWpppi_pppp_227)
	stubsWpppi_pppp[228] = runtype.FuncPC(stubWpppi_pppp_228)
	stubsWpppi_pppp[229] = runtype.FuncPC(stubWpppi_pppp_229)
	stubsWpppi_pppp[230] = runtype.FuncPC(stubWpppi_pppp_230)
	stubsWpppi_pppp[231] = runtype.FuncPC(stubWpppi_pppp_231)
	stubsWpppi_pppp[232] = runtype.FuncPC(stubWpppi_pppp_232)
	stubsWpppi_pppp[233] = runtype.FuncPC(stubWpppi_pppp_233)
	stubsWpppi_pppp[234] = runtype.FuncPC(stubWpppi_pppp_234)
	stubsWpppi_pppp[235] = runtype.FuncPC(stubWpppi_pppp_235)
	stubsWpppi_pppp[236] = runtype.FuncPC(stubWpppi_pppp_236)
	stubsWpppi_pppp[237] = runtype.FuncPC(stubWpppi_pppp_237)
	stubsWpppi_pppp[238] = runtype.FuncPC(stubWpppi_pppp_238)
	stubsWpppi_pppp[239] = runtype.FuncPC(stubWpppi_pppp_239)
	stubsWpppi_pppp[240] = runtype.FuncPC(stubWpppi_pppp_240)
	stubsWpppi_pppp[241] = runtype.FuncPC(stubWpppi_pppp_241)
	stubsWpppi_pppp[242] = runtype.FuncPC(stubWpppi_pppp_242)
	stubsWpppi_pppp[243] = runtype.FuncPC(stubWpppi_pppp_243)
	stubsWpppi_pppp[244] = runtype.FuncPC(stubWpppi_pppp_244)
	stubsWpppi_pppp[245] = runtype.FuncPC(stubWpppi_pppp_245)
	stubsWpppi_pppp[246] = runtype.FuncPC(stubWpppi_pppp_246)
	stubsWpppi_pppp[247] = runtype.FuncPC(stubWpppi_pppp_247)
	stubsWpppi_pppp[248] = runtype.FuncPC(stubWpppi_pppp_248)
	stubsWpppi_pppp[249] = runtype.FuncPC(stubWpppi_pppp_249)
	stubsWpppi_pppp[250] = runtype.FuncPC(stubWpppi_pppp_250)
	stubsWpppi_pppp[251] = runtype.FuncPC(stubWpppi_pppp_251)
	stubsWpppi_pppp[252] = runtype.FuncPC(stubWpppi_pppp_252)
	stubsWpppi_pppp[253] = runtype.FuncPC(stubWpppi_pppp_253)
	stubsWpppi_pppp[254] = runtype.FuncPC(stubWpppi_pppp_254)
	stubsWpppi_pppp[255] = runtype.FuncPC(stubWpppi_pppp_255)
	registerWordPool("pppi_pppp", &wordPool{
		next:  &nextSlotWpppi_pppp,
		cap:   poolSizeWpppi_pppp,
		stubs: stubsWpppi_pppp[:],
		slots: slotPoolWpppi_pppp[:],
		name:  "Wpppi_pppp",
	})
}
