// Code generated by gen_pools.go; DO NOT EDIT.
// Shape S8 pool: 512 slots.

package stubs

import (
	"unsafe"

	"github.com/mvm-sh/mvm/runtype"
)

const poolSizeS8 = 512

//go:noinline
func stubS8_0(recv unsafe.Pointer) int { return dispatchS8(0, recv) }

//go:noinline
func stubS8_1(recv unsafe.Pointer) int { return dispatchS8(1, recv) }

//go:noinline
func stubS8_2(recv unsafe.Pointer) int { return dispatchS8(2, recv) }

//go:noinline
func stubS8_3(recv unsafe.Pointer) int { return dispatchS8(3, recv) }

//go:noinline
func stubS8_4(recv unsafe.Pointer) int { return dispatchS8(4, recv) }

//go:noinline
func stubS8_5(recv unsafe.Pointer) int { return dispatchS8(5, recv) }

//go:noinline
func stubS8_6(recv unsafe.Pointer) int { return dispatchS8(6, recv) }

//go:noinline
func stubS8_7(recv unsafe.Pointer) int { return dispatchS8(7, recv) }

//go:noinline
func stubS8_8(recv unsafe.Pointer) int { return dispatchS8(8, recv) }

//go:noinline
func stubS8_9(recv unsafe.Pointer) int { return dispatchS8(9, recv) }

//go:noinline
func stubS8_10(recv unsafe.Pointer) int { return dispatchS8(10, recv) }

//go:noinline
func stubS8_11(recv unsafe.Pointer) int { return dispatchS8(11, recv) }

//go:noinline
func stubS8_12(recv unsafe.Pointer) int { return dispatchS8(12, recv) }

//go:noinline
func stubS8_13(recv unsafe.Pointer) int { return dispatchS8(13, recv) }

//go:noinline
func stubS8_14(recv unsafe.Pointer) int { return dispatchS8(14, recv) }

//go:noinline
func stubS8_15(recv unsafe.Pointer) int { return dispatchS8(15, recv) }

//go:noinline
func stubS8_16(recv unsafe.Pointer) int { return dispatchS8(16, recv) }

//go:noinline
func stubS8_17(recv unsafe.Pointer) int { return dispatchS8(17, recv) }

//go:noinline
func stubS8_18(recv unsafe.Pointer) int { return dispatchS8(18, recv) }

//go:noinline
func stubS8_19(recv unsafe.Pointer) int { return dispatchS8(19, recv) }

//go:noinline
func stubS8_20(recv unsafe.Pointer) int { return dispatchS8(20, recv) }

//go:noinline
func stubS8_21(recv unsafe.Pointer) int { return dispatchS8(21, recv) }

//go:noinline
func stubS8_22(recv unsafe.Pointer) int { return dispatchS8(22, recv) }

//go:noinline
func stubS8_23(recv unsafe.Pointer) int { return dispatchS8(23, recv) }

//go:noinline
func stubS8_24(recv unsafe.Pointer) int { return dispatchS8(24, recv) }

//go:noinline
func stubS8_25(recv unsafe.Pointer) int { return dispatchS8(25, recv) }

//go:noinline
func stubS8_26(recv unsafe.Pointer) int { return dispatchS8(26, recv) }

//go:noinline
func stubS8_27(recv unsafe.Pointer) int { return dispatchS8(27, recv) }

//go:noinline
func stubS8_28(recv unsafe.Pointer) int { return dispatchS8(28, recv) }

//go:noinline
func stubS8_29(recv unsafe.Pointer) int { return dispatchS8(29, recv) }

//go:noinline
func stubS8_30(recv unsafe.Pointer) int { return dispatchS8(30, recv) }

//go:noinline
func stubS8_31(recv unsafe.Pointer) int { return dispatchS8(31, recv) }

//go:noinline
func stubS8_32(recv unsafe.Pointer) int { return dispatchS8(32, recv) }

//go:noinline
func stubS8_33(recv unsafe.Pointer) int { return dispatchS8(33, recv) }

//go:noinline
func stubS8_34(recv unsafe.Pointer) int { return dispatchS8(34, recv) }

//go:noinline
func stubS8_35(recv unsafe.Pointer) int { return dispatchS8(35, recv) }

//go:noinline
func stubS8_36(recv unsafe.Pointer) int { return dispatchS8(36, recv) }

//go:noinline
func stubS8_37(recv unsafe.Pointer) int { return dispatchS8(37, recv) }

//go:noinline
func stubS8_38(recv unsafe.Pointer) int { return dispatchS8(38, recv) }

//go:noinline
func stubS8_39(recv unsafe.Pointer) int { return dispatchS8(39, recv) }

//go:noinline
func stubS8_40(recv unsafe.Pointer) int { return dispatchS8(40, recv) }

//go:noinline
func stubS8_41(recv unsafe.Pointer) int { return dispatchS8(41, recv) }

//go:noinline
func stubS8_42(recv unsafe.Pointer) int { return dispatchS8(42, recv) }

//go:noinline
func stubS8_43(recv unsafe.Pointer) int { return dispatchS8(43, recv) }

//go:noinline
func stubS8_44(recv unsafe.Pointer) int { return dispatchS8(44, recv) }

//go:noinline
func stubS8_45(recv unsafe.Pointer) int { return dispatchS8(45, recv) }

//go:noinline
func stubS8_46(recv unsafe.Pointer) int { return dispatchS8(46, recv) }

//go:noinline
func stubS8_47(recv unsafe.Pointer) int { return dispatchS8(47, recv) }

//go:noinline
func stubS8_48(recv unsafe.Pointer) int { return dispatchS8(48, recv) }

//go:noinline
func stubS8_49(recv unsafe.Pointer) int { return dispatchS8(49, recv) }

//go:noinline
func stubS8_50(recv unsafe.Pointer) int { return dispatchS8(50, recv) }

//go:noinline
func stubS8_51(recv unsafe.Pointer) int { return dispatchS8(51, recv) }

//go:noinline
func stubS8_52(recv unsafe.Pointer) int { return dispatchS8(52, recv) }

//go:noinline
func stubS8_53(recv unsafe.Pointer) int { return dispatchS8(53, recv) }

//go:noinline
func stubS8_54(recv unsafe.Pointer) int { return dispatchS8(54, recv) }

//go:noinline
func stubS8_55(recv unsafe.Pointer) int { return dispatchS8(55, recv) }

//go:noinline
func stubS8_56(recv unsafe.Pointer) int { return dispatchS8(56, recv) }

//go:noinline
func stubS8_57(recv unsafe.Pointer) int { return dispatchS8(57, recv) }

//go:noinline
func stubS8_58(recv unsafe.Pointer) int { return dispatchS8(58, recv) }

//go:noinline
func stubS8_59(recv unsafe.Pointer) int { return dispatchS8(59, recv) }

//go:noinline
func stubS8_60(recv unsafe.Pointer) int { return dispatchS8(60, recv) }

//go:noinline
func stubS8_61(recv unsafe.Pointer) int { return dispatchS8(61, recv) }

//go:noinline
func stubS8_62(recv unsafe.Pointer) int { return dispatchS8(62, recv) }

//go:noinline
func stubS8_63(recv unsafe.Pointer) int { return dispatchS8(63, recv) }

//go:noinline
func stubS8_64(recv unsafe.Pointer) int { return dispatchS8(64, recv) }

//go:noinline
func stubS8_65(recv unsafe.Pointer) int { return dispatchS8(65, recv) }

//go:noinline
func stubS8_66(recv unsafe.Pointer) int { return dispatchS8(66, recv) }

//go:noinline
func stubS8_67(recv unsafe.Pointer) int { return dispatchS8(67, recv) }

//go:noinline
func stubS8_68(recv unsafe.Pointer) int { return dispatchS8(68, recv) }

//go:noinline
func stubS8_69(recv unsafe.Pointer) int { return dispatchS8(69, recv) }

//go:noinline
func stubS8_70(recv unsafe.Pointer) int { return dispatchS8(70, recv) }

//go:noinline
func stubS8_71(recv unsafe.Pointer) int { return dispatchS8(71, recv) }

//go:noinline
func stubS8_72(recv unsafe.Pointer) int { return dispatchS8(72, recv) }

//go:noinline
func stubS8_73(recv unsafe.Pointer) int { return dispatchS8(73, recv) }

//go:noinline
func stubS8_74(recv unsafe.Pointer) int { return dispatchS8(74, recv) }

//go:noinline
func stubS8_75(recv unsafe.Pointer) int { return dispatchS8(75, recv) }

//go:noinline
func stubS8_76(recv unsafe.Pointer) int { return dispatchS8(76, recv) }

//go:noinline
func stubS8_77(recv unsafe.Pointer) int { return dispatchS8(77, recv) }

//go:noinline
func stubS8_78(recv unsafe.Pointer) int { return dispatchS8(78, recv) }

//go:noinline
func stubS8_79(recv unsafe.Pointer) int { return dispatchS8(79, recv) }

//go:noinline
func stubS8_80(recv unsafe.Pointer) int { return dispatchS8(80, recv) }

//go:noinline
func stubS8_81(recv unsafe.Pointer) int { return dispatchS8(81, recv) }

//go:noinline
func stubS8_82(recv unsafe.Pointer) int { return dispatchS8(82, recv) }

//go:noinline
func stubS8_83(recv unsafe.Pointer) int { return dispatchS8(83, recv) }

//go:noinline
func stubS8_84(recv unsafe.Pointer) int { return dispatchS8(84, recv) }

//go:noinline
func stubS8_85(recv unsafe.Pointer) int { return dispatchS8(85, recv) }

//go:noinline
func stubS8_86(recv unsafe.Pointer) int { return dispatchS8(86, recv) }

//go:noinline
func stubS8_87(recv unsafe.Pointer) int { return dispatchS8(87, recv) }

//go:noinline
func stubS8_88(recv unsafe.Pointer) int { return dispatchS8(88, recv) }

//go:noinline
func stubS8_89(recv unsafe.Pointer) int { return dispatchS8(89, recv) }

//go:noinline
func stubS8_90(recv unsafe.Pointer) int { return dispatchS8(90, recv) }

//go:noinline
func stubS8_91(recv unsafe.Pointer) int { return dispatchS8(91, recv) }

//go:noinline
func stubS8_92(recv unsafe.Pointer) int { return dispatchS8(92, recv) }

//go:noinline
func stubS8_93(recv unsafe.Pointer) int { return dispatchS8(93, recv) }

//go:noinline
func stubS8_94(recv unsafe.Pointer) int { return dispatchS8(94, recv) }

//go:noinline
func stubS8_95(recv unsafe.Pointer) int { return dispatchS8(95, recv) }

//go:noinline
func stubS8_96(recv unsafe.Pointer) int { return dispatchS8(96, recv) }

//go:noinline
func stubS8_97(recv unsafe.Pointer) int { return dispatchS8(97, recv) }

//go:noinline
func stubS8_98(recv unsafe.Pointer) int { return dispatchS8(98, recv) }

//go:noinline
func stubS8_99(recv unsafe.Pointer) int { return dispatchS8(99, recv) }

//go:noinline
func stubS8_100(recv unsafe.Pointer) int { return dispatchS8(100, recv) }

//go:noinline
func stubS8_101(recv unsafe.Pointer) int { return dispatchS8(101, recv) }

//go:noinline
func stubS8_102(recv unsafe.Pointer) int { return dispatchS8(102, recv) }

//go:noinline
func stubS8_103(recv unsafe.Pointer) int { return dispatchS8(103, recv) }

//go:noinline
func stubS8_104(recv unsafe.Pointer) int { return dispatchS8(104, recv) }

//go:noinline
func stubS8_105(recv unsafe.Pointer) int { return dispatchS8(105, recv) }

//go:noinline
func stubS8_106(recv unsafe.Pointer) int { return dispatchS8(106, recv) }

//go:noinline
func stubS8_107(recv unsafe.Pointer) int { return dispatchS8(107, recv) }

//go:noinline
func stubS8_108(recv unsafe.Pointer) int { return dispatchS8(108, recv) }

//go:noinline
func stubS8_109(recv unsafe.Pointer) int { return dispatchS8(109, recv) }

//go:noinline
func stubS8_110(recv unsafe.Pointer) int { return dispatchS8(110, recv) }

//go:noinline
func stubS8_111(recv unsafe.Pointer) int { return dispatchS8(111, recv) }

//go:noinline
func stubS8_112(recv unsafe.Pointer) int { return dispatchS8(112, recv) }

//go:noinline
func stubS8_113(recv unsafe.Pointer) int { return dispatchS8(113, recv) }

//go:noinline
func stubS8_114(recv unsafe.Pointer) int { return dispatchS8(114, recv) }

//go:noinline
func stubS8_115(recv unsafe.Pointer) int { return dispatchS8(115, recv) }

//go:noinline
func stubS8_116(recv unsafe.Pointer) int { return dispatchS8(116, recv) }

//go:noinline
func stubS8_117(recv unsafe.Pointer) int { return dispatchS8(117, recv) }

//go:noinline
func stubS8_118(recv unsafe.Pointer) int { return dispatchS8(118, recv) }

//go:noinline
func stubS8_119(recv unsafe.Pointer) int { return dispatchS8(119, recv) }

//go:noinline
func stubS8_120(recv unsafe.Pointer) int { return dispatchS8(120, recv) }

//go:noinline
func stubS8_121(recv unsafe.Pointer) int { return dispatchS8(121, recv) }

//go:noinline
func stubS8_122(recv unsafe.Pointer) int { return dispatchS8(122, recv) }

//go:noinline
func stubS8_123(recv unsafe.Pointer) int { return dispatchS8(123, recv) }

//go:noinline
func stubS8_124(recv unsafe.Pointer) int { return dispatchS8(124, recv) }

//go:noinline
func stubS8_125(recv unsafe.Pointer) int { return dispatchS8(125, recv) }

//go:noinline
func stubS8_126(recv unsafe.Pointer) int { return dispatchS8(126, recv) }

//go:noinline
func stubS8_127(recv unsafe.Pointer) int { return dispatchS8(127, recv) }

//go:noinline
func stubS8_128(recv unsafe.Pointer) int { return dispatchS8(128, recv) }

//go:noinline
func stubS8_129(recv unsafe.Pointer) int { return dispatchS8(129, recv) }

//go:noinline
func stubS8_130(recv unsafe.Pointer) int { return dispatchS8(130, recv) }

//go:noinline
func stubS8_131(recv unsafe.Pointer) int { return dispatchS8(131, recv) }

//go:noinline
func stubS8_132(recv unsafe.Pointer) int { return dispatchS8(132, recv) }

//go:noinline
func stubS8_133(recv unsafe.Pointer) int { return dispatchS8(133, recv) }

//go:noinline
func stubS8_134(recv unsafe.Pointer) int { return dispatchS8(134, recv) }

//go:noinline
func stubS8_135(recv unsafe.Pointer) int { return dispatchS8(135, recv) }

//go:noinline
func stubS8_136(recv unsafe.Pointer) int { return dispatchS8(136, recv) }

//go:noinline
func stubS8_137(recv unsafe.Pointer) int { return dispatchS8(137, recv) }

//go:noinline
func stubS8_138(recv unsafe.Pointer) int { return dispatchS8(138, recv) }

//go:noinline
func stubS8_139(recv unsafe.Pointer) int { return dispatchS8(139, recv) }

//go:noinline
func stubS8_140(recv unsafe.Pointer) int { return dispatchS8(140, recv) }

//go:noinline
func stubS8_141(recv unsafe.Pointer) int { return dispatchS8(141, recv) }

//go:noinline
func stubS8_142(recv unsafe.Pointer) int { return dispatchS8(142, recv) }

//go:noinline
func stubS8_143(recv unsafe.Pointer) int { return dispatchS8(143, recv) }

//go:noinline
func stubS8_144(recv unsafe.Pointer) int { return dispatchS8(144, recv) }

//go:noinline
func stubS8_145(recv unsafe.Pointer) int { return dispatchS8(145, recv) }

//go:noinline
func stubS8_146(recv unsafe.Pointer) int { return dispatchS8(146, recv) }

//go:noinline
func stubS8_147(recv unsafe.Pointer) int { return dispatchS8(147, recv) }

//go:noinline
func stubS8_148(recv unsafe.Pointer) int { return dispatchS8(148, recv) }

//go:noinline
func stubS8_149(recv unsafe.Pointer) int { return dispatchS8(149, recv) }

//go:noinline
func stubS8_150(recv unsafe.Pointer) int { return dispatchS8(150, recv) }

//go:noinline
func stubS8_151(recv unsafe.Pointer) int { return dispatchS8(151, recv) }

//go:noinline
func stubS8_152(recv unsafe.Pointer) int { return dispatchS8(152, recv) }

//go:noinline
func stubS8_153(recv unsafe.Pointer) int { return dispatchS8(153, recv) }

//go:noinline
func stubS8_154(recv unsafe.Pointer) int { return dispatchS8(154, recv) }

//go:noinline
func stubS8_155(recv unsafe.Pointer) int { return dispatchS8(155, recv) }

//go:noinline
func stubS8_156(recv unsafe.Pointer) int { return dispatchS8(156, recv) }

//go:noinline
func stubS8_157(recv unsafe.Pointer) int { return dispatchS8(157, recv) }

//go:noinline
func stubS8_158(recv unsafe.Pointer) int { return dispatchS8(158, recv) }

//go:noinline
func stubS8_159(recv unsafe.Pointer) int { return dispatchS8(159, recv) }

//go:noinline
func stubS8_160(recv unsafe.Pointer) int { return dispatchS8(160, recv) }

//go:noinline
func stubS8_161(recv unsafe.Pointer) int { return dispatchS8(161, recv) }

//go:noinline
func stubS8_162(recv unsafe.Pointer) int { return dispatchS8(162, recv) }

//go:noinline
func stubS8_163(recv unsafe.Pointer) int { return dispatchS8(163, recv) }

//go:noinline
func stubS8_164(recv unsafe.Pointer) int { return dispatchS8(164, recv) }

//go:noinline
func stubS8_165(recv unsafe.Pointer) int { return dispatchS8(165, recv) }

//go:noinline
func stubS8_166(recv unsafe.Pointer) int { return dispatchS8(166, recv) }

//go:noinline
func stubS8_167(recv unsafe.Pointer) int { return dispatchS8(167, recv) }

//go:noinline
func stubS8_168(recv unsafe.Pointer) int { return dispatchS8(168, recv) }

//go:noinline
func stubS8_169(recv unsafe.Pointer) int { return dispatchS8(169, recv) }

//go:noinline
func stubS8_170(recv unsafe.Pointer) int { return dispatchS8(170, recv) }

//go:noinline
func stubS8_171(recv unsafe.Pointer) int { return dispatchS8(171, recv) }

//go:noinline
func stubS8_172(recv unsafe.Pointer) int { return dispatchS8(172, recv) }

//go:noinline
func stubS8_173(recv unsafe.Pointer) int { return dispatchS8(173, recv) }

//go:noinline
func stubS8_174(recv unsafe.Pointer) int { return dispatchS8(174, recv) }

//go:noinline
func stubS8_175(recv unsafe.Pointer) int { return dispatchS8(175, recv) }

//go:noinline
func stubS8_176(recv unsafe.Pointer) int { return dispatchS8(176, recv) }

//go:noinline
func stubS8_177(recv unsafe.Pointer) int { return dispatchS8(177, recv) }

//go:noinline
func stubS8_178(recv unsafe.Pointer) int { return dispatchS8(178, recv) }

//go:noinline
func stubS8_179(recv unsafe.Pointer) int { return dispatchS8(179, recv) }

//go:noinline
func stubS8_180(recv unsafe.Pointer) int { return dispatchS8(180, recv) }

//go:noinline
func stubS8_181(recv unsafe.Pointer) int { return dispatchS8(181, recv) }

//go:noinline
func stubS8_182(recv unsafe.Pointer) int { return dispatchS8(182, recv) }

//go:noinline
func stubS8_183(recv unsafe.Pointer) int { return dispatchS8(183, recv) }

//go:noinline
func stubS8_184(recv unsafe.Pointer) int { return dispatchS8(184, recv) }

//go:noinline
func stubS8_185(recv unsafe.Pointer) int { return dispatchS8(185, recv) }

//go:noinline
func stubS8_186(recv unsafe.Pointer) int { return dispatchS8(186, recv) }

//go:noinline
func stubS8_187(recv unsafe.Pointer) int { return dispatchS8(187, recv) }

//go:noinline
func stubS8_188(recv unsafe.Pointer) int { return dispatchS8(188, recv) }

//go:noinline
func stubS8_189(recv unsafe.Pointer) int { return dispatchS8(189, recv) }

//go:noinline
func stubS8_190(recv unsafe.Pointer) int { return dispatchS8(190, recv) }

//go:noinline
func stubS8_191(recv unsafe.Pointer) int { return dispatchS8(191, recv) }

//go:noinline
func stubS8_192(recv unsafe.Pointer) int { return dispatchS8(192, recv) }

//go:noinline
func stubS8_193(recv unsafe.Pointer) int { return dispatchS8(193, recv) }

//go:noinline
func stubS8_194(recv unsafe.Pointer) int { return dispatchS8(194, recv) }

//go:noinline
func stubS8_195(recv unsafe.Pointer) int { return dispatchS8(195, recv) }

//go:noinline
func stubS8_196(recv unsafe.Pointer) int { return dispatchS8(196, recv) }

//go:noinline
func stubS8_197(recv unsafe.Pointer) int { return dispatchS8(197, recv) }

//go:noinline
func stubS8_198(recv unsafe.Pointer) int { return dispatchS8(198, recv) }

//go:noinline
func stubS8_199(recv unsafe.Pointer) int { return dispatchS8(199, recv) }

//go:noinline
func stubS8_200(recv unsafe.Pointer) int { return dispatchS8(200, recv) }

//go:noinline
func stubS8_201(recv unsafe.Pointer) int { return dispatchS8(201, recv) }

//go:noinline
func stubS8_202(recv unsafe.Pointer) int { return dispatchS8(202, recv) }

//go:noinline
func stubS8_203(recv unsafe.Pointer) int { return dispatchS8(203, recv) }

//go:noinline
func stubS8_204(recv unsafe.Pointer) int { return dispatchS8(204, recv) }

//go:noinline
func stubS8_205(recv unsafe.Pointer) int { return dispatchS8(205, recv) }

//go:noinline
func stubS8_206(recv unsafe.Pointer) int { return dispatchS8(206, recv) }

//go:noinline
func stubS8_207(recv unsafe.Pointer) int { return dispatchS8(207, recv) }

//go:noinline
func stubS8_208(recv unsafe.Pointer) int { return dispatchS8(208, recv) }

//go:noinline
func stubS8_209(recv unsafe.Pointer) int { return dispatchS8(209, recv) }

//go:noinline
func stubS8_210(recv unsafe.Pointer) int { return dispatchS8(210, recv) }

//go:noinline
func stubS8_211(recv unsafe.Pointer) int { return dispatchS8(211, recv) }

//go:noinline
func stubS8_212(recv unsafe.Pointer) int { return dispatchS8(212, recv) }

//go:noinline
func stubS8_213(recv unsafe.Pointer) int { return dispatchS8(213, recv) }

//go:noinline
func stubS8_214(recv unsafe.Pointer) int { return dispatchS8(214, recv) }

//go:noinline
func stubS8_215(recv unsafe.Pointer) int { return dispatchS8(215, recv) }

//go:noinline
func stubS8_216(recv unsafe.Pointer) int { return dispatchS8(216, recv) }

//go:noinline
func stubS8_217(recv unsafe.Pointer) int { return dispatchS8(217, recv) }

//go:noinline
func stubS8_218(recv unsafe.Pointer) int { return dispatchS8(218, recv) }

//go:noinline
func stubS8_219(recv unsafe.Pointer) int { return dispatchS8(219, recv) }

//go:noinline
func stubS8_220(recv unsafe.Pointer) int { return dispatchS8(220, recv) }

//go:noinline
func stubS8_221(recv unsafe.Pointer) int { return dispatchS8(221, recv) }

//go:noinline
func stubS8_222(recv unsafe.Pointer) int { return dispatchS8(222, recv) }

//go:noinline
func stubS8_223(recv unsafe.Pointer) int { return dispatchS8(223, recv) }

//go:noinline
func stubS8_224(recv unsafe.Pointer) int { return dispatchS8(224, recv) }

//go:noinline
func stubS8_225(recv unsafe.Pointer) int { return dispatchS8(225, recv) }

//go:noinline
func stubS8_226(recv unsafe.Pointer) int { return dispatchS8(226, recv) }

//go:noinline
func stubS8_227(recv unsafe.Pointer) int { return dispatchS8(227, recv) }

//go:noinline
func stubS8_228(recv unsafe.Pointer) int { return dispatchS8(228, recv) }

//go:noinline
func stubS8_229(recv unsafe.Pointer) int { return dispatchS8(229, recv) }

//go:noinline
func stubS8_230(recv unsafe.Pointer) int { return dispatchS8(230, recv) }

//go:noinline
func stubS8_231(recv unsafe.Pointer) int { return dispatchS8(231, recv) }

//go:noinline
func stubS8_232(recv unsafe.Pointer) int { return dispatchS8(232, recv) }

//go:noinline
func stubS8_233(recv unsafe.Pointer) int { return dispatchS8(233, recv) }

//go:noinline
func stubS8_234(recv unsafe.Pointer) int { return dispatchS8(234, recv) }

//go:noinline
func stubS8_235(recv unsafe.Pointer) int { return dispatchS8(235, recv) }

//go:noinline
func stubS8_236(recv unsafe.Pointer) int { return dispatchS8(236, recv) }

//go:noinline
func stubS8_237(recv unsafe.Pointer) int { return dispatchS8(237, recv) }

//go:noinline
func stubS8_238(recv unsafe.Pointer) int { return dispatchS8(238, recv) }

//go:noinline
func stubS8_239(recv unsafe.Pointer) int { return dispatchS8(239, recv) }

//go:noinline
func stubS8_240(recv unsafe.Pointer) int { return dispatchS8(240, recv) }

//go:noinline
func stubS8_241(recv unsafe.Pointer) int { return dispatchS8(241, recv) }

//go:noinline
func stubS8_242(recv unsafe.Pointer) int { return dispatchS8(242, recv) }

//go:noinline
func stubS8_243(recv unsafe.Pointer) int { return dispatchS8(243, recv) }

//go:noinline
func stubS8_244(recv unsafe.Pointer) int { return dispatchS8(244, recv) }

//go:noinline
func stubS8_245(recv unsafe.Pointer) int { return dispatchS8(245, recv) }

//go:noinline
func stubS8_246(recv unsafe.Pointer) int { return dispatchS8(246, recv) }

//go:noinline
func stubS8_247(recv unsafe.Pointer) int { return dispatchS8(247, recv) }

//go:noinline
func stubS8_248(recv unsafe.Pointer) int { return dispatchS8(248, recv) }

//go:noinline
func stubS8_249(recv unsafe.Pointer) int { return dispatchS8(249, recv) }

//go:noinline
func stubS8_250(recv unsafe.Pointer) int { return dispatchS8(250, recv) }

//go:noinline
func stubS8_251(recv unsafe.Pointer) int { return dispatchS8(251, recv) }

//go:noinline
func stubS8_252(recv unsafe.Pointer) int { return dispatchS8(252, recv) }

//go:noinline
func stubS8_253(recv unsafe.Pointer) int { return dispatchS8(253, recv) }

//go:noinline
func stubS8_254(recv unsafe.Pointer) int { return dispatchS8(254, recv) }

//go:noinline
func stubS8_255(recv unsafe.Pointer) int { return dispatchS8(255, recv) }

//go:noinline
func stubS8_256(recv unsafe.Pointer) int { return dispatchS8(256, recv) }

//go:noinline
func stubS8_257(recv unsafe.Pointer) int { return dispatchS8(257, recv) }

//go:noinline
func stubS8_258(recv unsafe.Pointer) int { return dispatchS8(258, recv) }

//go:noinline
func stubS8_259(recv unsafe.Pointer) int { return dispatchS8(259, recv) }

//go:noinline
func stubS8_260(recv unsafe.Pointer) int { return dispatchS8(260, recv) }

//go:noinline
func stubS8_261(recv unsafe.Pointer) int { return dispatchS8(261, recv) }

//go:noinline
func stubS8_262(recv unsafe.Pointer) int { return dispatchS8(262, recv) }

//go:noinline
func stubS8_263(recv unsafe.Pointer) int { return dispatchS8(263, recv) }

//go:noinline
func stubS8_264(recv unsafe.Pointer) int { return dispatchS8(264, recv) }

//go:noinline
func stubS8_265(recv unsafe.Pointer) int { return dispatchS8(265, recv) }

//go:noinline
func stubS8_266(recv unsafe.Pointer) int { return dispatchS8(266, recv) }

//go:noinline
func stubS8_267(recv unsafe.Pointer) int { return dispatchS8(267, recv) }

//go:noinline
func stubS8_268(recv unsafe.Pointer) int { return dispatchS8(268, recv) }

//go:noinline
func stubS8_269(recv unsafe.Pointer) int { return dispatchS8(269, recv) }

//go:noinline
func stubS8_270(recv unsafe.Pointer) int { return dispatchS8(270, recv) }

//go:noinline
func stubS8_271(recv unsafe.Pointer) int { return dispatchS8(271, recv) }

//go:noinline
func stubS8_272(recv unsafe.Pointer) int { return dispatchS8(272, recv) }

//go:noinline
func stubS8_273(recv unsafe.Pointer) int { return dispatchS8(273, recv) }

//go:noinline
func stubS8_274(recv unsafe.Pointer) int { return dispatchS8(274, recv) }

//go:noinline
func stubS8_275(recv unsafe.Pointer) int { return dispatchS8(275, recv) }

//go:noinline
func stubS8_276(recv unsafe.Pointer) int { return dispatchS8(276, recv) }

//go:noinline
func stubS8_277(recv unsafe.Pointer) int { return dispatchS8(277, recv) }

//go:noinline
func stubS8_278(recv unsafe.Pointer) int { return dispatchS8(278, recv) }

//go:noinline
func stubS8_279(recv unsafe.Pointer) int { return dispatchS8(279, recv) }

//go:noinline
func stubS8_280(recv unsafe.Pointer) int { return dispatchS8(280, recv) }

//go:noinline
func stubS8_281(recv unsafe.Pointer) int { return dispatchS8(281, recv) }

//go:noinline
func stubS8_282(recv unsafe.Pointer) int { return dispatchS8(282, recv) }

//go:noinline
func stubS8_283(recv unsafe.Pointer) int { return dispatchS8(283, recv) }

//go:noinline
func stubS8_284(recv unsafe.Pointer) int { return dispatchS8(284, recv) }

//go:noinline
func stubS8_285(recv unsafe.Pointer) int { return dispatchS8(285, recv) }

//go:noinline
func stubS8_286(recv unsafe.Pointer) int { return dispatchS8(286, recv) }

//go:noinline
func stubS8_287(recv unsafe.Pointer) int { return dispatchS8(287, recv) }

//go:noinline
func stubS8_288(recv unsafe.Pointer) int { return dispatchS8(288, recv) }

//go:noinline
func stubS8_289(recv unsafe.Pointer) int { return dispatchS8(289, recv) }

//go:noinline
func stubS8_290(recv unsafe.Pointer) int { return dispatchS8(290, recv) }

//go:noinline
func stubS8_291(recv unsafe.Pointer) int { return dispatchS8(291, recv) }

//go:noinline
func stubS8_292(recv unsafe.Pointer) int { return dispatchS8(292, recv) }

//go:noinline
func stubS8_293(recv unsafe.Pointer) int { return dispatchS8(293, recv) }

//go:noinline
func stubS8_294(recv unsafe.Pointer) int { return dispatchS8(294, recv) }

//go:noinline
func stubS8_295(recv unsafe.Pointer) int { return dispatchS8(295, recv) }

//go:noinline
func stubS8_296(recv unsafe.Pointer) int { return dispatchS8(296, recv) }

//go:noinline
func stubS8_297(recv unsafe.Pointer) int { return dispatchS8(297, recv) }

//go:noinline
func stubS8_298(recv unsafe.Pointer) int { return dispatchS8(298, recv) }

//go:noinline
func stubS8_299(recv unsafe.Pointer) int { return dispatchS8(299, recv) }

//go:noinline
func stubS8_300(recv unsafe.Pointer) int { return dispatchS8(300, recv) }

//go:noinline
func stubS8_301(recv unsafe.Pointer) int { return dispatchS8(301, recv) }

//go:noinline
func stubS8_302(recv unsafe.Pointer) int { return dispatchS8(302, recv) }

//go:noinline
func stubS8_303(recv unsafe.Pointer) int { return dispatchS8(303, recv) }

//go:noinline
func stubS8_304(recv unsafe.Pointer) int { return dispatchS8(304, recv) }

//go:noinline
func stubS8_305(recv unsafe.Pointer) int { return dispatchS8(305, recv) }

//go:noinline
func stubS8_306(recv unsafe.Pointer) int { return dispatchS8(306, recv) }

//go:noinline
func stubS8_307(recv unsafe.Pointer) int { return dispatchS8(307, recv) }

//go:noinline
func stubS8_308(recv unsafe.Pointer) int { return dispatchS8(308, recv) }

//go:noinline
func stubS8_309(recv unsafe.Pointer) int { return dispatchS8(309, recv) }

//go:noinline
func stubS8_310(recv unsafe.Pointer) int { return dispatchS8(310, recv) }

//go:noinline
func stubS8_311(recv unsafe.Pointer) int { return dispatchS8(311, recv) }

//go:noinline
func stubS8_312(recv unsafe.Pointer) int { return dispatchS8(312, recv) }

//go:noinline
func stubS8_313(recv unsafe.Pointer) int { return dispatchS8(313, recv) }

//go:noinline
func stubS8_314(recv unsafe.Pointer) int { return dispatchS8(314, recv) }

//go:noinline
func stubS8_315(recv unsafe.Pointer) int { return dispatchS8(315, recv) }

//go:noinline
func stubS8_316(recv unsafe.Pointer) int { return dispatchS8(316, recv) }

//go:noinline
func stubS8_317(recv unsafe.Pointer) int { return dispatchS8(317, recv) }

//go:noinline
func stubS8_318(recv unsafe.Pointer) int { return dispatchS8(318, recv) }

//go:noinline
func stubS8_319(recv unsafe.Pointer) int { return dispatchS8(319, recv) }

//go:noinline
func stubS8_320(recv unsafe.Pointer) int { return dispatchS8(320, recv) }

//go:noinline
func stubS8_321(recv unsafe.Pointer) int { return dispatchS8(321, recv) }

//go:noinline
func stubS8_322(recv unsafe.Pointer) int { return dispatchS8(322, recv) }

//go:noinline
func stubS8_323(recv unsafe.Pointer) int { return dispatchS8(323, recv) }

//go:noinline
func stubS8_324(recv unsafe.Pointer) int { return dispatchS8(324, recv) }

//go:noinline
func stubS8_325(recv unsafe.Pointer) int { return dispatchS8(325, recv) }

//go:noinline
func stubS8_326(recv unsafe.Pointer) int { return dispatchS8(326, recv) }

//go:noinline
func stubS8_327(recv unsafe.Pointer) int { return dispatchS8(327, recv) }

//go:noinline
func stubS8_328(recv unsafe.Pointer) int { return dispatchS8(328, recv) }

//go:noinline
func stubS8_329(recv unsafe.Pointer) int { return dispatchS8(329, recv) }

//go:noinline
func stubS8_330(recv unsafe.Pointer) int { return dispatchS8(330, recv) }

//go:noinline
func stubS8_331(recv unsafe.Pointer) int { return dispatchS8(331, recv) }

//go:noinline
func stubS8_332(recv unsafe.Pointer) int { return dispatchS8(332, recv) }

//go:noinline
func stubS8_333(recv unsafe.Pointer) int { return dispatchS8(333, recv) }

//go:noinline
func stubS8_334(recv unsafe.Pointer) int { return dispatchS8(334, recv) }

//go:noinline
func stubS8_335(recv unsafe.Pointer) int { return dispatchS8(335, recv) }

//go:noinline
func stubS8_336(recv unsafe.Pointer) int { return dispatchS8(336, recv) }

//go:noinline
func stubS8_337(recv unsafe.Pointer) int { return dispatchS8(337, recv) }

//go:noinline
func stubS8_338(recv unsafe.Pointer) int { return dispatchS8(338, recv) }

//go:noinline
func stubS8_339(recv unsafe.Pointer) int { return dispatchS8(339, recv) }

//go:noinline
func stubS8_340(recv unsafe.Pointer) int { return dispatchS8(340, recv) }

//go:noinline
func stubS8_341(recv unsafe.Pointer) int { return dispatchS8(341, recv) }

//go:noinline
func stubS8_342(recv unsafe.Pointer) int { return dispatchS8(342, recv) }

//go:noinline
func stubS8_343(recv unsafe.Pointer) int { return dispatchS8(343, recv) }

//go:noinline
func stubS8_344(recv unsafe.Pointer) int { return dispatchS8(344, recv) }

//go:noinline
func stubS8_345(recv unsafe.Pointer) int { return dispatchS8(345, recv) }

//go:noinline
func stubS8_346(recv unsafe.Pointer) int { return dispatchS8(346, recv) }

//go:noinline
func stubS8_347(recv unsafe.Pointer) int { return dispatchS8(347, recv) }

//go:noinline
func stubS8_348(recv unsafe.Pointer) int { return dispatchS8(348, recv) }

//go:noinline
func stubS8_349(recv unsafe.Pointer) int { return dispatchS8(349, recv) }

//go:noinline
func stubS8_350(recv unsafe.Pointer) int { return dispatchS8(350, recv) }

//go:noinline
func stubS8_351(recv unsafe.Pointer) int { return dispatchS8(351, recv) }

//go:noinline
func stubS8_352(recv unsafe.Pointer) int { return dispatchS8(352, recv) }

//go:noinline
func stubS8_353(recv unsafe.Pointer) int { return dispatchS8(353, recv) }

//go:noinline
func stubS8_354(recv unsafe.Pointer) int { return dispatchS8(354, recv) }

//go:noinline
func stubS8_355(recv unsafe.Pointer) int { return dispatchS8(355, recv) }

//go:noinline
func stubS8_356(recv unsafe.Pointer) int { return dispatchS8(356, recv) }

//go:noinline
func stubS8_357(recv unsafe.Pointer) int { return dispatchS8(357, recv) }

//go:noinline
func stubS8_358(recv unsafe.Pointer) int { return dispatchS8(358, recv) }

//go:noinline
func stubS8_359(recv unsafe.Pointer) int { return dispatchS8(359, recv) }

//go:noinline
func stubS8_360(recv unsafe.Pointer) int { return dispatchS8(360, recv) }

//go:noinline
func stubS8_361(recv unsafe.Pointer) int { return dispatchS8(361, recv) }

//go:noinline
func stubS8_362(recv unsafe.Pointer) int { return dispatchS8(362, recv) }

//go:noinline
func stubS8_363(recv unsafe.Pointer) int { return dispatchS8(363, recv) }

//go:noinline
func stubS8_364(recv unsafe.Pointer) int { return dispatchS8(364, recv) }

//go:noinline
func stubS8_365(recv unsafe.Pointer) int { return dispatchS8(365, recv) }

//go:noinline
func stubS8_366(recv unsafe.Pointer) int { return dispatchS8(366, recv) }

//go:noinline
func stubS8_367(recv unsafe.Pointer) int { return dispatchS8(367, recv) }

//go:noinline
func stubS8_368(recv unsafe.Pointer) int { return dispatchS8(368, recv) }

//go:noinline
func stubS8_369(recv unsafe.Pointer) int { return dispatchS8(369, recv) }

//go:noinline
func stubS8_370(recv unsafe.Pointer) int { return dispatchS8(370, recv) }

//go:noinline
func stubS8_371(recv unsafe.Pointer) int { return dispatchS8(371, recv) }

//go:noinline
func stubS8_372(recv unsafe.Pointer) int { return dispatchS8(372, recv) }

//go:noinline
func stubS8_373(recv unsafe.Pointer) int { return dispatchS8(373, recv) }

//go:noinline
func stubS8_374(recv unsafe.Pointer) int { return dispatchS8(374, recv) }

//go:noinline
func stubS8_375(recv unsafe.Pointer) int { return dispatchS8(375, recv) }

//go:noinline
func stubS8_376(recv unsafe.Pointer) int { return dispatchS8(376, recv) }

//go:noinline
func stubS8_377(recv unsafe.Pointer) int { return dispatchS8(377, recv) }

//go:noinline
func stubS8_378(recv unsafe.Pointer) int { return dispatchS8(378, recv) }

//go:noinline
func stubS8_379(recv unsafe.Pointer) int { return dispatchS8(379, recv) }

//go:noinline
func stubS8_380(recv unsafe.Pointer) int { return dispatchS8(380, recv) }

//go:noinline
func stubS8_381(recv unsafe.Pointer) int { return dispatchS8(381, recv) }

//go:noinline
func stubS8_382(recv unsafe.Pointer) int { return dispatchS8(382, recv) }

//go:noinline
func stubS8_383(recv unsafe.Pointer) int { return dispatchS8(383, recv) }

//go:noinline
func stubS8_384(recv unsafe.Pointer) int { return dispatchS8(384, recv) }

//go:noinline
func stubS8_385(recv unsafe.Pointer) int { return dispatchS8(385, recv) }

//go:noinline
func stubS8_386(recv unsafe.Pointer) int { return dispatchS8(386, recv) }

//go:noinline
func stubS8_387(recv unsafe.Pointer) int { return dispatchS8(387, recv) }

//go:noinline
func stubS8_388(recv unsafe.Pointer) int { return dispatchS8(388, recv) }

//go:noinline
func stubS8_389(recv unsafe.Pointer) int { return dispatchS8(389, recv) }

//go:noinline
func stubS8_390(recv unsafe.Pointer) int { return dispatchS8(390, recv) }

//go:noinline
func stubS8_391(recv unsafe.Pointer) int { return dispatchS8(391, recv) }

//go:noinline
func stubS8_392(recv unsafe.Pointer) int { return dispatchS8(392, recv) }

//go:noinline
func stubS8_393(recv unsafe.Pointer) int { return dispatchS8(393, recv) }

//go:noinline
func stubS8_394(recv unsafe.Pointer) int { return dispatchS8(394, recv) }

//go:noinline
func stubS8_395(recv unsafe.Pointer) int { return dispatchS8(395, recv) }

//go:noinline
func stubS8_396(recv unsafe.Pointer) int { return dispatchS8(396, recv) }

//go:noinline
func stubS8_397(recv unsafe.Pointer) int { return dispatchS8(397, recv) }

//go:noinline
func stubS8_398(recv unsafe.Pointer) int { return dispatchS8(398, recv) }

//go:noinline
func stubS8_399(recv unsafe.Pointer) int { return dispatchS8(399, recv) }

//go:noinline
func stubS8_400(recv unsafe.Pointer) int { return dispatchS8(400, recv) }

//go:noinline
func stubS8_401(recv unsafe.Pointer) int { return dispatchS8(401, recv) }

//go:noinline
func stubS8_402(recv unsafe.Pointer) int { return dispatchS8(402, recv) }

//go:noinline
func stubS8_403(recv unsafe.Pointer) int { return dispatchS8(403, recv) }

//go:noinline
func stubS8_404(recv unsafe.Pointer) int { return dispatchS8(404, recv) }

//go:noinline
func stubS8_405(recv unsafe.Pointer) int { return dispatchS8(405, recv) }

//go:noinline
func stubS8_406(recv unsafe.Pointer) int { return dispatchS8(406, recv) }

//go:noinline
func stubS8_407(recv unsafe.Pointer) int { return dispatchS8(407, recv) }

//go:noinline
func stubS8_408(recv unsafe.Pointer) int { return dispatchS8(408, recv) }

//go:noinline
func stubS8_409(recv unsafe.Pointer) int { return dispatchS8(409, recv) }

//go:noinline
func stubS8_410(recv unsafe.Pointer) int { return dispatchS8(410, recv) }

//go:noinline
func stubS8_411(recv unsafe.Pointer) int { return dispatchS8(411, recv) }

//go:noinline
func stubS8_412(recv unsafe.Pointer) int { return dispatchS8(412, recv) }

//go:noinline
func stubS8_413(recv unsafe.Pointer) int { return dispatchS8(413, recv) }

//go:noinline
func stubS8_414(recv unsafe.Pointer) int { return dispatchS8(414, recv) }

//go:noinline
func stubS8_415(recv unsafe.Pointer) int { return dispatchS8(415, recv) }

//go:noinline
func stubS8_416(recv unsafe.Pointer) int { return dispatchS8(416, recv) }

//go:noinline
func stubS8_417(recv unsafe.Pointer) int { return dispatchS8(417, recv) }

//go:noinline
func stubS8_418(recv unsafe.Pointer) int { return dispatchS8(418, recv) }

//go:noinline
func stubS8_419(recv unsafe.Pointer) int { return dispatchS8(419, recv) }

//go:noinline
func stubS8_420(recv unsafe.Pointer) int { return dispatchS8(420, recv) }

//go:noinline
func stubS8_421(recv unsafe.Pointer) int { return dispatchS8(421, recv) }

//go:noinline
func stubS8_422(recv unsafe.Pointer) int { return dispatchS8(422, recv) }

//go:noinline
func stubS8_423(recv unsafe.Pointer) int { return dispatchS8(423, recv) }

//go:noinline
func stubS8_424(recv unsafe.Pointer) int { return dispatchS8(424, recv) }

//go:noinline
func stubS8_425(recv unsafe.Pointer) int { return dispatchS8(425, recv) }

//go:noinline
func stubS8_426(recv unsafe.Pointer) int { return dispatchS8(426, recv) }

//go:noinline
func stubS8_427(recv unsafe.Pointer) int { return dispatchS8(427, recv) }

//go:noinline
func stubS8_428(recv unsafe.Pointer) int { return dispatchS8(428, recv) }

//go:noinline
func stubS8_429(recv unsafe.Pointer) int { return dispatchS8(429, recv) }

//go:noinline
func stubS8_430(recv unsafe.Pointer) int { return dispatchS8(430, recv) }

//go:noinline
func stubS8_431(recv unsafe.Pointer) int { return dispatchS8(431, recv) }

//go:noinline
func stubS8_432(recv unsafe.Pointer) int { return dispatchS8(432, recv) }

//go:noinline
func stubS8_433(recv unsafe.Pointer) int { return dispatchS8(433, recv) }

//go:noinline
func stubS8_434(recv unsafe.Pointer) int { return dispatchS8(434, recv) }

//go:noinline
func stubS8_435(recv unsafe.Pointer) int { return dispatchS8(435, recv) }

//go:noinline
func stubS8_436(recv unsafe.Pointer) int { return dispatchS8(436, recv) }

//go:noinline
func stubS8_437(recv unsafe.Pointer) int { return dispatchS8(437, recv) }

//go:noinline
func stubS8_438(recv unsafe.Pointer) int { return dispatchS8(438, recv) }

//go:noinline
func stubS8_439(recv unsafe.Pointer) int { return dispatchS8(439, recv) }

//go:noinline
func stubS8_440(recv unsafe.Pointer) int { return dispatchS8(440, recv) }

//go:noinline
func stubS8_441(recv unsafe.Pointer) int { return dispatchS8(441, recv) }

//go:noinline
func stubS8_442(recv unsafe.Pointer) int { return dispatchS8(442, recv) }

//go:noinline
func stubS8_443(recv unsafe.Pointer) int { return dispatchS8(443, recv) }

//go:noinline
func stubS8_444(recv unsafe.Pointer) int { return dispatchS8(444, recv) }

//go:noinline
func stubS8_445(recv unsafe.Pointer) int { return dispatchS8(445, recv) }

//go:noinline
func stubS8_446(recv unsafe.Pointer) int { return dispatchS8(446, recv) }

//go:noinline
func stubS8_447(recv unsafe.Pointer) int { return dispatchS8(447, recv) }

//go:noinline
func stubS8_448(recv unsafe.Pointer) int { return dispatchS8(448, recv) }

//go:noinline
func stubS8_449(recv unsafe.Pointer) int { return dispatchS8(449, recv) }

//go:noinline
func stubS8_450(recv unsafe.Pointer) int { return dispatchS8(450, recv) }

//go:noinline
func stubS8_451(recv unsafe.Pointer) int { return dispatchS8(451, recv) }

//go:noinline
func stubS8_452(recv unsafe.Pointer) int { return dispatchS8(452, recv) }

//go:noinline
func stubS8_453(recv unsafe.Pointer) int { return dispatchS8(453, recv) }

//go:noinline
func stubS8_454(recv unsafe.Pointer) int { return dispatchS8(454, recv) }

//go:noinline
func stubS8_455(recv unsafe.Pointer) int { return dispatchS8(455, recv) }

//go:noinline
func stubS8_456(recv unsafe.Pointer) int { return dispatchS8(456, recv) }

//go:noinline
func stubS8_457(recv unsafe.Pointer) int { return dispatchS8(457, recv) }

//go:noinline
func stubS8_458(recv unsafe.Pointer) int { return dispatchS8(458, recv) }

//go:noinline
func stubS8_459(recv unsafe.Pointer) int { return dispatchS8(459, recv) }

//go:noinline
func stubS8_460(recv unsafe.Pointer) int { return dispatchS8(460, recv) }

//go:noinline
func stubS8_461(recv unsafe.Pointer) int { return dispatchS8(461, recv) }

//go:noinline
func stubS8_462(recv unsafe.Pointer) int { return dispatchS8(462, recv) }

//go:noinline
func stubS8_463(recv unsafe.Pointer) int { return dispatchS8(463, recv) }

//go:noinline
func stubS8_464(recv unsafe.Pointer) int { return dispatchS8(464, recv) }

//go:noinline
func stubS8_465(recv unsafe.Pointer) int { return dispatchS8(465, recv) }

//go:noinline
func stubS8_466(recv unsafe.Pointer) int { return dispatchS8(466, recv) }

//go:noinline
func stubS8_467(recv unsafe.Pointer) int { return dispatchS8(467, recv) }

//go:noinline
func stubS8_468(recv unsafe.Pointer) int { return dispatchS8(468, recv) }

//go:noinline
func stubS8_469(recv unsafe.Pointer) int { return dispatchS8(469, recv) }

//go:noinline
func stubS8_470(recv unsafe.Pointer) int { return dispatchS8(470, recv) }

//go:noinline
func stubS8_471(recv unsafe.Pointer) int { return dispatchS8(471, recv) }

//go:noinline
func stubS8_472(recv unsafe.Pointer) int { return dispatchS8(472, recv) }

//go:noinline
func stubS8_473(recv unsafe.Pointer) int { return dispatchS8(473, recv) }

//go:noinline
func stubS8_474(recv unsafe.Pointer) int { return dispatchS8(474, recv) }

//go:noinline
func stubS8_475(recv unsafe.Pointer) int { return dispatchS8(475, recv) }

//go:noinline
func stubS8_476(recv unsafe.Pointer) int { return dispatchS8(476, recv) }

//go:noinline
func stubS8_477(recv unsafe.Pointer) int { return dispatchS8(477, recv) }

//go:noinline
func stubS8_478(recv unsafe.Pointer) int { return dispatchS8(478, recv) }

//go:noinline
func stubS8_479(recv unsafe.Pointer) int { return dispatchS8(479, recv) }

//go:noinline
func stubS8_480(recv unsafe.Pointer) int { return dispatchS8(480, recv) }

//go:noinline
func stubS8_481(recv unsafe.Pointer) int { return dispatchS8(481, recv) }

//go:noinline
func stubS8_482(recv unsafe.Pointer) int { return dispatchS8(482, recv) }

//go:noinline
func stubS8_483(recv unsafe.Pointer) int { return dispatchS8(483, recv) }

//go:noinline
func stubS8_484(recv unsafe.Pointer) int { return dispatchS8(484, recv) }

//go:noinline
func stubS8_485(recv unsafe.Pointer) int { return dispatchS8(485, recv) }

//go:noinline
func stubS8_486(recv unsafe.Pointer) int { return dispatchS8(486, recv) }

//go:noinline
func stubS8_487(recv unsafe.Pointer) int { return dispatchS8(487, recv) }

//go:noinline
func stubS8_488(recv unsafe.Pointer) int { return dispatchS8(488, recv) }

//go:noinline
func stubS8_489(recv unsafe.Pointer) int { return dispatchS8(489, recv) }

//go:noinline
func stubS8_490(recv unsafe.Pointer) int { return dispatchS8(490, recv) }

//go:noinline
func stubS8_491(recv unsafe.Pointer) int { return dispatchS8(491, recv) }

//go:noinline
func stubS8_492(recv unsafe.Pointer) int { return dispatchS8(492, recv) }

//go:noinline
func stubS8_493(recv unsafe.Pointer) int { return dispatchS8(493, recv) }

//go:noinline
func stubS8_494(recv unsafe.Pointer) int { return dispatchS8(494, recv) }

//go:noinline
func stubS8_495(recv unsafe.Pointer) int { return dispatchS8(495, recv) }

//go:noinline
func stubS8_496(recv unsafe.Pointer) int { return dispatchS8(496, recv) }

//go:noinline
func stubS8_497(recv unsafe.Pointer) int { return dispatchS8(497, recv) }

//go:noinline
func stubS8_498(recv unsafe.Pointer) int { return dispatchS8(498, recv) }

//go:noinline
func stubS8_499(recv unsafe.Pointer) int { return dispatchS8(499, recv) }

//go:noinline
func stubS8_500(recv unsafe.Pointer) int { return dispatchS8(500, recv) }

//go:noinline
func stubS8_501(recv unsafe.Pointer) int { return dispatchS8(501, recv) }

//go:noinline
func stubS8_502(recv unsafe.Pointer) int { return dispatchS8(502, recv) }

//go:noinline
func stubS8_503(recv unsafe.Pointer) int { return dispatchS8(503, recv) }

//go:noinline
func stubS8_504(recv unsafe.Pointer) int { return dispatchS8(504, recv) }

//go:noinline
func stubS8_505(recv unsafe.Pointer) int { return dispatchS8(505, recv) }

//go:noinline
func stubS8_506(recv unsafe.Pointer) int { return dispatchS8(506, recv) }

//go:noinline
func stubS8_507(recv unsafe.Pointer) int { return dispatchS8(507, recv) }

//go:noinline
func stubS8_508(recv unsafe.Pointer) int { return dispatchS8(508, recv) }

//go:noinline
func stubS8_509(recv unsafe.Pointer) int { return dispatchS8(509, recv) }

//go:noinline
func stubS8_510(recv unsafe.Pointer) int { return dispatchS8(510, recv) }

//go:noinline
func stubS8_511(recv unsafe.Pointer) int { return dispatchS8(511, recv) }

var stubsS8 = [poolSizeS8]uintptr{
	runtype.FuncPC(stubS8_0),
	runtype.FuncPC(stubS8_1),
	runtype.FuncPC(stubS8_2),
	runtype.FuncPC(stubS8_3),
	runtype.FuncPC(stubS8_4),
	runtype.FuncPC(stubS8_5),
	runtype.FuncPC(stubS8_6),
	runtype.FuncPC(stubS8_7),
	runtype.FuncPC(stubS8_8),
	runtype.FuncPC(stubS8_9),
	runtype.FuncPC(stubS8_10),
	runtype.FuncPC(stubS8_11),
	runtype.FuncPC(stubS8_12),
	runtype.FuncPC(stubS8_13),
	runtype.FuncPC(stubS8_14),
	runtype.FuncPC(stubS8_15),
	runtype.FuncPC(stubS8_16),
	runtype.FuncPC(stubS8_17),
	runtype.FuncPC(stubS8_18),
	runtype.FuncPC(stubS8_19),
	runtype.FuncPC(stubS8_20),
	runtype.FuncPC(stubS8_21),
	runtype.FuncPC(stubS8_22),
	runtype.FuncPC(stubS8_23),
	runtype.FuncPC(stubS8_24),
	runtype.FuncPC(stubS8_25),
	runtype.FuncPC(stubS8_26),
	runtype.FuncPC(stubS8_27),
	runtype.FuncPC(stubS8_28),
	runtype.FuncPC(stubS8_29),
	runtype.FuncPC(stubS8_30),
	runtype.FuncPC(stubS8_31),
	runtype.FuncPC(stubS8_32),
	runtype.FuncPC(stubS8_33),
	runtype.FuncPC(stubS8_34),
	runtype.FuncPC(stubS8_35),
	runtype.FuncPC(stubS8_36),
	runtype.FuncPC(stubS8_37),
	runtype.FuncPC(stubS8_38),
	runtype.FuncPC(stubS8_39),
	runtype.FuncPC(stubS8_40),
	runtype.FuncPC(stubS8_41),
	runtype.FuncPC(stubS8_42),
	runtype.FuncPC(stubS8_43),
	runtype.FuncPC(stubS8_44),
	runtype.FuncPC(stubS8_45),
	runtype.FuncPC(stubS8_46),
	runtype.FuncPC(stubS8_47),
	runtype.FuncPC(stubS8_48),
	runtype.FuncPC(stubS8_49),
	runtype.FuncPC(stubS8_50),
	runtype.FuncPC(stubS8_51),
	runtype.FuncPC(stubS8_52),
	runtype.FuncPC(stubS8_53),
	runtype.FuncPC(stubS8_54),
	runtype.FuncPC(stubS8_55),
	runtype.FuncPC(stubS8_56),
	runtype.FuncPC(stubS8_57),
	runtype.FuncPC(stubS8_58),
	runtype.FuncPC(stubS8_59),
	runtype.FuncPC(stubS8_60),
	runtype.FuncPC(stubS8_61),
	runtype.FuncPC(stubS8_62),
	runtype.FuncPC(stubS8_63),
	runtype.FuncPC(stubS8_64),
	runtype.FuncPC(stubS8_65),
	runtype.FuncPC(stubS8_66),
	runtype.FuncPC(stubS8_67),
	runtype.FuncPC(stubS8_68),
	runtype.FuncPC(stubS8_69),
	runtype.FuncPC(stubS8_70),
	runtype.FuncPC(stubS8_71),
	runtype.FuncPC(stubS8_72),
	runtype.FuncPC(stubS8_73),
	runtype.FuncPC(stubS8_74),
	runtype.FuncPC(stubS8_75),
	runtype.FuncPC(stubS8_76),
	runtype.FuncPC(stubS8_77),
	runtype.FuncPC(stubS8_78),
	runtype.FuncPC(stubS8_79),
	runtype.FuncPC(stubS8_80),
	runtype.FuncPC(stubS8_81),
	runtype.FuncPC(stubS8_82),
	runtype.FuncPC(stubS8_83),
	runtype.FuncPC(stubS8_84),
	runtype.FuncPC(stubS8_85),
	runtype.FuncPC(stubS8_86),
	runtype.FuncPC(stubS8_87),
	runtype.FuncPC(stubS8_88),
	runtype.FuncPC(stubS8_89),
	runtype.FuncPC(stubS8_90),
	runtype.FuncPC(stubS8_91),
	runtype.FuncPC(stubS8_92),
	runtype.FuncPC(stubS8_93),
	runtype.FuncPC(stubS8_94),
	runtype.FuncPC(stubS8_95),
	runtype.FuncPC(stubS8_96),
	runtype.FuncPC(stubS8_97),
	runtype.FuncPC(stubS8_98),
	runtype.FuncPC(stubS8_99),
	runtype.FuncPC(stubS8_100),
	runtype.FuncPC(stubS8_101),
	runtype.FuncPC(stubS8_102),
	runtype.FuncPC(stubS8_103),
	runtype.FuncPC(stubS8_104),
	runtype.FuncPC(stubS8_105),
	runtype.FuncPC(stubS8_106),
	runtype.FuncPC(stubS8_107),
	runtype.FuncPC(stubS8_108),
	runtype.FuncPC(stubS8_109),
	runtype.FuncPC(stubS8_110),
	runtype.FuncPC(stubS8_111),
	runtype.FuncPC(stubS8_112),
	runtype.FuncPC(stubS8_113),
	runtype.FuncPC(stubS8_114),
	runtype.FuncPC(stubS8_115),
	runtype.FuncPC(stubS8_116),
	runtype.FuncPC(stubS8_117),
	runtype.FuncPC(stubS8_118),
	runtype.FuncPC(stubS8_119),
	runtype.FuncPC(stubS8_120),
	runtype.FuncPC(stubS8_121),
	runtype.FuncPC(stubS8_122),
	runtype.FuncPC(stubS8_123),
	runtype.FuncPC(stubS8_124),
	runtype.FuncPC(stubS8_125),
	runtype.FuncPC(stubS8_126),
	runtype.FuncPC(stubS8_127),
	runtype.FuncPC(stubS8_128),
	runtype.FuncPC(stubS8_129),
	runtype.FuncPC(stubS8_130),
	runtype.FuncPC(stubS8_131),
	runtype.FuncPC(stubS8_132),
	runtype.FuncPC(stubS8_133),
	runtype.FuncPC(stubS8_134),
	runtype.FuncPC(stubS8_135),
	runtype.FuncPC(stubS8_136),
	runtype.FuncPC(stubS8_137),
	runtype.FuncPC(stubS8_138),
	runtype.FuncPC(stubS8_139),
	runtype.FuncPC(stubS8_140),
	runtype.FuncPC(stubS8_141),
	runtype.FuncPC(stubS8_142),
	runtype.FuncPC(stubS8_143),
	runtype.FuncPC(stubS8_144),
	runtype.FuncPC(stubS8_145),
	runtype.FuncPC(stubS8_146),
	runtype.FuncPC(stubS8_147),
	runtype.FuncPC(stubS8_148),
	runtype.FuncPC(stubS8_149),
	runtype.FuncPC(stubS8_150),
	runtype.FuncPC(stubS8_151),
	runtype.FuncPC(stubS8_152),
	runtype.FuncPC(stubS8_153),
	runtype.FuncPC(stubS8_154),
	runtype.FuncPC(stubS8_155),
	runtype.FuncPC(stubS8_156),
	runtype.FuncPC(stubS8_157),
	runtype.FuncPC(stubS8_158),
	runtype.FuncPC(stubS8_159),
	runtype.FuncPC(stubS8_160),
	runtype.FuncPC(stubS8_161),
	runtype.FuncPC(stubS8_162),
	runtype.FuncPC(stubS8_163),
	runtype.FuncPC(stubS8_164),
	runtype.FuncPC(stubS8_165),
	runtype.FuncPC(stubS8_166),
	runtype.FuncPC(stubS8_167),
	runtype.FuncPC(stubS8_168),
	runtype.FuncPC(stubS8_169),
	runtype.FuncPC(stubS8_170),
	runtype.FuncPC(stubS8_171),
	runtype.FuncPC(stubS8_172),
	runtype.FuncPC(stubS8_173),
	runtype.FuncPC(stubS8_174),
	runtype.FuncPC(stubS8_175),
	runtype.FuncPC(stubS8_176),
	runtype.FuncPC(stubS8_177),
	runtype.FuncPC(stubS8_178),
	runtype.FuncPC(stubS8_179),
	runtype.FuncPC(stubS8_180),
	runtype.FuncPC(stubS8_181),
	runtype.FuncPC(stubS8_182),
	runtype.FuncPC(stubS8_183),
	runtype.FuncPC(stubS8_184),
	runtype.FuncPC(stubS8_185),
	runtype.FuncPC(stubS8_186),
	runtype.FuncPC(stubS8_187),
	runtype.FuncPC(stubS8_188),
	runtype.FuncPC(stubS8_189),
	runtype.FuncPC(stubS8_190),
	runtype.FuncPC(stubS8_191),
	runtype.FuncPC(stubS8_192),
	runtype.FuncPC(stubS8_193),
	runtype.FuncPC(stubS8_194),
	runtype.FuncPC(stubS8_195),
	runtype.FuncPC(stubS8_196),
	runtype.FuncPC(stubS8_197),
	runtype.FuncPC(stubS8_198),
	runtype.FuncPC(stubS8_199),
	runtype.FuncPC(stubS8_200),
	runtype.FuncPC(stubS8_201),
	runtype.FuncPC(stubS8_202),
	runtype.FuncPC(stubS8_203),
	runtype.FuncPC(stubS8_204),
	runtype.FuncPC(stubS8_205),
	runtype.FuncPC(stubS8_206),
	runtype.FuncPC(stubS8_207),
	runtype.FuncPC(stubS8_208),
	runtype.FuncPC(stubS8_209),
	runtype.FuncPC(stubS8_210),
	runtype.FuncPC(stubS8_211),
	runtype.FuncPC(stubS8_212),
	runtype.FuncPC(stubS8_213),
	runtype.FuncPC(stubS8_214),
	runtype.FuncPC(stubS8_215),
	runtype.FuncPC(stubS8_216),
	runtype.FuncPC(stubS8_217),
	runtype.FuncPC(stubS8_218),
	runtype.FuncPC(stubS8_219),
	runtype.FuncPC(stubS8_220),
	runtype.FuncPC(stubS8_221),
	runtype.FuncPC(stubS8_222),
	runtype.FuncPC(stubS8_223),
	runtype.FuncPC(stubS8_224),
	runtype.FuncPC(stubS8_225),
	runtype.FuncPC(stubS8_226),
	runtype.FuncPC(stubS8_227),
	runtype.FuncPC(stubS8_228),
	runtype.FuncPC(stubS8_229),
	runtype.FuncPC(stubS8_230),
	runtype.FuncPC(stubS8_231),
	runtype.FuncPC(stubS8_232),
	runtype.FuncPC(stubS8_233),
	runtype.FuncPC(stubS8_234),
	runtype.FuncPC(stubS8_235),
	runtype.FuncPC(stubS8_236),
	runtype.FuncPC(stubS8_237),
	runtype.FuncPC(stubS8_238),
	runtype.FuncPC(stubS8_239),
	runtype.FuncPC(stubS8_240),
	runtype.FuncPC(stubS8_241),
	runtype.FuncPC(stubS8_242),
	runtype.FuncPC(stubS8_243),
	runtype.FuncPC(stubS8_244),
	runtype.FuncPC(stubS8_245),
	runtype.FuncPC(stubS8_246),
	runtype.FuncPC(stubS8_247),
	runtype.FuncPC(stubS8_248),
	runtype.FuncPC(stubS8_249),
	runtype.FuncPC(stubS8_250),
	runtype.FuncPC(stubS8_251),
	runtype.FuncPC(stubS8_252),
	runtype.FuncPC(stubS8_253),
	runtype.FuncPC(stubS8_254),
	runtype.FuncPC(stubS8_255),
	runtype.FuncPC(stubS8_256),
	runtype.FuncPC(stubS8_257),
	runtype.FuncPC(stubS8_258),
	runtype.FuncPC(stubS8_259),
	runtype.FuncPC(stubS8_260),
	runtype.FuncPC(stubS8_261),
	runtype.FuncPC(stubS8_262),
	runtype.FuncPC(stubS8_263),
	runtype.FuncPC(stubS8_264),
	runtype.FuncPC(stubS8_265),
	runtype.FuncPC(stubS8_266),
	runtype.FuncPC(stubS8_267),
	runtype.FuncPC(stubS8_268),
	runtype.FuncPC(stubS8_269),
	runtype.FuncPC(stubS8_270),
	runtype.FuncPC(stubS8_271),
	runtype.FuncPC(stubS8_272),
	runtype.FuncPC(stubS8_273),
	runtype.FuncPC(stubS8_274),
	runtype.FuncPC(stubS8_275),
	runtype.FuncPC(stubS8_276),
	runtype.FuncPC(stubS8_277),
	runtype.FuncPC(stubS8_278),
	runtype.FuncPC(stubS8_279),
	runtype.FuncPC(stubS8_280),
	runtype.FuncPC(stubS8_281),
	runtype.FuncPC(stubS8_282),
	runtype.FuncPC(stubS8_283),
	runtype.FuncPC(stubS8_284),
	runtype.FuncPC(stubS8_285),
	runtype.FuncPC(stubS8_286),
	runtype.FuncPC(stubS8_287),
	runtype.FuncPC(stubS8_288),
	runtype.FuncPC(stubS8_289),
	runtype.FuncPC(stubS8_290),
	runtype.FuncPC(stubS8_291),
	runtype.FuncPC(stubS8_292),
	runtype.FuncPC(stubS8_293),
	runtype.FuncPC(stubS8_294),
	runtype.FuncPC(stubS8_295),
	runtype.FuncPC(stubS8_296),
	runtype.FuncPC(stubS8_297),
	runtype.FuncPC(stubS8_298),
	runtype.FuncPC(stubS8_299),
	runtype.FuncPC(stubS8_300),
	runtype.FuncPC(stubS8_301),
	runtype.FuncPC(stubS8_302),
	runtype.FuncPC(stubS8_303),
	runtype.FuncPC(stubS8_304),
	runtype.FuncPC(stubS8_305),
	runtype.FuncPC(stubS8_306),
	runtype.FuncPC(stubS8_307),
	runtype.FuncPC(stubS8_308),
	runtype.FuncPC(stubS8_309),
	runtype.FuncPC(stubS8_310),
	runtype.FuncPC(stubS8_311),
	runtype.FuncPC(stubS8_312),
	runtype.FuncPC(stubS8_313),
	runtype.FuncPC(stubS8_314),
	runtype.FuncPC(stubS8_315),
	runtype.FuncPC(stubS8_316),
	runtype.FuncPC(stubS8_317),
	runtype.FuncPC(stubS8_318),
	runtype.FuncPC(stubS8_319),
	runtype.FuncPC(stubS8_320),
	runtype.FuncPC(stubS8_321),
	runtype.FuncPC(stubS8_322),
	runtype.FuncPC(stubS8_323),
	runtype.FuncPC(stubS8_324),
	runtype.FuncPC(stubS8_325),
	runtype.FuncPC(stubS8_326),
	runtype.FuncPC(stubS8_327),
	runtype.FuncPC(stubS8_328),
	runtype.FuncPC(stubS8_329),
	runtype.FuncPC(stubS8_330),
	runtype.FuncPC(stubS8_331),
	runtype.FuncPC(stubS8_332),
	runtype.FuncPC(stubS8_333),
	runtype.FuncPC(stubS8_334),
	runtype.FuncPC(stubS8_335),
	runtype.FuncPC(stubS8_336),
	runtype.FuncPC(stubS8_337),
	runtype.FuncPC(stubS8_338),
	runtype.FuncPC(stubS8_339),
	runtype.FuncPC(stubS8_340),
	runtype.FuncPC(stubS8_341),
	runtype.FuncPC(stubS8_342),
	runtype.FuncPC(stubS8_343),
	runtype.FuncPC(stubS8_344),
	runtype.FuncPC(stubS8_345),
	runtype.FuncPC(stubS8_346),
	runtype.FuncPC(stubS8_347),
	runtype.FuncPC(stubS8_348),
	runtype.FuncPC(stubS8_349),
	runtype.FuncPC(stubS8_350),
	runtype.FuncPC(stubS8_351),
	runtype.FuncPC(stubS8_352),
	runtype.FuncPC(stubS8_353),
	runtype.FuncPC(stubS8_354),
	runtype.FuncPC(stubS8_355),
	runtype.FuncPC(stubS8_356),
	runtype.FuncPC(stubS8_357),
	runtype.FuncPC(stubS8_358),
	runtype.FuncPC(stubS8_359),
	runtype.FuncPC(stubS8_360),
	runtype.FuncPC(stubS8_361),
	runtype.FuncPC(stubS8_362),
	runtype.FuncPC(stubS8_363),
	runtype.FuncPC(stubS8_364),
	runtype.FuncPC(stubS8_365),
	runtype.FuncPC(stubS8_366),
	runtype.FuncPC(stubS8_367),
	runtype.FuncPC(stubS8_368),
	runtype.FuncPC(stubS8_369),
	runtype.FuncPC(stubS8_370),
	runtype.FuncPC(stubS8_371),
	runtype.FuncPC(stubS8_372),
	runtype.FuncPC(stubS8_373),
	runtype.FuncPC(stubS8_374),
	runtype.FuncPC(stubS8_375),
	runtype.FuncPC(stubS8_376),
	runtype.FuncPC(stubS8_377),
	runtype.FuncPC(stubS8_378),
	runtype.FuncPC(stubS8_379),
	runtype.FuncPC(stubS8_380),
	runtype.FuncPC(stubS8_381),
	runtype.FuncPC(stubS8_382),
	runtype.FuncPC(stubS8_383),
	runtype.FuncPC(stubS8_384),
	runtype.FuncPC(stubS8_385),
	runtype.FuncPC(stubS8_386),
	runtype.FuncPC(stubS8_387),
	runtype.FuncPC(stubS8_388),
	runtype.FuncPC(stubS8_389),
	runtype.FuncPC(stubS8_390),
	runtype.FuncPC(stubS8_391),
	runtype.FuncPC(stubS8_392),
	runtype.FuncPC(stubS8_393),
	runtype.FuncPC(stubS8_394),
	runtype.FuncPC(stubS8_395),
	runtype.FuncPC(stubS8_396),
	runtype.FuncPC(stubS8_397),
	runtype.FuncPC(stubS8_398),
	runtype.FuncPC(stubS8_399),
	runtype.FuncPC(stubS8_400),
	runtype.FuncPC(stubS8_401),
	runtype.FuncPC(stubS8_402),
	runtype.FuncPC(stubS8_403),
	runtype.FuncPC(stubS8_404),
	runtype.FuncPC(stubS8_405),
	runtype.FuncPC(stubS8_406),
	runtype.FuncPC(stubS8_407),
	runtype.FuncPC(stubS8_408),
	runtype.FuncPC(stubS8_409),
	runtype.FuncPC(stubS8_410),
	runtype.FuncPC(stubS8_411),
	runtype.FuncPC(stubS8_412),
	runtype.FuncPC(stubS8_413),
	runtype.FuncPC(stubS8_414),
	runtype.FuncPC(stubS8_415),
	runtype.FuncPC(stubS8_416),
	runtype.FuncPC(stubS8_417),
	runtype.FuncPC(stubS8_418),
	runtype.FuncPC(stubS8_419),
	runtype.FuncPC(stubS8_420),
	runtype.FuncPC(stubS8_421),
	runtype.FuncPC(stubS8_422),
	runtype.FuncPC(stubS8_423),
	runtype.FuncPC(stubS8_424),
	runtype.FuncPC(stubS8_425),
	runtype.FuncPC(stubS8_426),
	runtype.FuncPC(stubS8_427),
	runtype.FuncPC(stubS8_428),
	runtype.FuncPC(stubS8_429),
	runtype.FuncPC(stubS8_430),
	runtype.FuncPC(stubS8_431),
	runtype.FuncPC(stubS8_432),
	runtype.FuncPC(stubS8_433),
	runtype.FuncPC(stubS8_434),
	runtype.FuncPC(stubS8_435),
	runtype.FuncPC(stubS8_436),
	runtype.FuncPC(stubS8_437),
	runtype.FuncPC(stubS8_438),
	runtype.FuncPC(stubS8_439),
	runtype.FuncPC(stubS8_440),
	runtype.FuncPC(stubS8_441),
	runtype.FuncPC(stubS8_442),
	runtype.FuncPC(stubS8_443),
	runtype.FuncPC(stubS8_444),
	runtype.FuncPC(stubS8_445),
	runtype.FuncPC(stubS8_446),
	runtype.FuncPC(stubS8_447),
	runtype.FuncPC(stubS8_448),
	runtype.FuncPC(stubS8_449),
	runtype.FuncPC(stubS8_450),
	runtype.FuncPC(stubS8_451),
	runtype.FuncPC(stubS8_452),
	runtype.FuncPC(stubS8_453),
	runtype.FuncPC(stubS8_454),
	runtype.FuncPC(stubS8_455),
	runtype.FuncPC(stubS8_456),
	runtype.FuncPC(stubS8_457),
	runtype.FuncPC(stubS8_458),
	runtype.FuncPC(stubS8_459),
	runtype.FuncPC(stubS8_460),
	runtype.FuncPC(stubS8_461),
	runtype.FuncPC(stubS8_462),
	runtype.FuncPC(stubS8_463),
	runtype.FuncPC(stubS8_464),
	runtype.FuncPC(stubS8_465),
	runtype.FuncPC(stubS8_466),
	runtype.FuncPC(stubS8_467),
	runtype.FuncPC(stubS8_468),
	runtype.FuncPC(stubS8_469),
	runtype.FuncPC(stubS8_470),
	runtype.FuncPC(stubS8_471),
	runtype.FuncPC(stubS8_472),
	runtype.FuncPC(stubS8_473),
	runtype.FuncPC(stubS8_474),
	runtype.FuncPC(stubS8_475),
	runtype.FuncPC(stubS8_476),
	runtype.FuncPC(stubS8_477),
	runtype.FuncPC(stubS8_478),
	runtype.FuncPC(stubS8_479),
	runtype.FuncPC(stubS8_480),
	runtype.FuncPC(stubS8_481),
	runtype.FuncPC(stubS8_482),
	runtype.FuncPC(stubS8_483),
	runtype.FuncPC(stubS8_484),
	runtype.FuncPC(stubS8_485),
	runtype.FuncPC(stubS8_486),
	runtype.FuncPC(stubS8_487),
	runtype.FuncPC(stubS8_488),
	runtype.FuncPC(stubS8_489),
	runtype.FuncPC(stubS8_490),
	runtype.FuncPC(stubS8_491),
	runtype.FuncPC(stubS8_492),
	runtype.FuncPC(stubS8_493),
	runtype.FuncPC(stubS8_494),
	runtype.FuncPC(stubS8_495),
	runtype.FuncPC(stubS8_496),
	runtype.FuncPC(stubS8_497),
	runtype.FuncPC(stubS8_498),
	runtype.FuncPC(stubS8_499),
	runtype.FuncPC(stubS8_500),
	runtype.FuncPC(stubS8_501),
	runtype.FuncPC(stubS8_502),
	runtype.FuncPC(stubS8_503),
	runtype.FuncPC(stubS8_504),
	runtype.FuncPC(stubS8_505),
	runtype.FuncPC(stubS8_506),
	runtype.FuncPC(stubS8_507),
	runtype.FuncPC(stubS8_508),
	runtype.FuncPC(stubS8_509),
	runtype.FuncPC(stubS8_510),
	runtype.FuncPC(stubS8_511),
}
