// Code generated by gen_pools.go; DO NOT EDIT.
// Shape S10 pool: 256 slots (128 on wasm).

package stubs

import (
	"unsafe"

	"github.com/mvm-sh/mvm/runtype"
)

//go:noinline
func stubS10_0(recv unsafe.Pointer, i, j int) { dispatchS10(0, recv, i, j) }

//go:noinline
func stubS10_1(recv unsafe.Pointer, i, j int) { dispatchS10(1, recv, i, j) }

//go:noinline
func stubS10_2(recv unsafe.Pointer, i, j int) { dispatchS10(2, recv, i, j) }

//go:noinline
func stubS10_3(recv unsafe.Pointer, i, j int) { dispatchS10(3, recv, i, j) }

//go:noinline
func stubS10_4(recv unsafe.Pointer, i, j int) { dispatchS10(4, recv, i, j) }

//go:noinline
func stubS10_5(recv unsafe.Pointer, i, j int) { dispatchS10(5, recv, i, j) }

//go:noinline
func stubS10_6(recv unsafe.Pointer, i, j int) { dispatchS10(6, recv, i, j) }

//go:noinline
func stubS10_7(recv unsafe.Pointer, i, j int) { dispatchS10(7, recv, i, j) }

//go:noinline
func stubS10_8(recv unsafe.Pointer, i, j int) { dispatchS10(8, recv, i, j) }

//go:noinline
func stubS10_9(recv unsafe.Pointer, i, j int) { dispatchS10(9, recv, i, j) }

//go:noinline
func stubS10_10(recv unsafe.Pointer, i, j int) { dispatchS10(10, recv, i, j) }

//go:noinline
func stubS10_11(recv unsafe.Pointer, i, j int) { dispatchS10(11, recv, i, j) }

//go:noinline
func stubS10_12(recv unsafe.Pointer, i, j int) { dispatchS10(12, recv, i, j) }

//go:noinline
func stubS10_13(recv unsafe.Pointer, i, j int) { dispatchS10(13, recv, i, j) }

//go:noinline
func stubS10_14(recv unsafe.Pointer, i, j int) { dispatchS10(14, recv, i, j) }

//go:noinline
func stubS10_15(recv unsafe.Pointer, i, j int) { dispatchS10(15, recv, i, j) }

//go:noinline
func stubS10_16(recv unsafe.Pointer, i, j int) { dispatchS10(16, recv, i, j) }

//go:noinline
func stubS10_17(recv unsafe.Pointer, i, j int) { dispatchS10(17, recv, i, j) }

//go:noinline
func stubS10_18(recv unsafe.Pointer, i, j int) { dispatchS10(18, recv, i, j) }

//go:noinline
func stubS10_19(recv unsafe.Pointer, i, j int) { dispatchS10(19, recv, i, j) }

//go:noinline
func stubS10_20(recv unsafe.Pointer, i, j int) { dispatchS10(20, recv, i, j) }

//go:noinline
func stubS10_21(recv unsafe.Pointer, i, j int) { dispatchS10(21, recv, i, j) }

//go:noinline
func stubS10_22(recv unsafe.Pointer, i, j int) { dispatchS10(22, recv, i, j) }

//go:noinline
func stubS10_23(recv unsafe.Pointer, i, j int) { dispatchS10(23, recv, i, j) }

//go:noinline
func stubS10_24(recv unsafe.Pointer, i, j int) { dispatchS10(24, recv, i, j) }

//go:noinline
func stubS10_25(recv unsafe.Pointer, i, j int) { dispatchS10(25, recv, i, j) }

//go:noinline
func stubS10_26(recv unsafe.Pointer, i, j int) { dispatchS10(26, recv, i, j) }

//go:noinline
func stubS10_27(recv unsafe.Pointer, i, j int) { dispatchS10(27, recv, i, j) }

//go:noinline
func stubS10_28(recv unsafe.Pointer, i, j int) { dispatchS10(28, recv, i, j) }

//go:noinline
func stubS10_29(recv unsafe.Pointer, i, j int) { dispatchS10(29, recv, i, j) }

//go:noinline
func stubS10_30(recv unsafe.Pointer, i, j int) { dispatchS10(30, recv, i, j) }

//go:noinline
func stubS10_31(recv unsafe.Pointer, i, j int) { dispatchS10(31, recv, i, j) }

//go:noinline
func stubS10_32(recv unsafe.Pointer, i, j int) { dispatchS10(32, recv, i, j) }

//go:noinline
func stubS10_33(recv unsafe.Pointer, i, j int) { dispatchS10(33, recv, i, j) }

//go:noinline
func stubS10_34(recv unsafe.Pointer, i, j int) { dispatchS10(34, recv, i, j) }

//go:noinline
func stubS10_35(recv unsafe.Pointer, i, j int) { dispatchS10(35, recv, i, j) }

//go:noinline
func stubS10_36(recv unsafe.Pointer, i, j int) { dispatchS10(36, recv, i, j) }

//go:noinline
func stubS10_37(recv unsafe.Pointer, i, j int) { dispatchS10(37, recv, i, j) }

//go:noinline
func stubS10_38(recv unsafe.Pointer, i, j int) { dispatchS10(38, recv, i, j) }

//go:noinline
func stubS10_39(recv unsafe.Pointer, i, j int) { dispatchS10(39, recv, i, j) }

//go:noinline
func stubS10_40(recv unsafe.Pointer, i, j int) { dispatchS10(40, recv, i, j) }

//go:noinline
func stubS10_41(recv unsafe.Pointer, i, j int) { dispatchS10(41, recv, i, j) }

//go:noinline
func stubS10_42(recv unsafe.Pointer, i, j int) { dispatchS10(42, recv, i, j) }

//go:noinline
func stubS10_43(recv unsafe.Pointer, i, j int) { dispatchS10(43, recv, i, j) }

//go:noinline
func stubS10_44(recv unsafe.Pointer, i, j int) { dispatchS10(44, recv, i, j) }

//go:noinline
func stubS10_45(recv unsafe.Pointer, i, j int) { dispatchS10(45, recv, i, j) }

//go:noinline
func stubS10_46(recv unsafe.Pointer, i, j int) { dispatchS10(46, recv, i, j) }

//go:noinline
func stubS10_47(recv unsafe.Pointer, i, j int) { dispatchS10(47, recv, i, j) }

//go:noinline
func stubS10_48(recv unsafe.Pointer, i, j int) { dispatchS10(48, recv, i, j) }

//go:noinline
func stubS10_49(recv unsafe.Pointer, i, j int) { dispatchS10(49, recv, i, j) }

//go:noinline
func stubS10_50(recv unsafe.Pointer, i, j int) { dispatchS10(50, recv, i, j) }

//go:noinline
func stubS10_51(recv unsafe.Pointer, i, j int) { dispatchS10(51, recv, i, j) }

//go:noinline
func stubS10_52(recv unsafe.Pointer, i, j int) { dispatchS10(52, recv, i, j) }

//go:noinline
func stubS10_53(recv unsafe.Pointer, i, j int) { dispatchS10(53, recv, i, j) }

//go:noinline
func stubS10_54(recv unsafe.Pointer, i, j int) { dispatchS10(54, recv, i, j) }

//go:noinline
func stubS10_55(recv unsafe.Pointer, i, j int) { dispatchS10(55, recv, i, j) }

//go:noinline
func stubS10_56(recv unsafe.Pointer, i, j int) { dispatchS10(56, recv, i, j) }

//go:noinline
func stubS10_57(recv unsafe.Pointer, i, j int) { dispatchS10(57, recv, i, j) }

//go:noinline
func stubS10_58(recv unsafe.Pointer, i, j int) { dispatchS10(58, recv, i, j) }

//go:noinline
func stubS10_59(recv unsafe.Pointer, i, j int) { dispatchS10(59, recv, i, j) }

//go:noinline
func stubS10_60(recv unsafe.Pointer, i, j int) { dispatchS10(60, recv, i, j) }

//go:noinline
func stubS10_61(recv unsafe.Pointer, i, j int) { dispatchS10(61, recv, i, j) }

//go:noinline
func stubS10_62(recv unsafe.Pointer, i, j int) { dispatchS10(62, recv, i, j) }

//go:noinline
func stubS10_63(recv unsafe.Pointer, i, j int) { dispatchS10(63, recv, i, j) }

//go:noinline
func stubS10_64(recv unsafe.Pointer, i, j int) { dispatchS10(64, recv, i, j) }

//go:noinline
func stubS10_65(recv unsafe.Pointer, i, j int) { dispatchS10(65, recv, i, j) }

//go:noinline
func stubS10_66(recv unsafe.Pointer, i, j int) { dispatchS10(66, recv, i, j) }

//go:noinline
func stubS10_67(recv unsafe.Pointer, i, j int) { dispatchS10(67, recv, i, j) }

//go:noinline
func stubS10_68(recv unsafe.Pointer, i, j int) { dispatchS10(68, recv, i, j) }

//go:noinline
func stubS10_69(recv unsafe.Pointer, i, j int) { dispatchS10(69, recv, i, j) }

//go:noinline
func stubS10_70(recv unsafe.Pointer, i, j int) { dispatchS10(70, recv, i, j) }

//go:noinline
func stubS10_71(recv unsafe.Pointer, i, j int) { dispatchS10(71, recv, i, j) }

//go:noinline
func stubS10_72(recv unsafe.Pointer, i, j int) { dispatchS10(72, recv, i, j) }

//go:noinline
func stubS10_73(recv unsafe.Pointer, i, j int) { dispatchS10(73, recv, i, j) }

//go:noinline
func stubS10_74(recv unsafe.Pointer, i, j int) { dispatchS10(74, recv, i, j) }

//go:noinline
func stubS10_75(recv unsafe.Pointer, i, j int) { dispatchS10(75, recv, i, j) }

//go:noinline
func stubS10_76(recv unsafe.Pointer, i, j int) { dispatchS10(76, recv, i, j) }

//go:noinline
func stubS10_77(recv unsafe.Pointer, i, j int) { dispatchS10(77, recv, i, j) }

//go:noinline
func stubS10_78(recv unsafe.Pointer, i, j int) { dispatchS10(78, recv, i, j) }

//go:noinline
func stubS10_79(recv unsafe.Pointer, i, j int) { dispatchS10(79, recv, i, j) }

//go:noinline
func stubS10_80(recv unsafe.Pointer, i, j int) { dispatchS10(80, recv, i, j) }

//go:noinline
func stubS10_81(recv unsafe.Pointer, i, j int) { dispatchS10(81, recv, i, j) }

//go:noinline
func stubS10_82(recv unsafe.Pointer, i, j int) { dispatchS10(82, recv, i, j) }

//go:noinline
func stubS10_83(recv unsafe.Pointer, i, j int) { dispatchS10(83, recv, i, j) }

//go:noinline
func stubS10_84(recv unsafe.Pointer, i, j int) { dispatchS10(84, recv, i, j) }

//go:noinline
func stubS10_85(recv unsafe.Pointer, i, j int) { dispatchS10(85, recv, i, j) }

//go:noinline
func stubS10_86(recv unsafe.Pointer, i, j int) { dispatchS10(86, recv, i, j) }

//go:noinline
func stubS10_87(recv unsafe.Pointer, i, j int) { dispatchS10(87, recv, i, j) }

//go:noinline
func stubS10_88(recv unsafe.Pointer, i, j int) { dispatchS10(88, recv, i, j) }

//go:noinline
func stubS10_89(recv unsafe.Pointer, i, j int) { dispatchS10(89, recv, i, j) }

//go:noinline
func stubS10_90(recv unsafe.Pointer, i, j int) { dispatchS10(90, recv, i, j) }

//go:noinline
func stubS10_91(recv unsafe.Pointer, i, j int) { dispatchS10(91, recv, i, j) }

//go:noinline
func stubS10_92(recv unsafe.Pointer, i, j int) { dispatchS10(92, recv, i, j) }

//go:noinline
func stubS10_93(recv unsafe.Pointer, i, j int) { dispatchS10(93, recv, i, j) }

//go:noinline
func stubS10_94(recv unsafe.Pointer, i, j int) { dispatchS10(94, recv, i, j) }

//go:noinline
func stubS10_95(recv unsafe.Pointer, i, j int) { dispatchS10(95, recv, i, j) }

//go:noinline
func stubS10_96(recv unsafe.Pointer, i, j int) { dispatchS10(96, recv, i, j) }

//go:noinline
func stubS10_97(recv unsafe.Pointer, i, j int) { dispatchS10(97, recv, i, j) }

//go:noinline
func stubS10_98(recv unsafe.Pointer, i, j int) { dispatchS10(98, recv, i, j) }

//go:noinline
func stubS10_99(recv unsafe.Pointer, i, j int) { dispatchS10(99, recv, i, j) }

//go:noinline
func stubS10_100(recv unsafe.Pointer, i, j int) { dispatchS10(100, recv, i, j) }

//go:noinline
func stubS10_101(recv unsafe.Pointer, i, j int) { dispatchS10(101, recv, i, j) }

//go:noinline
func stubS10_102(recv unsafe.Pointer, i, j int) { dispatchS10(102, recv, i, j) }

//go:noinline
func stubS10_103(recv unsafe.Pointer, i, j int) { dispatchS10(103, recv, i, j) }

//go:noinline
func stubS10_104(recv unsafe.Pointer, i, j int) { dispatchS10(104, recv, i, j) }

//go:noinline
func stubS10_105(recv unsafe.Pointer, i, j int) { dispatchS10(105, recv, i, j) }

//go:noinline
func stubS10_106(recv unsafe.Pointer, i, j int) { dispatchS10(106, recv, i, j) }

//go:noinline
func stubS10_107(recv unsafe.Pointer, i, j int) { dispatchS10(107, recv, i, j) }

//go:noinline
func stubS10_108(recv unsafe.Pointer, i, j int) { dispatchS10(108, recv, i, j) }

//go:noinline
func stubS10_109(recv unsafe.Pointer, i, j int) { dispatchS10(109, recv, i, j) }

//go:noinline
func stubS10_110(recv unsafe.Pointer, i, j int) { dispatchS10(110, recv, i, j) }

//go:noinline
func stubS10_111(recv unsafe.Pointer, i, j int) { dispatchS10(111, recv, i, j) }

//go:noinline
func stubS10_112(recv unsafe.Pointer, i, j int) { dispatchS10(112, recv, i, j) }

//go:noinline
func stubS10_113(recv unsafe.Pointer, i, j int) { dispatchS10(113, recv, i, j) }

//go:noinline
func stubS10_114(recv unsafe.Pointer, i, j int) { dispatchS10(114, recv, i, j) }

//go:noinline
func stubS10_115(recv unsafe.Pointer, i, j int) { dispatchS10(115, recv, i, j) }

//go:noinline
func stubS10_116(recv unsafe.Pointer, i, j int) { dispatchS10(116, recv, i, j) }

//go:noinline
func stubS10_117(recv unsafe.Pointer, i, j int) { dispatchS10(117, recv, i, j) }

//go:noinline
func stubS10_118(recv unsafe.Pointer, i, j int) { dispatchS10(118, recv, i, j) }

//go:noinline
func stubS10_119(recv unsafe.Pointer, i, j int) { dispatchS10(119, recv, i, j) }

//go:noinline
func stubS10_120(recv unsafe.Pointer, i, j int) { dispatchS10(120, recv, i, j) }

//go:noinline
func stubS10_121(recv unsafe.Pointer, i, j int) { dispatchS10(121, recv, i, j) }

//go:noinline
func stubS10_122(recv unsafe.Pointer, i, j int) { dispatchS10(122, recv, i, j) }

//go:noinline
func stubS10_123(recv unsafe.Pointer, i, j int) { dispatchS10(123, recv, i, j) }

//go:noinline
func stubS10_124(recv unsafe.Pointer, i, j int) { dispatchS10(124, recv, i, j) }

//go:noinline
func stubS10_125(recv unsafe.Pointer, i, j int) { dispatchS10(125, recv, i, j) }

//go:noinline
func stubS10_126(recv unsafe.Pointer, i, j int) { dispatchS10(126, recv, i, j) }

//go:noinline
func stubS10_127(recv unsafe.Pointer, i, j int) { dispatchS10(127, recv, i, j) }

var stubsS10 [poolSizeS10]uintptr

func init() {
	stubsS10[0] = runtype.FuncPC(stubS10_0)
	stubsS10[1] = runtype.FuncPC(stubS10_1)
	stubsS10[2] = runtype.FuncPC(stubS10_2)
	stubsS10[3] = runtype.FuncPC(stubS10_3)
	stubsS10[4] = runtype.FuncPC(stubS10_4)
	stubsS10[5] = runtype.FuncPC(stubS10_5)
	stubsS10[6] = runtype.FuncPC(stubS10_6)
	stubsS10[7] = runtype.FuncPC(stubS10_7)
	stubsS10[8] = runtype.FuncPC(stubS10_8)
	stubsS10[9] = runtype.FuncPC(stubS10_9)
	stubsS10[10] = runtype.FuncPC(stubS10_10)
	stubsS10[11] = runtype.FuncPC(stubS10_11)
	stubsS10[12] = runtype.FuncPC(stubS10_12)
	stubsS10[13] = runtype.FuncPC(stubS10_13)
	stubsS10[14] = runtype.FuncPC(stubS10_14)
	stubsS10[15] = runtype.FuncPC(stubS10_15)
	stubsS10[16] = runtype.FuncPC(stubS10_16)
	stubsS10[17] = runtype.FuncPC(stubS10_17)
	stubsS10[18] = runtype.FuncPC(stubS10_18)
	stubsS10[19] = runtype.FuncPC(stubS10_19)
	stubsS10[20] = runtype.FuncPC(stubS10_20)
	stubsS10[21] = runtype.FuncPC(stubS10_21)
	stubsS10[22] = runtype.FuncPC(stubS10_22)
	stubsS10[23] = runtype.FuncPC(stubS10_23)
	stubsS10[24] = runtype.FuncPC(stubS10_24)
	stubsS10[25] = runtype.FuncPC(stubS10_25)
	stubsS10[26] = runtype.FuncPC(stubS10_26)
	stubsS10[27] = runtype.FuncPC(stubS10_27)
	stubsS10[28] = runtype.FuncPC(stubS10_28)
	stubsS10[29] = runtype.FuncPC(stubS10_29)
	stubsS10[30] = runtype.FuncPC(stubS10_30)
	stubsS10[31] = runtype.FuncPC(stubS10_31)
	stubsS10[32] = runtype.FuncPC(stubS10_32)
	stubsS10[33] = runtype.FuncPC(stubS10_33)
	stubsS10[34] = runtype.FuncPC(stubS10_34)
	stubsS10[35] = runtype.FuncPC(stubS10_35)
	stubsS10[36] = runtype.FuncPC(stubS10_36)
	stubsS10[37] = runtype.FuncPC(stubS10_37)
	stubsS10[38] = runtype.FuncPC(stubS10_38)
	stubsS10[39] = runtype.FuncPC(stubS10_39)
	stubsS10[40] = runtype.FuncPC(stubS10_40)
	stubsS10[41] = runtype.FuncPC(stubS10_41)
	stubsS10[42] = runtype.FuncPC(stubS10_42)
	stubsS10[43] = runtype.FuncPC(stubS10_43)
	stubsS10[44] = runtype.FuncPC(stubS10_44)
	stubsS10[45] = runtype.FuncPC(stubS10_45)
	stubsS10[46] = runtype.FuncPC(stubS10_46)
	stubsS10[47] = runtype.FuncPC(stubS10_47)
	stubsS10[48] = runtype.FuncPC(stubS10_48)
	stubsS10[49] = runtype.FuncPC(stubS10_49)
	stubsS10[50] = runtype.FuncPC(stubS10_50)
	stubsS10[51] = runtype.FuncPC(stubS10_51)
	stubsS10[52] = runtype.FuncPC(stubS10_52)
	stubsS10[53] = runtype.FuncPC(stubS10_53)
	stubsS10[54] = runtype.FuncPC(stubS10_54)
	stubsS10[55] = runtype.FuncPC(stubS10_55)
	stubsS10[56] = runtype.FuncPC(stubS10_56)
	stubsS10[57] = runtype.FuncPC(stubS10_57)
	stubsS10[58] = runtype.FuncPC(stubS10_58)
	stubsS10[59] = runtype.FuncPC(stubS10_59)
	stubsS10[60] = runtype.FuncPC(stubS10_60)
	stubsS10[61] = runtype.FuncPC(stubS10_61)
	stubsS10[62] = runtype.FuncPC(stubS10_62)
	stubsS10[63] = runtype.FuncPC(stubS10_63)
	stubsS10[64] = runtype.FuncPC(stubS10_64)
	stubsS10[65] = runtype.FuncPC(stubS10_65)
	stubsS10[66] = runtype.FuncPC(stubS10_66)
	stubsS10[67] = runtype.FuncPC(stubS10_67)
	stubsS10[68] = runtype.FuncPC(stubS10_68)
	stubsS10[69] = runtype.FuncPC(stubS10_69)
	stubsS10[70] = runtype.FuncPC(stubS10_70)
	stubsS10[71] = runtype.FuncPC(stubS10_71)
	stubsS10[72] = runtype.FuncPC(stubS10_72)
	stubsS10[73] = runtype.FuncPC(stubS10_73)
	stubsS10[74] = runtype.FuncPC(stubS10_74)
	stubsS10[75] = runtype.FuncPC(stubS10_75)
	stubsS10[76] = runtype.FuncPC(stubS10_76)
	stubsS10[77] = runtype.FuncPC(stubS10_77)
	stubsS10[78] = runtype.FuncPC(stubS10_78)
	stubsS10[79] = runtype.FuncPC(stubS10_79)
	stubsS10[80] = runtype.FuncPC(stubS10_80)
	stubsS10[81] = runtype.FuncPC(stubS10_81)
	stubsS10[82] = runtype.FuncPC(stubS10_82)
	stubsS10[83] = runtype.FuncPC(stubS10_83)
	stubsS10[84] = runtype.FuncPC(stubS10_84)
	stubsS10[85] = runtype.FuncPC(stubS10_85)
	stubsS10[86] = runtype.FuncPC(stubS10_86)
	stubsS10[87] = runtype.FuncPC(stubS10_87)
	stubsS10[88] = runtype.FuncPC(stubS10_88)
	stubsS10[89] = runtype.FuncPC(stubS10_89)
	stubsS10[90] = runtype.FuncPC(stubS10_90)
	stubsS10[91] = runtype.FuncPC(stubS10_91)
	stubsS10[92] = runtype.FuncPC(stubS10_92)
	stubsS10[93] = runtype.FuncPC(stubS10_93)
	stubsS10[94] = runtype.FuncPC(stubS10_94)
	stubsS10[95] = runtype.FuncPC(stubS10_95)
	stubsS10[96] = runtype.FuncPC(stubS10_96)
	stubsS10[97] = runtype.FuncPC(stubS10_97)
	stubsS10[98] = runtype.FuncPC(stubS10_98)
	stubsS10[99] = runtype.FuncPC(stubS10_99)
	stubsS10[100] = runtype.FuncPC(stubS10_100)
	stubsS10[101] = runtype.FuncPC(stubS10_101)
	stubsS10[102] = runtype.FuncPC(stubS10_102)
	stubsS10[103] = runtype.FuncPC(stubS10_103)
	stubsS10[104] = runtype.FuncPC(stubS10_104)
	stubsS10[105] = runtype.FuncPC(stubS10_105)
	stubsS10[106] = runtype.FuncPC(stubS10_106)
	stubsS10[107] = runtype.FuncPC(stubS10_107)
	stubsS10[108] = runtype.FuncPC(stubS10_108)
	stubsS10[109] = runtype.FuncPC(stubS10_109)
	stubsS10[110] = runtype.FuncPC(stubS10_110)
	stubsS10[111] = runtype.FuncPC(stubS10_111)
	stubsS10[112] = runtype.FuncPC(stubS10_112)
	stubsS10[113] = runtype.FuncPC(stubS10_113)
	stubsS10[114] = runtype.FuncPC(stubS10_114)
	stubsS10[115] = runtype.FuncPC(stubS10_115)
	stubsS10[116] = runtype.FuncPC(stubS10_116)
	stubsS10[117] = runtype.FuncPC(stubS10_117)
	stubsS10[118] = runtype.FuncPC(stubS10_118)
	stubsS10[119] = runtype.FuncPC(stubS10_119)
	stubsS10[120] = runtype.FuncPC(stubS10_120)
	stubsS10[121] = runtype.FuncPC(stubS10_121)
	stubsS10[122] = runtype.FuncPC(stubS10_122)
	stubsS10[123] = runtype.FuncPC(stubS10_123)
	stubsS10[124] = runtype.FuncPC(stubS10_124)
	stubsS10[125] = runtype.FuncPC(stubS10_125)
	stubsS10[126] = runtype.FuncPC(stubS10_126)
	stubsS10[127] = runtype.FuncPC(stubS10_127)
}
