// Code generated by gen_pools.go; DO NOT EDIT.
// Shape S25 pool: 256 slots.

package stubs

import (
	"io/fs"
	"unsafe"

	"github.com/mvm-sh/mvm/runtype"
)

const poolSizeS25 = 256

//go:noinline
func stubS25_0(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(0, recv) }

//go:noinline
func stubS25_1(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(1, recv) }

//go:noinline
func stubS25_2(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(2, recv) }

//go:noinline
func stubS25_3(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(3, recv) }

//go:noinline
func stubS25_4(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(4, recv) }

//go:noinline
func stubS25_5(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(5, recv) }

//go:noinline
func stubS25_6(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(6, recv) }

//go:noinline
func stubS25_7(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(7, recv) }

//go:noinline
func stubS25_8(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(8, recv) }

//go:noinline
func stubS25_9(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(9, recv) }

//go:noinline
func stubS25_10(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(10, recv) }

//go:noinline
func stubS25_11(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(11, recv) }

//go:noinline
func stubS25_12(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(12, recv) }

//go:noinline
func stubS25_13(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(13, recv) }

//go:noinline
func stubS25_14(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(14, recv) }

//go:noinline
func stubS25_15(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(15, recv) }

//go:noinline
func stubS25_16(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(16, recv) }

//go:noinline
func stubS25_17(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(17, recv) }

//go:noinline
func stubS25_18(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(18, recv) }

//go:noinline
func stubS25_19(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(19, recv) }

//go:noinline
func stubS25_20(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(20, recv) }

//go:noinline
func stubS25_21(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(21, recv) }

//go:noinline
func stubS25_22(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(22, recv) }

//go:noinline
func stubS25_23(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(23, recv) }

//go:noinline
func stubS25_24(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(24, recv) }

//go:noinline
func stubS25_25(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(25, recv) }

//go:noinline
func stubS25_26(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(26, recv) }

//go:noinline
func stubS25_27(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(27, recv) }

//go:noinline
func stubS25_28(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(28, recv) }

//go:noinline
func stubS25_29(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(29, recv) }

//go:noinline
func stubS25_30(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(30, recv) }

//go:noinline
func stubS25_31(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(31, recv) }

//go:noinline
func stubS25_32(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(32, recv) }

//go:noinline
func stubS25_33(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(33, recv) }

//go:noinline
func stubS25_34(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(34, recv) }

//go:noinline
func stubS25_35(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(35, recv) }

//go:noinline
func stubS25_36(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(36, recv) }

//go:noinline
func stubS25_37(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(37, recv) }

//go:noinline
func stubS25_38(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(38, recv) }

//go:noinline
func stubS25_39(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(39, recv) }

//go:noinline
func stubS25_40(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(40, recv) }

//go:noinline
func stubS25_41(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(41, recv) }

//go:noinline
func stubS25_42(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(42, recv) }

//go:noinline
func stubS25_43(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(43, recv) }

//go:noinline
func stubS25_44(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(44, recv) }

//go:noinline
func stubS25_45(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(45, recv) }

//go:noinline
func stubS25_46(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(46, recv) }

//go:noinline
func stubS25_47(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(47, recv) }

//go:noinline
func stubS25_48(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(48, recv) }

//go:noinline
func stubS25_49(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(49, recv) }

//go:noinline
func stubS25_50(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(50, recv) }

//go:noinline
func stubS25_51(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(51, recv) }

//go:noinline
func stubS25_52(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(52, recv) }

//go:noinline
func stubS25_53(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(53, recv) }

//go:noinline
func stubS25_54(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(54, recv) }

//go:noinline
func stubS25_55(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(55, recv) }

//go:noinline
func stubS25_56(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(56, recv) }

//go:noinline
func stubS25_57(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(57, recv) }

//go:noinline
func stubS25_58(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(58, recv) }

//go:noinline
func stubS25_59(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(59, recv) }

//go:noinline
func stubS25_60(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(60, recv) }

//go:noinline
func stubS25_61(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(61, recv) }

//go:noinline
func stubS25_62(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(62, recv) }

//go:noinline
func stubS25_63(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(63, recv) }

//go:noinline
func stubS25_64(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(64, recv) }

//go:noinline
func stubS25_65(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(65, recv) }

//go:noinline
func stubS25_66(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(66, recv) }

//go:noinline
func stubS25_67(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(67, recv) }

//go:noinline
func stubS25_68(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(68, recv) }

//go:noinline
func stubS25_69(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(69, recv) }

//go:noinline
func stubS25_70(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(70, recv) }

//go:noinline
func stubS25_71(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(71, recv) }

//go:noinline
func stubS25_72(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(72, recv) }

//go:noinline
func stubS25_73(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(73, recv) }

//go:noinline
func stubS25_74(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(74, recv) }

//go:noinline
func stubS25_75(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(75, recv) }

//go:noinline
func stubS25_76(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(76, recv) }

//go:noinline
func stubS25_77(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(77, recv) }

//go:noinline
func stubS25_78(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(78, recv) }

//go:noinline
func stubS25_79(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(79, recv) }

//go:noinline
func stubS25_80(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(80, recv) }

//go:noinline
func stubS25_81(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(81, recv) }

//go:noinline
func stubS25_82(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(82, recv) }

//go:noinline
func stubS25_83(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(83, recv) }

//go:noinline
func stubS25_84(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(84, recv) }

//go:noinline
func stubS25_85(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(85, recv) }

//go:noinline
func stubS25_86(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(86, recv) }

//go:noinline
func stubS25_87(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(87, recv) }

//go:noinline
func stubS25_88(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(88, recv) }

//go:noinline
func stubS25_89(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(89, recv) }

//go:noinline
func stubS25_90(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(90, recv) }

//go:noinline
func stubS25_91(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(91, recv) }

//go:noinline
func stubS25_92(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(92, recv) }

//go:noinline
func stubS25_93(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(93, recv) }

//go:noinline
func stubS25_94(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(94, recv) }

//go:noinline
func stubS25_95(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(95, recv) }

//go:noinline
func stubS25_96(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(96, recv) }

//go:noinline
func stubS25_97(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(97, recv) }

//go:noinline
func stubS25_98(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(98, recv) }

//go:noinline
func stubS25_99(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(99, recv) }

//go:noinline
func stubS25_100(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(100, recv) }

//go:noinline
func stubS25_101(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(101, recv) }

//go:noinline
func stubS25_102(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(102, recv) }

//go:noinline
func stubS25_103(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(103, recv) }

//go:noinline
func stubS25_104(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(104, recv) }

//go:noinline
func stubS25_105(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(105, recv) }

//go:noinline
func stubS25_106(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(106, recv) }

//go:noinline
func stubS25_107(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(107, recv) }

//go:noinline
func stubS25_108(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(108, recv) }

//go:noinline
func stubS25_109(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(109, recv) }

//go:noinline
func stubS25_110(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(110, recv) }

//go:noinline
func stubS25_111(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(111, recv) }

//go:noinline
func stubS25_112(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(112, recv) }

//go:noinline
func stubS25_113(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(113, recv) }

//go:noinline
func stubS25_114(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(114, recv) }

//go:noinline
func stubS25_115(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(115, recv) }

//go:noinline
func stubS25_116(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(116, recv) }

//go:noinline
func stubS25_117(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(117, recv) }

//go:noinline
func stubS25_118(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(118, recv) }

//go:noinline
func stubS25_119(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(119, recv) }

//go:noinline
func stubS25_120(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(120, recv) }

//go:noinline
func stubS25_121(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(121, recv) }

//go:noinline
func stubS25_122(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(122, recv) }

//go:noinline
func stubS25_123(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(123, recv) }

//go:noinline
func stubS25_124(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(124, recv) }

//go:noinline
func stubS25_125(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(125, recv) }

//go:noinline
func stubS25_126(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(126, recv) }

//go:noinline
func stubS25_127(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(127, recv) }

//go:noinline
func stubS25_128(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(128, recv) }

//go:noinline
func stubS25_129(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(129, recv) }

//go:noinline
func stubS25_130(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(130, recv) }

//go:noinline
func stubS25_131(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(131, recv) }

//go:noinline
func stubS25_132(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(132, recv) }

//go:noinline
func stubS25_133(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(133, recv) }

//go:noinline
func stubS25_134(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(134, recv) }

//go:noinline
func stubS25_135(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(135, recv) }

//go:noinline
func stubS25_136(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(136, recv) }

//go:noinline
func stubS25_137(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(137, recv) }

//go:noinline
func stubS25_138(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(138, recv) }

//go:noinline
func stubS25_139(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(139, recv) }

//go:noinline
func stubS25_140(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(140, recv) }

//go:noinline
func stubS25_141(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(141, recv) }

//go:noinline
func stubS25_142(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(142, recv) }

//go:noinline
func stubS25_143(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(143, recv) }

//go:noinline
func stubS25_144(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(144, recv) }

//go:noinline
func stubS25_145(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(145, recv) }

//go:noinline
func stubS25_146(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(146, recv) }

//go:noinline
func stubS25_147(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(147, recv) }

//go:noinline
func stubS25_148(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(148, recv) }

//go:noinline
func stubS25_149(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(149, recv) }

//go:noinline
func stubS25_150(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(150, recv) }

//go:noinline
func stubS25_151(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(151, recv) }

//go:noinline
func stubS25_152(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(152, recv) }

//go:noinline
func stubS25_153(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(153, recv) }

//go:noinline
func stubS25_154(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(154, recv) }

//go:noinline
func stubS25_155(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(155, recv) }

//go:noinline
func stubS25_156(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(156, recv) }

//go:noinline
func stubS25_157(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(157, recv) }

//go:noinline
func stubS25_158(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(158, recv) }

//go:noinline
func stubS25_159(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(159, recv) }

//go:noinline
func stubS25_160(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(160, recv) }

//go:noinline
func stubS25_161(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(161, recv) }

//go:noinline
func stubS25_162(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(162, recv) }

//go:noinline
func stubS25_163(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(163, recv) }

//go:noinline
func stubS25_164(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(164, recv) }

//go:noinline
func stubS25_165(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(165, recv) }

//go:noinline
func stubS25_166(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(166, recv) }

//go:noinline
func stubS25_167(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(167, recv) }

//go:noinline
func stubS25_168(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(168, recv) }

//go:noinline
func stubS25_169(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(169, recv) }

//go:noinline
func stubS25_170(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(170, recv) }

//go:noinline
func stubS25_171(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(171, recv) }

//go:noinline
func stubS25_172(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(172, recv) }

//go:noinline
func stubS25_173(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(173, recv) }

//go:noinline
func stubS25_174(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(174, recv) }

//go:noinline
func stubS25_175(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(175, recv) }

//go:noinline
func stubS25_176(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(176, recv) }

//go:noinline
func stubS25_177(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(177, recv) }

//go:noinline
func stubS25_178(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(178, recv) }

//go:noinline
func stubS25_179(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(179, recv) }

//go:noinline
func stubS25_180(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(180, recv) }

//go:noinline
func stubS25_181(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(181, recv) }

//go:noinline
func stubS25_182(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(182, recv) }

//go:noinline
func stubS25_183(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(183, recv) }

//go:noinline
func stubS25_184(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(184, recv) }

//go:noinline
func stubS25_185(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(185, recv) }

//go:noinline
func stubS25_186(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(186, recv) }

//go:noinline
func stubS25_187(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(187, recv) }

//go:noinline
func stubS25_188(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(188, recv) }

//go:noinline
func stubS25_189(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(189, recv) }

//go:noinline
func stubS25_190(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(190, recv) }

//go:noinline
func stubS25_191(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(191, recv) }

//go:noinline
func stubS25_192(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(192, recv) }

//go:noinline
func stubS25_193(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(193, recv) }

//go:noinline
func stubS25_194(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(194, recv) }

//go:noinline
func stubS25_195(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(195, recv) }

//go:noinline
func stubS25_196(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(196, recv) }

//go:noinline
func stubS25_197(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(197, recv) }

//go:noinline
func stubS25_198(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(198, recv) }

//go:noinline
func stubS25_199(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(199, recv) }

//go:noinline
func stubS25_200(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(200, recv) }

//go:noinline
func stubS25_201(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(201, recv) }

//go:noinline
func stubS25_202(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(202, recv) }

//go:noinline
func stubS25_203(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(203, recv) }

//go:noinline
func stubS25_204(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(204, recv) }

//go:noinline
func stubS25_205(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(205, recv) }

//go:noinline
func stubS25_206(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(206, recv) }

//go:noinline
func stubS25_207(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(207, recv) }

//go:noinline
func stubS25_208(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(208, recv) }

//go:noinline
func stubS25_209(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(209, recv) }

//go:noinline
func stubS25_210(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(210, recv) }

//go:noinline
func stubS25_211(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(211, recv) }

//go:noinline
func stubS25_212(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(212, recv) }

//go:noinline
func stubS25_213(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(213, recv) }

//go:noinline
func stubS25_214(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(214, recv) }

//go:noinline
func stubS25_215(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(215, recv) }

//go:noinline
func stubS25_216(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(216, recv) }

//go:noinline
func stubS25_217(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(217, recv) }

//go:noinline
func stubS25_218(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(218, recv) }

//go:noinline
func stubS25_219(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(219, recv) }

//go:noinline
func stubS25_220(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(220, recv) }

//go:noinline
func stubS25_221(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(221, recv) }

//go:noinline
func stubS25_222(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(222, recv) }

//go:noinline
func stubS25_223(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(223, recv) }

//go:noinline
func stubS25_224(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(224, recv) }

//go:noinline
func stubS25_225(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(225, recv) }

//go:noinline
func stubS25_226(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(226, recv) }

//go:noinline
func stubS25_227(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(227, recv) }

//go:noinline
func stubS25_228(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(228, recv) }

//go:noinline
func stubS25_229(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(229, recv) }

//go:noinline
func stubS25_230(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(230, recv) }

//go:noinline
func stubS25_231(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(231, recv) }

//go:noinline
func stubS25_232(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(232, recv) }

//go:noinline
func stubS25_233(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(233, recv) }

//go:noinline
func stubS25_234(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(234, recv) }

//go:noinline
func stubS25_235(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(235, recv) }

//go:noinline
func stubS25_236(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(236, recv) }

//go:noinline
func stubS25_237(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(237, recv) }

//go:noinline
func stubS25_238(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(238, recv) }

//go:noinline
func stubS25_239(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(239, recv) }

//go:noinline
func stubS25_240(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(240, recv) }

//go:noinline
func stubS25_241(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(241, recv) }

//go:noinline
func stubS25_242(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(242, recv) }

//go:noinline
func stubS25_243(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(243, recv) }

//go:noinline
func stubS25_244(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(244, recv) }

//go:noinline
func stubS25_245(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(245, recv) }

//go:noinline
func stubS25_246(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(246, recv) }

//go:noinline
func stubS25_247(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(247, recv) }

//go:noinline
func stubS25_248(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(248, recv) }

//go:noinline
func stubS25_249(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(249, recv) }

//go:noinline
func stubS25_250(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(250, recv) }

//go:noinline
func stubS25_251(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(251, recv) }

//go:noinline
func stubS25_252(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(252, recv) }

//go:noinline
func stubS25_253(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(253, recv) }

//go:noinline
func stubS25_254(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(254, recv) }

//go:noinline
func stubS25_255(recv unsafe.Pointer) (fs.FileInfo, error) { return dispatchS25(255, recv) }

var stubsS25 = [poolSizeS25]uintptr{
	runtype.FuncPC(stubS25_0),
	runtype.FuncPC(stubS25_1),
	runtype.FuncPC(stubS25_2),
	runtype.FuncPC(stubS25_3),
	runtype.FuncPC(stubS25_4),
	runtype.FuncPC(stubS25_5),
	runtype.FuncPC(stubS25_6),
	runtype.FuncPC(stubS25_7),
	runtype.FuncPC(stubS25_8),
	runtype.FuncPC(stubS25_9),
	runtype.FuncPC(stubS25_10),
	runtype.FuncPC(stubS25_11),
	runtype.FuncPC(stubS25_12),
	runtype.FuncPC(stubS25_13),
	runtype.FuncPC(stubS25_14),
	runtype.FuncPC(stubS25_15),
	runtype.FuncPC(stubS25_16),
	runtype.FuncPC(stubS25_17),
	runtype.FuncPC(stubS25_18),
	runtype.FuncPC(stubS25_19),
	runtype.FuncPC(stubS25_20),
	runtype.FuncPC(stubS25_21),
	runtype.FuncPC(stubS25_22),
	runtype.FuncPC(stubS25_23),
	runtype.FuncPC(stubS25_24),
	runtype.FuncPC(stubS25_25),
	runtype.FuncPC(stubS25_26),
	runtype.FuncPC(stubS25_27),
	runtype.FuncPC(stubS25_28),
	runtype.FuncPC(stubS25_29),
	runtype.FuncPC(stubS25_30),
	runtype.FuncPC(stubS25_31),
	runtype.FuncPC(stubS25_32),
	runtype.FuncPC(stubS25_33),
	runtype.FuncPC(stubS25_34),
	runtype.FuncPC(stubS25_35),
	runtype.FuncPC(stubS25_36),
	runtype.FuncPC(stubS25_37),
	runtype.FuncPC(stubS25_38),
	runtype.FuncPC(stubS25_39),
	runtype.FuncPC(stubS25_40),
	runtype.FuncPC(stubS25_41),
	runtype.FuncPC(stubS25_42),
	runtype.FuncPC(stubS25_43),
	runtype.FuncPC(stubS25_44),
	runtype.FuncPC(stubS25_45),
	runtype.FuncPC(stubS25_46),
	runtype.FuncPC(stubS25_47),
	runtype.FuncPC(stubS25_48),
	runtype.FuncPC(stubS25_49),
	runtype.FuncPC(stubS25_50),
	runtype.FuncPC(stubS25_51),
	runtype.FuncPC(stubS25_52),
	runtype.FuncPC(stubS25_53),
	runtype.FuncPC(stubS25_54),
	runtype.FuncPC(stubS25_55),
	runtype.FuncPC(stubS25_56),
	runtype.FuncPC(stubS25_57),
	runtype.FuncPC(stubS25_58),
	runtype.FuncPC(stubS25_59),
	runtype.FuncPC(stubS25_60),
	runtype.FuncPC(stubS25_61),
	runtype.FuncPC(stubS25_62),
	runtype.FuncPC(stubS25_63),
	runtype.FuncPC(stubS25_64),
	runtype.FuncPC(stubS25_65),
	runtype.FuncPC(stubS25_66),
	runtype.FuncPC(stubS25_67),
	runtype.FuncPC(stubS25_68),
	runtype.FuncPC(stubS25_69),
	runtype.FuncPC(stubS25_70),
	runtype.FuncPC(stubS25_71),
	runtype.FuncPC(stubS25_72),
	runtype.FuncPC(stubS25_73),
	runtype.FuncPC(stubS25_74),
	runtype.FuncPC(stubS25_75),
	runtype.FuncPC(stubS25_76),
	runtype.FuncPC(stubS25_77),
	runtype.FuncPC(stubS25_78),
	runtype.FuncPC(stubS25_79),
	runtype.FuncPC(stubS25_80),
	runtype.FuncPC(stubS25_81),
	runtype.FuncPC(stubS25_82),
	runtype.FuncPC(stubS25_83),
	runtype.FuncPC(stubS25_84),
	runtype.FuncPC(stubS25_85),
	runtype.FuncPC(stubS25_86),
	runtype.FuncPC(stubS25_87),
	runtype.FuncPC(stubS25_88),
	runtype.FuncPC(stubS25_89),
	runtype.FuncPC(stubS25_90),
	runtype.FuncPC(stubS25_91),
	runtype.FuncPC(stubS25_92),
	runtype.FuncPC(stubS25_93),
	runtype.FuncPC(stubS25_94),
	runtype.FuncPC(stubS25_95),
	runtype.FuncPC(stubS25_96),
	runtype.FuncPC(stubS25_97),
	runtype.FuncPC(stubS25_98),
	runtype.FuncPC(stubS25_99),
	runtype.FuncPC(stubS25_100),
	runtype.FuncPC(stubS25_101),
	runtype.FuncPC(stubS25_102),
	runtype.FuncPC(stubS25_103),
	runtype.FuncPC(stubS25_104),
	runtype.FuncPC(stubS25_105),
	runtype.FuncPC(stubS25_106),
	runtype.FuncPC(stubS25_107),
	runtype.FuncPC(stubS25_108),
	runtype.FuncPC(stubS25_109),
	runtype.FuncPC(stubS25_110),
	runtype.FuncPC(stubS25_111),
	runtype.FuncPC(stubS25_112),
	runtype.FuncPC(stubS25_113),
	runtype.FuncPC(stubS25_114),
	runtype.FuncPC(stubS25_115),
	runtype.FuncPC(stubS25_116),
	runtype.FuncPC(stubS25_117),
	runtype.FuncPC(stubS25_118),
	runtype.FuncPC(stubS25_119),
	runtype.FuncPC(stubS25_120),
	runtype.FuncPC(stubS25_121),
	runtype.FuncPC(stubS25_122),
	runtype.FuncPC(stubS25_123),
	runtype.FuncPC(stubS25_124),
	runtype.FuncPC(stubS25_125),
	runtype.FuncPC(stubS25_126),
	runtype.FuncPC(stubS25_127),
	runtype.FuncPC(stubS25_128),
	runtype.FuncPC(stubS25_129),
	runtype.FuncPC(stubS25_130),
	runtype.FuncPC(stubS25_131),
	runtype.FuncPC(stubS25_132),
	runtype.FuncPC(stubS25_133),
	runtype.FuncPC(stubS25_134),
	runtype.FuncPC(stubS25_135),
	runtype.FuncPC(stubS25_136),
	runtype.FuncPC(stubS25_137),
	runtype.FuncPC(stubS25_138),
	runtype.FuncPC(stubS25_139),
	runtype.FuncPC(stubS25_140),
	runtype.FuncPC(stubS25_141),
	runtype.FuncPC(stubS25_142),
	runtype.FuncPC(stubS25_143),
	runtype.FuncPC(stubS25_144),
	runtype.FuncPC(stubS25_145),
	runtype.FuncPC(stubS25_146),
	runtype.FuncPC(stubS25_147),
	runtype.FuncPC(stubS25_148),
	runtype.FuncPC(stubS25_149),
	runtype.FuncPC(stubS25_150),
	runtype.FuncPC(stubS25_151),
	runtype.FuncPC(stubS25_152),
	runtype.FuncPC(stubS25_153),
	runtype.FuncPC(stubS25_154),
	runtype.FuncPC(stubS25_155),
	runtype.FuncPC(stubS25_156),
	runtype.FuncPC(stubS25_157),
	runtype.FuncPC(stubS25_158),
	runtype.FuncPC(stubS25_159),
	runtype.FuncPC(stubS25_160),
	runtype.FuncPC(stubS25_161),
	runtype.FuncPC(stubS25_162),
	runtype.FuncPC(stubS25_163),
	runtype.FuncPC(stubS25_164),
	runtype.FuncPC(stubS25_165),
	runtype.FuncPC(stubS25_166),
	runtype.FuncPC(stubS25_167),
	runtype.FuncPC(stubS25_168),
	runtype.FuncPC(stubS25_169),
	runtype.FuncPC(stubS25_170),
	runtype.FuncPC(stubS25_171),
	runtype.FuncPC(stubS25_172),
	runtype.FuncPC(stubS25_173),
	runtype.FuncPC(stubS25_174),
	runtype.FuncPC(stubS25_175),
	runtype.FuncPC(stubS25_176),
	runtype.FuncPC(stubS25_177),
	runtype.FuncPC(stubS25_178),
	runtype.FuncPC(stubS25_179),
	runtype.FuncPC(stubS25_180),
	runtype.FuncPC(stubS25_181),
	runtype.FuncPC(stubS25_182),
	runtype.FuncPC(stubS25_183),
	runtype.FuncPC(stubS25_184),
	runtype.FuncPC(stubS25_185),
	runtype.FuncPC(stubS25_186),
	runtype.FuncPC(stubS25_187),
	runtype.FuncPC(stubS25_188),
	runtype.FuncPC(stubS25_189),
	runtype.FuncPC(stubS25_190),
	runtype.FuncPC(stubS25_191),
	runtype.FuncPC(stubS25_192),
	runtype.FuncPC(stubS25_193),
	runtype.FuncPC(stubS25_194),
	runtype.FuncPC(stubS25_195),
	runtype.FuncPC(stubS25_196),
	runtype.FuncPC(stubS25_197),
	runtype.FuncPC(stubS25_198),
	runtype.FuncPC(stubS25_199),
	runtype.FuncPC(stubS25_200),
	runtype.FuncPC(stubS25_201),
	runtype.FuncPC(stubS25_202),
	runtype.FuncPC(stubS25_203),
	runtype.FuncPC(stubS25_204),
	runtype.FuncPC(stubS25_205),
	runtype.FuncPC(stubS25_206),
	runtype.FuncPC(stubS25_207),
	runtype.FuncPC(stubS25_208),
	runtype.FuncPC(stubS25_209),
	runtype.FuncPC(stubS25_210),
	runtype.FuncPC(stubS25_211),
	runtype.FuncPC(stubS25_212),
	runtype.FuncPC(stubS25_213),
	runtype.FuncPC(stubS25_214),
	runtype.FuncPC(stubS25_215),
	runtype.FuncPC(stubS25_216),
	runtype.FuncPC(stubS25_217),
	runtype.FuncPC(stubS25_218),
	runtype.FuncPC(stubS25_219),
	runtype.FuncPC(stubS25_220),
	runtype.FuncPC(stubS25_221),
	runtype.FuncPC(stubS25_222),
	runtype.FuncPC(stubS25_223),
	runtype.FuncPC(stubS25_224),
	runtype.FuncPC(stubS25_225),
	runtype.FuncPC(stubS25_226),
	runtype.FuncPC(stubS25_227),
	runtype.FuncPC(stubS25_228),
	runtype.FuncPC(stubS25_229),
	runtype.FuncPC(stubS25_230),
	runtype.FuncPC(stubS25_231),
	runtype.FuncPC(stubS25_232),
	runtype.FuncPC(stubS25_233),
	runtype.FuncPC(stubS25_234),
	runtype.FuncPC(stubS25_235),
	runtype.FuncPC(stubS25_236),
	runtype.FuncPC(stubS25_237),
	runtype.FuncPC(stubS25_238),
	runtype.FuncPC(stubS25_239),
	runtype.FuncPC(stubS25_240),
	runtype.FuncPC(stubS25_241),
	runtype.FuncPC(stubS25_242),
	runtype.FuncPC(stubS25_243),
	runtype.FuncPC(stubS25_244),
	runtype.FuncPC(stubS25_245),
	runtype.FuncPC(stubS25_246),
	runtype.FuncPC(stubS25_247),
	runtype.FuncPC(stubS25_248),
	runtype.FuncPC(stubS25_249),
	runtype.FuncPC(stubS25_250),
	runtype.FuncPC(stubS25_251),
	runtype.FuncPC(stubS25_252),
	runtype.FuncPC(stubS25_253),
	runtype.FuncPC(stubS25_254),
	runtype.FuncPC(stubS25_255),
}
