// Code generated by gen_pools.go; DO NOT EDIT.
// Word-shape pii_ pool: 256 slots (128 on wasm).

package stubs

import (
	"sync/atomic"
	"unsafe"

	"github.com/mvm-sh/mvm/runtype"
)

var (
	slotPoolWpii_ [poolSizeWpii_]CoreFunc
	nextSlotWpii_ atomic.Uint32
)

//go:noinline
func stubWpii__0(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(0, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__1(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(1, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__2(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(2, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__3(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(3, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__4(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(4, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__5(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(5, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__6(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(6, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__7(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(7, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__8(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(8, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__9(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(9, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__10(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(10, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__11(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(11, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__12(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(12, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__13(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(13, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__14(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(14, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__15(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(15, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__16(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(16, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__17(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(17, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__18(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(18, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__19(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(19, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__20(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(20, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__21(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(21, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__22(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(22, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__23(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(23, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__24(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(24, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__25(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(25, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__26(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(26, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__27(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(27, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__28(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(28, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__29(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(29, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__30(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(30, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__31(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(31, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__32(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(32, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__33(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(33, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__34(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(34, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__35(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(35, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__36(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(36, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__37(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(37, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__38(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(38, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__39(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(39, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__40(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(40, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__41(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(41, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__42(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(42, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__43(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(43, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__44(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(44, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__45(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(45, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__46(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(46, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__47(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(47, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__48(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(48, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__49(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(49, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__50(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(50, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__51(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(51, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__52(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(52, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__53(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(53, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__54(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(54, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__55(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(55, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__56(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(56, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__57(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(57, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__58(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(58, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__59(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(59, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__60(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(60, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__61(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(61, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__62(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(62, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__63(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(63, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__64(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(64, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__65(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(65, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__66(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(66, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__67(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(67, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__68(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(68, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__69(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(69, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__70(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(70, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__71(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(71, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__72(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(72, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__73(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(73, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__74(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(74, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__75(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(75, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__76(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(76, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__77(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(77, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__78(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(78, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__79(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(79, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__80(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(80, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__81(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(81, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__82(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(82, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__83(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(83, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__84(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(84, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__85(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(85, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__86(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(86, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__87(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(87, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__88(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(88, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__89(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(89, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__90(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(90, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__91(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(91, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__92(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(92, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__93(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(93, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__94(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(94, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__95(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(95, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__96(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(96, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__97(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(97, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__98(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(98, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__99(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(99, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__100(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(100, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__101(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(101, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__102(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(102, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__103(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(103, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__104(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(104, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__105(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(105, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__106(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(106, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__107(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(107, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__108(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(108, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__109(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(109, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__110(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(110, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__111(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(111, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__112(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(112, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__113(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(113, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__114(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(114, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__115(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(115, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__116(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(116, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__117(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(117, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__118(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(118, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__119(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(119, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__120(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(120, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__121(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(121, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__122(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(122, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__123(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(123, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__124(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(124, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__125(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(125, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__126(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(126, recv, w0, w1, w2)
}

//go:noinline
func stubWpii__127(recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	dispatchWpii_(127, recv, w0, w1, w2)
}

var stubsWpii_ [poolSizeWpii_]uintptr

func dispatchWpii_(slot uint32, recv unsafe.Pointer, w0 unsafe.Pointer, w1 uint64, w2 uint64) {
	var pw [1]unsafe.Pointer
	var sw [2]uint64
	var fw [0]float64
	pw[0] = w0
	sw[0] = w1
	sw[1] = w2
	var rpw [0]unsafe.Pointer
	var rsw [0]uint64
	var rfw [0]float64
	if core := slotPoolWpii_[slot]; core != nil {
		core(recv, pw[:], sw[:], fw[:], rpw[:], rsw[:], rfw[:])
	}
}

func init() {
	stubsWpii_[0] = runtype.FuncPC(stubWpii__0)
	stubsWpii_[1] = runtype.FuncPC(stubWpii__1)
	stubsWpii_[2] = runtype.FuncPC(stubWpii__2)
	stubsWpii_[3] = runtype.FuncPC(stubWpii__3)
	stubsWpii_[4] = runtype.FuncPC(stubWpii__4)
	stubsWpii_[5] = runtype.FuncPC(stubWpii__5)
	stubsWpii_[6] = runtype.FuncPC(stubWpii__6)
	stubsWpii_[7] = runtype.FuncPC(stubWpii__7)
	stubsWpii_[8] = runtype.FuncPC(stubWpii__8)
	stubsWpii_[9] = runtype.FuncPC(stubWpii__9)
	stubsWpii_[10] = runtype.FuncPC(stubWpii__10)
	stubsWpii_[11] = runtype.FuncPC(stubWpii__11)
	stubsWpii_[12] = runtype.FuncPC(stubWpii__12)
	stubsWpii_[13] = runtype.FuncPC(stubWpii__13)
	stubsWpii_[14] = runtype.FuncPC(stubWpii__14)
	stubsWpii_[15] = runtype.FuncPC(stubWpii__15)
	stubsWpii_[16] = runtype.FuncPC(stubWpii__16)
	stubsWpii_[17] = runtype.FuncPC(stubWpii__17)
	stubsWpii_[18] = runtype.FuncPC(stubWpii__18)
	stubsWpii_[19] = runtype.FuncPC(stubWpii__19)
	stubsWpii_[20] = runtype.FuncPC(stubWpii__20)
	stubsWpii_[21] = runtype.FuncPC(stubWpii__21)
	stubsWpii_[22] = runtype.FuncPC(stubWpii__22)
	stubsWpii_[23] = runtype.FuncPC(stubWpii__23)
	stubsWpii_[24] = runtype.FuncPC(stubWpii__24)
	stubsWpii_[25] = runtype.FuncPC(stubWpii__25)
	stubsWpii_[26] = runtype.FuncPC(stubWpii__26)
	stubsWpii_[27] = runtype.FuncPC(stubWpii__27)
	stubsWpii_[28] = runtype.FuncPC(stubWpii__28)
	stubsWpii_[29] = runtype.FuncPC(stubWpii__29)
	stubsWpii_[30] = runtype.FuncPC(stubWpii__30)
	stubsWpii_[31] = runtype.FuncPC(stubWpii__31)
	stubsWpii_[32] = runtype.FuncPC(stubWpii__32)
	stubsWpii_[33] = runtype.FuncPC(stubWpii__33)
	stubsWpii_[34] = runtype.FuncPC(stubWpii__34)
	stubsWpii_[35] = runtype.FuncPC(stubWpii__35)
	stubsWpii_[36] = runtype.FuncPC(stubWpii__36)
	stubsWpii_[37] = runtype.FuncPC(stubWpii__37)
	stubsWpii_[38] = runtype.FuncPC(stubWpii__38)
	stubsWpii_[39] = runtype.FuncPC(stubWpii__39)
	stubsWpii_[40] = runtype.FuncPC(stubWpii__40)
	stubsWpii_[41] = runtype.FuncPC(stubWpii__41)
	stubsWpii_[42] = runtype.FuncPC(stubWpii__42)
	stubsWpii_[43] = runtype.FuncPC(stubWpii__43)
	stubsWpii_[44] = runtype.FuncPC(stubWpii__44)
	stubsWpii_[45] = runtype.FuncPC(stubWpii__45)
	stubsWpii_[46] = runtype.FuncPC(stubWpii__46)
	stubsWpii_[47] = runtype.FuncPC(stubWpii__47)
	stubsWpii_[48] = runtype.FuncPC(stubWpii__48)
	stubsWpii_[49] = runtype.FuncPC(stubWpii__49)
	stubsWpii_[50] = runtype.FuncPC(stubWpii__50)
	stubsWpii_[51] = runtype.FuncPC(stubWpii__51)
	stubsWpii_[52] = runtype.FuncPC(stubWpii__52)
	stubsWpii_[53] = runtype.FuncPC(stubWpii__53)
	stubsWpii_[54] = runtype.FuncPC(stubWpii__54)
	stubsWpii_[55] = runtype.FuncPC(stubWpii__55)
	stubsWpii_[56] = runtype.FuncPC(stubWpii__56)
	stubsWpii_[57] = runtype.FuncPC(stubWpii__57)
	stubsWpii_[58] = runtype.FuncPC(stubWpii__58)
	stubsWpii_[59] = runtype.FuncPC(stubWpii__59)
	stubsWpii_[60] = runtype.FuncPC(stubWpii__60)
	stubsWpii_[61] = runtype.FuncPC(stubWpii__61)
	stubsWpii_[62] = runtype.FuncPC(stubWpii__62)
	stubsWpii_[63] = runtype.FuncPC(stubWpii__63)
	stubsWpii_[64] = runtype.FuncPC(stubWpii__64)
	stubsWpii_[65] = runtype.FuncPC(stubWpii__65)
	stubsWpii_[66] = runtype.FuncPC(stubWpii__66)
	stubsWpii_[67] = runtype.FuncPC(stubWpii__67)
	stubsWpii_[68] = runtype.FuncPC(stubWpii__68)
	stubsWpii_[69] = runtype.FuncPC(stubWpii__69)
	stubsWpii_[70] = runtype.FuncPC(stubWpii__70)
	stubsWpii_[71] = runtype.FuncPC(stubWpii__71)
	stubsWpii_[72] = runtype.FuncPC(stubWpii__72)
	stubsWpii_[73] = runtype.FuncPC(stubWpii__73)
	stubsWpii_[74] = runtype.FuncPC(stubWpii__74)
	stubsWpii_[75] = runtype.FuncPC(stubWpii__75)
	stubsWpii_[76] = runtype.FuncPC(stubWpii__76)
	stubsWpii_[77] = runtype.FuncPC(stubWpii__77)
	stubsWpii_[78] = runtype.FuncPC(stubWpii__78)
	stubsWpii_[79] = runtype.FuncPC(stubWpii__79)
	stubsWpii_[80] = runtype.FuncPC(stubWpii__80)
	stubsWpii_[81] = runtype.FuncPC(stubWpii__81)
	stubsWpii_[82] = runtype.FuncPC(stubWpii__82)
	stubsWpii_[83] = runtype.FuncPC(stubWpii__83)
	stubsWpii_[84] = runtype.FuncPC(stubWpii__84)
	stubsWpii_[85] = runtype.FuncPC(stubWpii__85)
	stubsWpii_[86] = runtype.FuncPC(stubWpii__86)
	stubsWpii_[87] = runtype.FuncPC(stubWpii__87)
	stubsWpii_[88] = runtype.FuncPC(stubWpii__88)
	stubsWpii_[89] = runtype.FuncPC(stubWpii__89)
	stubsWpii_[90] = runtype.FuncPC(stubWpii__90)
	stubsWpii_[91] = runtype.FuncPC(stubWpii__91)
	stubsWpii_[92] = runtype.FuncPC(stubWpii__92)
	stubsWpii_[93] = runtype.FuncPC(stubWpii__93)
	stubsWpii_[94] = runtype.FuncPC(stubWpii__94)
	stubsWpii_[95] = runtype.FuncPC(stubWpii__95)
	stubsWpii_[96] = runtype.FuncPC(stubWpii__96)
	stubsWpii_[97] = runtype.FuncPC(stubWpii__97)
	stubsWpii_[98] = runtype.FuncPC(stubWpii__98)
	stubsWpii_[99] = runtype.FuncPC(stubWpii__99)
	stubsWpii_[100] = runtype.FuncPC(stubWpii__100)
	stubsWpii_[101] = runtype.FuncPC(stubWpii__101)
	stubsWpii_[102] = runtype.FuncPC(stubWpii__102)
	stubsWpii_[103] = runtype.FuncPC(stubWpii__103)
	stubsWpii_[104] = runtype.FuncPC(stubWpii__104)
	stubsWpii_[105] = runtype.FuncPC(stubWpii__105)
	stubsWpii_[106] = runtype.FuncPC(stubWpii__106)
	stubsWpii_[107] = runtype.FuncPC(stubWpii__107)
	stubsWpii_[108] = runtype.FuncPC(stubWpii__108)
	stubsWpii_[109] = runtype.FuncPC(stubWpii__109)
	stubsWpii_[110] = runtype.FuncPC(stubWpii__110)
	stubsWpii_[111] = runtype.FuncPC(stubWpii__111)
	stubsWpii_[112] = runtype.FuncPC(stubWpii__112)
	stubsWpii_[113] = runtype.FuncPC(stubWpii__113)
	stubsWpii_[114] = runtype.FuncPC(stubWpii__114)
	stubsWpii_[115] = runtype.FuncPC(stubWpii__115)
	stubsWpii_[116] = runtype.FuncPC(stubWpii__116)
	stubsWpii_[117] = runtype.FuncPC(stubWpii__117)
	stubsWpii_[118] = runtype.FuncPC(stubWpii__118)
	stubsWpii_[119] = runtype.FuncPC(stubWpii__119)
	stubsWpii_[120] = runtype.FuncPC(stubWpii__120)
	stubsWpii_[121] = runtype.FuncPC(stubWpii__121)
	stubsWpii_[122] = runtype.FuncPC(stubWpii__122)
	stubsWpii_[123] = runtype.FuncPC(stubWpii__123)
	stubsWpii_[124] = runtype.FuncPC(stubWpii__124)
	stubsWpii_[125] = runtype.FuncPC(stubWpii__125)
	stubsWpii_[126] = runtype.FuncPC(stubWpii__126)
	stubsWpii_[127] = runtype.FuncPC(stubWpii__127)
	registerWordPool("pii_", &wordPool{
		next:  &nextSlotWpii_,
		cap:   poolSizeWpii_,
		stubs: stubsWpii_[:],
		slots: slotPoolWpii_[:],
		name:  "Wpii_",
	})
}
